# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tffg1156-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/engenharia/Tony/mem5000/project_1/project_1.cache/wt [current_project]
set_property parent.project_path /home/engenharia/Tony/mem5000/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
add_files /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0_1/design_1_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0_1/design_1_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0_1/design_1_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_1_1/design_1_microblaze_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_1_1/design_1_microblaze_0_1_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_1_1/design_1_microblaze_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_1/design_1_dlmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_1/design_1_dlmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_1/design_1_ilmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_1/design_1_ilmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_dlmb_bram_if_cntlr_1/design_1_dlmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_ilmb_bram_if_cntlr_1/design_1_ilmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_1/design_1_lmb_bram_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_intc_1/design_1_microblaze_0_axi_intc_1.xdc]
set_property used_in_implementation false [get_files -all /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_intc_1/design_1_microblaze_0_axi_intc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_intc_1/design_1_microblaze_0_axi_intc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_1_1/design_1_mdm_1_1.xdc]
set_property used_in_implementation false [get_files -all /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_1_1/design_1_mdm_1_1_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_1_1/design_1_mdm_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_xbar_2/design_1_xbar_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_100M_1/design_1_rst_clk_wiz_0_100M_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_100M_1/design_1_rst_clk_wiz_0_100M_1.xdc]
set_property used_in_implementation false [get_files -all /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_100M_1/design_1_rst_clk_wiz_0_100M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_xbar_3/design_1_xbar_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_100M_1/design_1_rst_mig_7series_0_100M_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_100M_1/design_1_rst_mig_7series_0_100M_1.xdc]
set_property used_in_implementation false [get_files -all /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_100M_1/design_1_rst_mig_7series_0_100M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_timer_0_0/design_1_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_timer_0_0/design_1_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/design_1.bd]

read_vhdl -library xil_defaultlib /home/engenharia/Tony/mem5000/project_1/project_1.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/engenharia/Tony/mem5000/project_1/project_1.srcs/constrs_1/new/pins.xdc
set_property used_in_implementation false [get_files /home/engenharia/Tony/mem5000/project_1/project_1.srcs/constrs_1/new/pins.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_1_wrapper -part xc7a200tffg1156-1


write_checkpoint -force -noxdef design_1_wrapper.dcp

catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
