# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_resultados_rffe.ui'
#
# Created: Mon Feb 20 18:56:10 2017
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(792, 615)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(20, 50, 741, 511))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Tab_Atenuadores = QtGui.QWidget()
        self.Tab_Atenuadores.setObjectName(_fromUtf8("Tab_Atenuadores"))
        self.label_25 = QtGui.QLabel(self.Tab_Atenuadores)
        self.label_25.setGeometry(QtCore.QRect(260, 60, 141, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.Tab_Atenuadores)
        self.label_26.setGeometry(QtCore.QRect(0, 20, 741, 20))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.atenuador_crit_max = QtGui.QLineEdit(self.Tab_Atenuadores)
        self.atenuador_crit_max.setGeometry(QtCore.QRect(400, 50, 113, 26))
        self.atenuador_crit_max.setObjectName(_fromUtf8("atenuador_crit_max"))
        self.label_27 = QtGui.QLabel(self.Tab_Atenuadores)
        self.label_27.setGeometry(QtCore.QRect(260, 80, 141, 16))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.atenuador_crit_min = QtGui.QLineEdit(self.Tab_Atenuadores)
        self.atenuador_crit_min.setGeometry(QtCore.QRect(400, 80, 113, 26))
        self.atenuador_crit_min.setObjectName(_fromUtf8("atenuador_crit_min"))
        self.line_3 = QtGui.QFrame(self.Tab_Atenuadores)
        self.line_3.setGeometry(QtCore.QRect(0, 110, 741, 16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.label_28 = QtGui.QLabel(self.Tab_Atenuadores)
        self.label_28.setGeometry(QtCore.QRect(0, 130, 741, 16))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.line_4 = QtGui.QFrame(self.Tab_Atenuadores)
        self.line_4.setGeometry(QtCore.QRect(0, 320, 741, 16))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.label_29 = QtGui.QLabel(self.Tab_Atenuadores)
        self.label_29.setGeometry(QtCore.QRect(0, 340, 741, 16))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.att_ch1_resultado = QtGui.QLineEdit(self.Tab_Atenuadores)
        self.att_ch1_resultado.setGeometry(QtCore.QRect(110, 400, 121, 26))
        self.att_ch1_resultado.setObjectName(_fromUtf8("att_ch1_resultado"))
        self.label_30 = QtGui.QLabel(self.Tab_Atenuadores)
        self.label_30.setGeometry(QtCore.QRect(109, 370, 121, 26))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.att_ch2_resultado = QtGui.QLineEdit(self.Tab_Atenuadores)
        self.att_ch2_resultado.setGeometry(QtCore.QRect(260, 400, 121, 26))
        self.att_ch2_resultado.setObjectName(_fromUtf8("att_ch2_resultado"))
        self.label_31 = QtGui.QLabel(self.Tab_Atenuadores)
        self.label_31.setGeometry(QtCore.QRect(259, 370, 121, 26))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.att_ch3_resultado = QtGui.QLineEdit(self.Tab_Atenuadores)
        self.att_ch3_resultado.setGeometry(QtCore.QRect(400, 400, 121, 26))
        self.att_ch3_resultado.setObjectName(_fromUtf8("att_ch3_resultado"))
        self.label_32 = QtGui.QLabel(self.Tab_Atenuadores)
        self.label_32.setGeometry(QtCore.QRect(399, 370, 121, 26))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.att_ch4_resultado = QtGui.QLineEdit(self.Tab_Atenuadores)
        self.att_ch4_resultado.setGeometry(QtCore.QRect(540, 400, 121, 26))
        self.att_ch4_resultado.setObjectName(_fromUtf8("att_ch4_resultado"))
        self.label_33 = QtGui.QLabel(self.Tab_Atenuadores)
        self.label_33.setGeometry(QtCore.QRect(539, 370, 121, 26))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.tableWidget_atenuadores = QtGui.QTableWidget(self.Tab_Atenuadores)
        self.tableWidget_atenuadores.setGeometry(QtCore.QRect(120, 150, 501, 161))
        self.tableWidget_atenuadores.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_atenuadores.setObjectName(_fromUtf8("tableWidget_atenuadores"))
        self.tableWidget_atenuadores.setColumnCount(16)
        self.tableWidget_atenuadores.setRowCount(5)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_atenuadores.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_atenuadores.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_atenuadores.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_atenuadores.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_atenuadores.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_atenuadores.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_atenuadores.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_atenuadores.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_atenuadores.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_atenuadores.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_atenuadores.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_atenuadores.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_atenuadores.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_atenuadores.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_atenuadores.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_atenuadores.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_atenuadores.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_atenuadores.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_atenuadores.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_atenuadores.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_atenuadores.setHorizontalHeaderItem(15, item)
        self.tableWidget_atenuadores.horizontalHeader().setVisible(False)
        self.tabWidget.addTab(self.Tab_Atenuadores, _fromUtf8(""))
        self.Tab_RF_Switches = QtGui.QWidget()
        self.Tab_RF_Switches.setObjectName(_fromUtf8("Tab_RF_Switches"))
        self.label_38 = QtGui.QLabel(self.Tab_RF_Switches)
        self.label_38.setGeometry(QtCore.QRect(0, 20, 741, 20))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.label_39 = QtGui.QLabel(self.Tab_RF_Switches)
        self.label_39.setGeometry(QtCore.QRect(252, 60, 121, 21))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.switch_dc_crit = QtGui.QLineEdit(self.Tab_RF_Switches)
        self.switch_dc_crit.setGeometry(QtCore.QRect(390, 60, 112, 26))
        self.switch_dc_crit.setObjectName(_fromUtf8("switch_dc_crit"))
        self.line_5 = QtGui.QFrame(self.Tab_RF_Switches)
        self.line_5.setGeometry(QtCore.QRect(0, 100, 741, 16))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.label_40 = QtGui.QLabel(self.Tab_RF_Switches)
        self.label_40.setGeometry(QtCore.QRect(0, 120, 741, 16))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.label_41 = QtGui.QLabel(self.Tab_RF_Switches)
        self.label_41.setGeometry(QtCore.QRect(50, 150, 121, 26))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.switch_dc_ch1_medicao = QtGui.QLineEdit(self.Tab_RF_Switches)
        self.switch_dc_ch1_medicao.setGeometry(QtCore.QRect(51, 180, 121, 26))
        self.switch_dc_ch1_medicao.setObjectName(_fromUtf8("switch_dc_ch1_medicao"))
        self.switch_dc_ch2_medicao = QtGui.QLineEdit(self.Tab_RF_Switches)
        self.switch_dc_ch2_medicao.setGeometry(QtCore.QRect(222, 180, 121, 26))
        self.switch_dc_ch2_medicao.setObjectName(_fromUtf8("switch_dc_ch2_medicao"))
        self.label_42 = QtGui.QLabel(self.Tab_RF_Switches)
        self.label_42.setGeometry(QtCore.QRect(221, 150, 121, 26))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.switch_dc_ch3_medicao = QtGui.QLineEdit(self.Tab_RF_Switches)
        self.switch_dc_ch3_medicao.setGeometry(QtCore.QRect(392, 180, 121, 26))
        self.switch_dc_ch3_medicao.setObjectName(_fromUtf8("switch_dc_ch3_medicao"))
        self.label_43 = QtGui.QLabel(self.Tab_RF_Switches)
        self.label_43.setGeometry(QtCore.QRect(391, 150, 121, 26))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.switch_dc_ch4_medicao = QtGui.QLineEdit(self.Tab_RF_Switches)
        self.switch_dc_ch4_medicao.setGeometry(QtCore.QRect(561, 180, 121, 26))
        self.switch_dc_ch4_medicao.setObjectName(_fromUtf8("switch_dc_ch4_medicao"))
        self.label_44 = QtGui.QLabel(self.Tab_RF_Switches)
        self.label_44.setGeometry(QtCore.QRect(560, 150, 121, 26))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.switch_dc_ch3_resultado = QtGui.QLineEdit(self.Tab_RF_Switches)
        self.switch_dc_ch3_resultado.setGeometry(QtCore.QRect(391, 310, 121, 26))
        self.switch_dc_ch3_resultado.setObjectName(_fromUtf8("switch_dc_ch3_resultado"))
        self.label_45 = QtGui.QLabel(self.Tab_RF_Switches)
        self.label_45.setGeometry(QtCore.QRect(559, 280, 121, 26))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.switch_dc_ch4_resultado = QtGui.QLineEdit(self.Tab_RF_Switches)
        self.switch_dc_ch4_resultado.setGeometry(QtCore.QRect(560, 310, 121, 26))
        self.switch_dc_ch4_resultado.setObjectName(_fromUtf8("switch_dc_ch4_resultado"))
        self.label_46 = QtGui.QLabel(self.Tab_RF_Switches)
        self.label_46.setGeometry(QtCore.QRect(-1, 250, 741, 16))
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.switch_dc_ch1_resultado = QtGui.QLineEdit(self.Tab_RF_Switches)
        self.switch_dc_ch1_resultado.setGeometry(QtCore.QRect(50, 310, 121, 26))
        self.switch_dc_ch1_resultado.setObjectName(_fromUtf8("switch_dc_ch1_resultado"))
        self.label_47 = QtGui.QLabel(self.Tab_RF_Switches)
        self.label_47.setGeometry(QtCore.QRect(49, 280, 121, 26))
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.line_6 = QtGui.QFrame(self.Tab_RF_Switches)
        self.line_6.setGeometry(QtCore.QRect(-1, 230, 741, 16))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.label_48 = QtGui.QLabel(self.Tab_RF_Switches)
        self.label_48.setGeometry(QtCore.QRect(390, 280, 121, 26))
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.switch_dc_ch2_resultado = QtGui.QLineEdit(self.Tab_RF_Switches)
        self.switch_dc_ch2_resultado.setGeometry(QtCore.QRect(221, 310, 121, 26))
        self.switch_dc_ch2_resultado.setObjectName(_fromUtf8("switch_dc_ch2_resultado"))
        self.label_49 = QtGui.QLabel(self.Tab_RF_Switches)
        self.label_49.setGeometry(QtCore.QRect(220, 280, 121, 26))
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.tabWidget.addTab(self.Tab_RF_Switches, _fromUtf8(""))
        self.Tab_Linearidade = QtGui.QWidget()
        self.Tab_Linearidade.setObjectName(_fromUtf8("Tab_Linearidade"))
        self.line_7 = QtGui.QFrame(self.Tab_Linearidade)
        self.line_7.setGeometry(QtCore.QRect(0, 110, 741, 16))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.label_51 = QtGui.QLabel(self.Tab_Linearidade)
        self.label_51.setGeometry(QtCore.QRect(260, 60, 111, 21))
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.label_52 = QtGui.QLabel(self.Tab_Linearidade)
        self.label_52.setGeometry(QtCore.QRect(0, 20, 741, 20))
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.linearidade_crit = QtGui.QLineEdit(self.Tab_Linearidade)
        self.linearidade_crit.setGeometry(QtCore.QRect(388, 60, 112, 26))
        self.linearidade_crit.setObjectName(_fromUtf8("linearidade_crit"))
        self.label_54 = QtGui.QLabel(self.Tab_Linearidade)
        self.label_54.setGeometry(QtCore.QRect(0, 130, 741, 16))
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.label_60 = QtGui.QLabel(self.Tab_Linearidade)
        self.label_60.setGeometry(QtCore.QRect(0, 340, 741, 16))
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.linearidade_ch2_resultado = QtGui.QLineEdit(self.Tab_Linearidade)
        self.linearidade_ch2_resultado.setGeometry(QtCore.QRect(260, 400, 121, 26))
        self.linearidade_ch2_resultado.setObjectName(_fromUtf8("linearidade_ch2_resultado"))
        self.linearidade_ch1_resultado = QtGui.QLineEdit(self.Tab_Linearidade)
        self.linearidade_ch1_resultado.setGeometry(QtCore.QRect(110, 400, 121, 26))
        self.linearidade_ch1_resultado.setObjectName(_fromUtf8("linearidade_ch1_resultado"))
        self.linearidade_ch4_resultado = QtGui.QLineEdit(self.Tab_Linearidade)
        self.linearidade_ch4_resultado.setGeometry(QtCore.QRect(540, 400, 121, 26))
        self.linearidade_ch4_resultado.setObjectName(_fromUtf8("linearidade_ch4_resultado"))
        self.line_8 = QtGui.QFrame(self.Tab_Linearidade)
        self.line_8.setGeometry(QtCore.QRect(0, 320, 741, 16))
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.linearidade_ch3_resultado = QtGui.QLineEdit(self.Tab_Linearidade)
        self.linearidade_ch3_resultado.setGeometry(QtCore.QRect(400, 400, 121, 26))
        self.linearidade_ch3_resultado.setObjectName(_fromUtf8("linearidade_ch3_resultado"))
        self.label_61 = QtGui.QLabel(self.Tab_Linearidade)
        self.label_61.setGeometry(QtCore.QRect(260, 370, 121, 26))
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.label_62 = QtGui.QLabel(self.Tab_Linearidade)
        self.label_62.setGeometry(QtCore.QRect(540, 370, 121, 26))
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.label_63 = QtGui.QLabel(self.Tab_Linearidade)
        self.label_63.setGeometry(QtCore.QRect(110, 370, 121, 26))
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.label_64 = QtGui.QLabel(self.Tab_Linearidade)
        self.label_64.setGeometry(QtCore.QRect(400, 370, 121, 26))
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.tableWidget_linearidade = QtGui.QTableWidget(self.Tab_Linearidade)
        self.tableWidget_linearidade.setGeometry(QtCore.QRect(120, 160, 501, 161))
        self.tableWidget_linearidade.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_linearidade.setObjectName(_fromUtf8("tableWidget_linearidade"))
        self.tableWidget_linearidade.setColumnCount(16)
        self.tableWidget_linearidade.setRowCount(5)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_linearidade.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_linearidade.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_linearidade.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_linearidade.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_linearidade.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_linearidade.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_linearidade.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_linearidade.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_linearidade.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_linearidade.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_linearidade.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_linearidade.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_linearidade.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_linearidade.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_linearidade.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_linearidade.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_linearidade.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_linearidade.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_linearidade.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_linearidade.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_linearidade.setHorizontalHeaderItem(15, item)
        self.tableWidget_linearidade.horizontalHeader().setVisible(False)
        self.tabWidget.addTab(self.Tab_Linearidade, _fromUtf8(""))
        self.Tab_Crosstalk = QtGui.QWidget()
        self.Tab_Crosstalk.setObjectName(_fromUtf8("Tab_Crosstalk"))
        self.label_50 = QtGui.QLabel(self.Tab_Crosstalk)
        self.label_50.setGeometry(QtCore.QRect(253, 60, 121, 21))
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.label_65 = QtGui.QLabel(self.Tab_Crosstalk)
        self.label_65.setGeometry(QtCore.QRect(51, 150, 121, 26))
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.label_66 = QtGui.QLabel(self.Tab_Crosstalk)
        self.label_66.setGeometry(QtCore.QRect(1, 20, 741, 20))
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.label_67 = QtGui.QLabel(self.Tab_Crosstalk)
        self.label_67.setGeometry(QtCore.QRect(221, 280, 121, 26))
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.label_68 = QtGui.QLabel(self.Tab_Crosstalk)
        self.label_68.setGeometry(QtCore.QRect(1, 120, 741, 16))
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.label_69 = QtGui.QLabel(self.Tab_Crosstalk)
        self.label_69.setGeometry(QtCore.QRect(50, 280, 121, 26))
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.crosstalk_ch4_resultado = QtGui.QLineEdit(self.Tab_Crosstalk)
        self.crosstalk_ch4_resultado.setGeometry(QtCore.QRect(561, 310, 121, 26))
        self.crosstalk_ch4_resultado.setObjectName(_fromUtf8("crosstalk_ch4_resultado"))
        self.crosstalk_ch3_medicao = QtGui.QLineEdit(self.Tab_Crosstalk)
        self.crosstalk_ch3_medicao.setGeometry(QtCore.QRect(393, 180, 121, 26))
        self.crosstalk_ch3_medicao.setObjectName(_fromUtf8("crosstalk_ch3_medicao"))
        self.label_70 = QtGui.QLabel(self.Tab_Crosstalk)
        self.label_70.setGeometry(QtCore.QRect(222, 150, 121, 26))
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.crosstalk_ch1_medicao = QtGui.QLineEdit(self.Tab_Crosstalk)
        self.crosstalk_ch1_medicao.setGeometry(QtCore.QRect(52, 180, 121, 26))
        self.crosstalk_ch1_medicao.setObjectName(_fromUtf8("crosstalk_ch1_medicao"))
        self.label_71 = QtGui.QLabel(self.Tab_Crosstalk)
        self.label_71.setGeometry(QtCore.QRect(391, 280, 121, 26))
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.crosstalk_ch2_resultado = QtGui.QLineEdit(self.Tab_Crosstalk)
        self.crosstalk_ch2_resultado.setGeometry(QtCore.QRect(222, 310, 121, 26))
        self.crosstalk_ch2_resultado.setObjectName(_fromUtf8("crosstalk_ch2_resultado"))
        self.crosstalk_ch4_medicao = QtGui.QLineEdit(self.Tab_Crosstalk)
        self.crosstalk_ch4_medicao.setGeometry(QtCore.QRect(562, 180, 121, 26))
        self.crosstalk_ch4_medicao.setObjectName(_fromUtf8("crosstalk_ch4_medicao"))
        self.label_72 = QtGui.QLabel(self.Tab_Crosstalk)
        self.label_72.setGeometry(QtCore.QRect(392, 150, 121, 26))
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.crosstalk_crit = QtGui.QLineEdit(self.Tab_Crosstalk)
        self.crosstalk_crit.setGeometry(QtCore.QRect(391, 60, 112, 26))
        self.crosstalk_crit.setObjectName(_fromUtf8("crosstalk_crit"))
        self.label_73 = QtGui.QLabel(self.Tab_Crosstalk)
        self.label_73.setGeometry(QtCore.QRect(560, 280, 121, 26))
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.label_74 = QtGui.QLabel(self.Tab_Crosstalk)
        self.label_74.setGeometry(QtCore.QRect(561, 150, 121, 26))
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.crosstalk_ch3_resultado = QtGui.QLineEdit(self.Tab_Crosstalk)
        self.crosstalk_ch3_resultado.setGeometry(QtCore.QRect(392, 310, 121, 26))
        self.crosstalk_ch3_resultado.setObjectName(_fromUtf8("crosstalk_ch3_resultado"))
        self.crosstalk_ch2_medicao = QtGui.QLineEdit(self.Tab_Crosstalk)
        self.crosstalk_ch2_medicao.setGeometry(QtCore.QRect(223, 180, 121, 26))
        self.crosstalk_ch2_medicao.setObjectName(_fromUtf8("crosstalk_ch2_medicao"))
        self.crosstalk_ch1_resultado = QtGui.QLineEdit(self.Tab_Crosstalk)
        self.crosstalk_ch1_resultado.setGeometry(QtCore.QRect(51, 310, 121, 26))
        self.crosstalk_ch1_resultado.setObjectName(_fromUtf8("crosstalk_ch1_resultado"))
        self.label_75 = QtGui.QLabel(self.Tab_Crosstalk)
        self.label_75.setGeometry(QtCore.QRect(0, 250, 731, 16))
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.line_9 = QtGui.QFrame(self.Tab_Crosstalk)
        self.line_9.setGeometry(QtCore.QRect(-1, 230, 741, 16))
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.line_10 = QtGui.QFrame(self.Tab_Crosstalk)
        self.line_10.setGeometry(QtCore.QRect(0, 100, 741, 16))
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.tabWidget.addTab(self.Tab_Crosstalk, _fromUtf8(""))
        self.Tab_Freq_Resp = QtGui.QWidget()
        self.Tab_Freq_Resp.setObjectName(_fromUtf8("Tab_Freq_Resp"))
        self.freq_resp_crit_min = QtGui.QLineEdit(self.Tab_Freq_Resp)
        self.freq_resp_crit_min.setGeometry(QtCore.QRect(520, 60, 112, 26))
        self.freq_resp_crit_min.setObjectName(_fromUtf8("freq_resp_crit_min"))
        self.label_81 = QtGui.QLabel(self.Tab_Freq_Resp)
        self.label_81.setGeometry(QtCore.QRect(-2, 20, 741, 20))
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.label_82 = QtGui.QLabel(self.Tab_Freq_Resp)
        self.label_82.setGeometry(QtCore.QRect(0, 60, 461, 21))
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.label_83 = QtGui.QLabel(self.Tab_Freq_Resp)
        self.label_83.setGeometry(QtCore.QRect(20, 90, 501, 31))
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.freq_resp_crit_dif = QtGui.QLineEdit(self.Tab_Freq_Resp)
        self.freq_resp_crit_dif.setGeometry(QtCore.QRect(520, 90, 112, 26))
        self.freq_resp_crit_dif.setObjectName(_fromUtf8("freq_resp_crit_dif"))
        self.line_13 = QtGui.QFrame(self.Tab_Freq_Resp)
        self.line_13.setGeometry(QtCore.QRect(0, 130, 741, 16))
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.label_84 = QtGui.QLabel(self.Tab_Freq_Resp)
        self.label_84.setGeometry(QtCore.QRect(450, 189, 121, 16))
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.label_9 = QtGui.QLabel(self.Tab_Freq_Resp)
        self.label_9.setGeometry(QtCore.QRect(200, 189, 121, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_14 = QtGui.QLabel(self.Tab_Freq_Resp)
        self.label_14.setGeometry(QtCore.QRect(320, 189, 121, 20))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_89 = QtGui.QLabel(self.Tab_Freq_Resp)
        self.label_89.setGeometry(QtCore.QRect(0, 150, 741, 16))
        self.label_89.setObjectName(_fromUtf8("label_89"))
        self.freq_amp_max_3 = QtGui.QLineEdit(self.Tab_Freq_Resp)
        self.freq_amp_max_3.setGeometry(QtCore.QRect(449, 263, 129, 21))
        self.freq_amp_max_3.setObjectName(_fromUtf8("freq_amp_max_3"))
        self.freq_freq_max_3 = QtGui.QLineEdit(self.Tab_Freq_Resp)
        self.freq_freq_max_3.setGeometry(QtCore.QRect(320, 263, 129, 21))
        self.freq_freq_max_3.setObjectName(_fromUtf8("freq_freq_max_3"))
        self.label_85 = QtGui.QLabel(self.Tab_Freq_Resp)
        self.label_85.setGeometry(QtCore.QRect(139, 264, 46, 21))
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.freq_dif_max_4 = QtGui.QLineEdit(self.Tab_Freq_Resp)
        self.freq_dif_max_4.setGeometry(QtCore.QRect(191, 290, 129, 21))
        self.freq_dif_max_4.setObjectName(_fromUtf8("freq_dif_max_4"))
        self.freq_freq_max_2 = QtGui.QLineEdit(self.Tab_Freq_Resp)
        self.freq_freq_max_2.setGeometry(QtCore.QRect(320, 236, 129, 21))
        self.freq_freq_max_2.setObjectName(_fromUtf8("freq_freq_max_2"))
        self.freq_amp_max_4 = QtGui.QLineEdit(self.Tab_Freq_Resp)
        self.freq_amp_max_4.setGeometry(QtCore.QRect(449, 290, 129, 21))
        self.freq_amp_max_4.setObjectName(_fromUtf8("freq_amp_max_4"))
        self.freq_dif_max_2 = QtGui.QLineEdit(self.Tab_Freq_Resp)
        self.freq_dif_max_2.setGeometry(QtCore.QRect(191, 236, 129, 21))
        self.freq_dif_max_2.setObjectName(_fromUtf8("freq_dif_max_2"))
        self.freq_freq_max_1 = QtGui.QLineEdit(self.Tab_Freq_Resp)
        self.freq_freq_max_1.setGeometry(QtCore.QRect(320, 209, 129, 21))
        self.freq_freq_max_1.setObjectName(_fromUtf8("freq_freq_max_1"))
        self.freq_amp_max_1 = QtGui.QLineEdit(self.Tab_Freq_Resp)
        self.freq_amp_max_1.setGeometry(QtCore.QRect(449, 209, 129, 21))
        self.freq_amp_max_1.setObjectName(_fromUtf8("freq_amp_max_1"))
        self.label_86 = QtGui.QLabel(self.Tab_Freq_Resp)
        self.label_86.setGeometry(QtCore.QRect(139, 289, 46, 21))
        self.label_86.setObjectName(_fromUtf8("label_86"))
        self.label_87 = QtGui.QLabel(self.Tab_Freq_Resp)
        self.label_87.setGeometry(QtCore.QRect(139, 235, 46, 20))
        self.label_87.setObjectName(_fromUtf8("label_87"))
        self.freq_dif_max_1 = QtGui.QLineEdit(self.Tab_Freq_Resp)
        self.freq_dif_max_1.setGeometry(QtCore.QRect(191, 209, 129, 21))
        self.freq_dif_max_1.setObjectName(_fromUtf8("freq_dif_max_1"))
        self.freq_dif_max_3 = QtGui.QLineEdit(self.Tab_Freq_Resp)
        self.freq_dif_max_3.setGeometry(QtCore.QRect(191, 263, 129, 21))
        self.freq_dif_max_3.setObjectName(_fromUtf8("freq_dif_max_3"))
        self.label_88 = QtGui.QLabel(self.Tab_Freq_Resp)
        self.label_88.setGeometry(QtCore.QRect(139, 209, 46, 16))
        self.label_88.setObjectName(_fromUtf8("label_88"))
        self.freq_amp_max_2 = QtGui.QLineEdit(self.Tab_Freq_Resp)
        self.freq_amp_max_2.setGeometry(QtCore.QRect(449, 236, 129, 21))
        self.freq_amp_max_2.setObjectName(_fromUtf8("freq_amp_max_2"))
        self.freq_freq_max_4 = QtGui.QLineEdit(self.Tab_Freq_Resp)
        self.freq_freq_max_4.setGeometry(QtCore.QRect(320, 290, 129, 21))
        self.freq_freq_max_4.setObjectName(_fromUtf8("freq_freq_max_4"))
        self.line_14 = QtGui.QFrame(self.Tab_Freq_Resp)
        self.line_14.setGeometry(QtCore.QRect(0, 320, 741, 16))
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.label_90 = QtGui.QLabel(self.Tab_Freq_Resp)
        self.label_90.setGeometry(QtCore.QRect(540, 370, 121, 26))
        self.label_90.setObjectName(_fromUtf8("label_90"))
        self.label_91 = QtGui.QLabel(self.Tab_Freq_Resp)
        self.label_91.setGeometry(QtCore.QRect(110, 370, 121, 26))
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.label_92 = QtGui.QLabel(self.Tab_Freq_Resp)
        self.label_92.setGeometry(QtCore.QRect(400, 370, 121, 26))
        self.label_92.setObjectName(_fromUtf8("label_92"))
        self.freq_resp_ch4_resultado = QtGui.QLineEdit(self.Tab_Freq_Resp)
        self.freq_resp_ch4_resultado.setGeometry(QtCore.QRect(540, 400, 121, 26))
        self.freq_resp_ch4_resultado.setObjectName(_fromUtf8("freq_resp_ch4_resultado"))
        self.label_93 = QtGui.QLabel(self.Tab_Freq_Resp)
        self.label_93.setGeometry(QtCore.QRect(0, 340, 741, 16))
        self.label_93.setObjectName(_fromUtf8("label_93"))
        self.freq_resp_ch1_resultado = QtGui.QLineEdit(self.Tab_Freq_Resp)
        self.freq_resp_ch1_resultado.setGeometry(QtCore.QRect(110, 400, 121, 26))
        self.freq_resp_ch1_resultado.setObjectName(_fromUtf8("freq_resp_ch1_resultado"))
        self.label_94 = QtGui.QLabel(self.Tab_Freq_Resp)
        self.label_94.setGeometry(QtCore.QRect(260, 370, 121, 26))
        self.label_94.setObjectName(_fromUtf8("label_94"))
        self.freq_resp_ch2_resultado = QtGui.QLineEdit(self.Tab_Freq_Resp)
        self.freq_resp_ch2_resultado.setGeometry(QtCore.QRect(260, 400, 121, 26))
        self.freq_resp_ch2_resultado.setObjectName(_fromUtf8("freq_resp_ch2_resultado"))
        self.freq_resp_ch3_resultado = QtGui.QLineEdit(self.Tab_Freq_Resp)
        self.freq_resp_ch3_resultado.setGeometry(QtCore.QRect(400, 400, 121, 26))
        self.freq_resp_ch3_resultado.setObjectName(_fromUtf8("freq_resp_ch3_resultado"))
        self.tabWidget.addTab(self.Tab_Freq_Resp, _fromUtf8(""))
        self.Tab_Return_Loss = QtGui.QWidget()
        self.Tab_Return_Loss.setObjectName(_fromUtf8("Tab_Return_Loss"))
        self.ret_loss_s22_crit = QtGui.QLineEdit(self.Tab_Return_Loss)
        self.ret_loss_s22_crit.setGeometry(QtCore.QRect(400, 90, 113, 26))
        self.ret_loss_s22_crit.setObjectName(_fromUtf8("ret_loss_s22_crit"))
        self.label_95 = QtGui.QLabel(self.Tab_Return_Loss)
        self.label_95.setGeometry(QtCore.QRect(230, 59, 171, 31))
        self.label_95.setObjectName(_fromUtf8("label_95"))
        self.label_96 = QtGui.QLabel(self.Tab_Return_Loss)
        self.label_96.setGeometry(QtCore.QRect(230, 89, 171, 31))
        self.label_96.setObjectName(_fromUtf8("label_96"))
        self.label_97 = QtGui.QLabel(self.Tab_Return_Loss)
        self.label_97.setGeometry(QtCore.QRect(0, 20, 741, 20))
        self.label_97.setObjectName(_fromUtf8("label_97"))
        self.ret_loss_s11_crit = QtGui.QLineEdit(self.Tab_Return_Loss)
        self.ret_loss_s11_crit.setGeometry(QtCore.QRect(400, 60, 113, 26))
        self.ret_loss_s11_crit.setObjectName(_fromUtf8("ret_loss_s11_crit"))
        self.line_15 = QtGui.QFrame(self.Tab_Return_Loss)
        self.line_15.setGeometry(QtCore.QRect(0, 130, 741, 16))
        self.line_15.setFrameShape(QtGui.QFrame.HLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName(_fromUtf8("line_15"))
        self.label_98 = QtGui.QLabel(self.Tab_Return_Loss)
        self.label_98.setGeometry(QtCore.QRect(120, 200, 121, 26))
        self.label_98.setObjectName(_fromUtf8("label_98"))
        self.ret_loss_s11_ch3_medicao = QtGui.QLineEdit(self.Tab_Return_Loss)
        self.ret_loss_s11_ch3_medicao.setGeometry(QtCore.QRect(378, 220, 129, 23))
        self.ret_loss_s11_ch3_medicao.setObjectName(_fromUtf8("ret_loss_s11_ch3_medicao"))
        self.ret_loss_s11_ch4_medicao = QtGui.QLineEdit(self.Tab_Return_Loss)
        self.ret_loss_s11_ch4_medicao.setGeometry(QtCore.QRect(509, 220, 129, 23))
        self.ret_loss_s11_ch4_medicao.setObjectName(_fromUtf8("ret_loss_s11_ch4_medicao"))
        self.ret_loss_s11_ch1_medicao = QtGui.QLineEdit(self.Tab_Return_Loss)
        self.ret_loss_s11_ch1_medicao.setGeometry(QtCore.QRect(119, 220, 129, 23))
        self.ret_loss_s11_ch1_medicao.setObjectName(_fromUtf8("ret_loss_s11_ch1_medicao"))
        self.ret_loss_s11_ch2_medicao = QtGui.QLineEdit(self.Tab_Return_Loss)
        self.ret_loss_s11_ch2_medicao.setGeometry(QtCore.QRect(250, 220, 129, 23))
        self.ret_loss_s11_ch2_medicao.setObjectName(_fromUtf8("ret_loss_s11_ch2_medicao"))
        self.label_99 = QtGui.QLabel(self.Tab_Return_Loss)
        self.label_99.setGeometry(QtCore.QRect(379, 200, 121, 26))
        self.label_99.setObjectName(_fromUtf8("label_99"))
        self.label_100 = QtGui.QLabel(self.Tab_Return_Loss)
        self.label_100.setGeometry(QtCore.QRect(0, 160, 741, 16))
        self.label_100.setObjectName(_fromUtf8("label_100"))
        self.label_101 = QtGui.QLabel(self.Tab_Return_Loss)
        self.label_101.setGeometry(QtCore.QRect(251, 200, 121, 26))
        self.label_101.setObjectName(_fromUtf8("label_101"))
        self.label_102 = QtGui.QLabel(self.Tab_Return_Loss)
        self.label_102.setGeometry(QtCore.QRect(510, 200, 121, 26))
        self.label_102.setObjectName(_fromUtf8("label_102"))
        self.ret_loss_s22_ch3_medicao = QtGui.QLineEdit(self.Tab_Return_Loss)
        self.ret_loss_s22_ch3_medicao.setGeometry(QtCore.QRect(378, 249, 129, 23))
        self.ret_loss_s22_ch3_medicao.setObjectName(_fromUtf8("ret_loss_s22_ch3_medicao"))
        self.ret_loss_s22_ch4_medicao = QtGui.QLineEdit(self.Tab_Return_Loss)
        self.ret_loss_s22_ch4_medicao.setGeometry(QtCore.QRect(509, 249, 129, 23))
        self.ret_loss_s22_ch4_medicao.setObjectName(_fromUtf8("ret_loss_s22_ch4_medicao"))
        self.ret_loss_s22_ch1_medicao = QtGui.QLineEdit(self.Tab_Return_Loss)
        self.ret_loss_s22_ch1_medicao.setGeometry(QtCore.QRect(119, 249, 129, 23))
        self.ret_loss_s22_ch1_medicao.setObjectName(_fromUtf8("ret_loss_s22_ch1_medicao"))
        self.ret_loss_s22_ch2_medicao = QtGui.QLineEdit(self.Tab_Return_Loss)
        self.ret_loss_s22_ch2_medicao.setGeometry(QtCore.QRect(250, 249, 129, 23))
        self.ret_loss_s22_ch2_medicao.setObjectName(_fromUtf8("ret_loss_s22_ch2_medicao"))
        self.label_103 = QtGui.QLabel(self.Tab_Return_Loss)
        self.label_103.setGeometry(QtCore.QRect(70, 220, 51, 21))
        self.label_103.setObjectName(_fromUtf8("label_103"))
        self.label_104 = QtGui.QLabel(self.Tab_Return_Loss)
        self.label_104.setGeometry(QtCore.QRect(70, 250, 51, 21))
        self.label_104.setObjectName(_fromUtf8("label_104"))
        self.line_16 = QtGui.QFrame(self.Tab_Return_Loss)
        self.line_16.setGeometry(QtCore.QRect(0, 280, 741, 16))
        self.line_16.setFrameShape(QtGui.QFrame.HLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName(_fromUtf8("line_16"))
        self.label_105 = QtGui.QLabel(self.Tab_Return_Loss)
        self.label_105.setGeometry(QtCore.QRect(0, 310, 741, 16))
        self.label_105.setObjectName(_fromUtf8("label_105"))
        self.ret_loss_s22_ch2_resultado = QtGui.QLineEdit(self.Tab_Return_Loss)
        self.ret_loss_s22_ch2_resultado.setGeometry(QtCore.QRect(251, 400, 129, 23))
        self.ret_loss_s22_ch2_resultado.setObjectName(_fromUtf8("ret_loss_s22_ch2_resultado"))
        self.ret_loss_s11_ch3_resultado = QtGui.QLineEdit(self.Tab_Return_Loss)
        self.ret_loss_s11_ch3_resultado.setGeometry(QtCore.QRect(379, 371, 129, 23))
        self.ret_loss_s11_ch3_resultado.setObjectName(_fromUtf8("ret_loss_s11_ch3_resultado"))
        self.label_106 = QtGui.QLabel(self.Tab_Return_Loss)
        self.label_106.setGeometry(QtCore.QRect(511, 351, 121, 26))
        self.label_106.setObjectName(_fromUtf8("label_106"))
        self.label_107 = QtGui.QLabel(self.Tab_Return_Loss)
        self.label_107.setGeometry(QtCore.QRect(252, 351, 121, 26))
        self.label_107.setObjectName(_fromUtf8("label_107"))
        self.ret_loss_s11_ch4_resultado = QtGui.QLineEdit(self.Tab_Return_Loss)
        self.ret_loss_s11_ch4_resultado.setGeometry(QtCore.QRect(510, 371, 129, 23))
        self.ret_loss_s11_ch4_resultado.setObjectName(_fromUtf8("ret_loss_s11_ch4_resultado"))
        self.label_108 = QtGui.QLabel(self.Tab_Return_Loss)
        self.label_108.setGeometry(QtCore.QRect(71, 401, 51, 21))
        self.label_108.setObjectName(_fromUtf8("label_108"))
        self.label_109 = QtGui.QLabel(self.Tab_Return_Loss)
        self.label_109.setGeometry(QtCore.QRect(121, 351, 121, 26))
        self.label_109.setObjectName(_fromUtf8("label_109"))
        self.ret_loss_s22_ch4_resultado = QtGui.QLineEdit(self.Tab_Return_Loss)
        self.ret_loss_s22_ch4_resultado.setGeometry(QtCore.QRect(510, 400, 129, 23))
        self.ret_loss_s22_ch4_resultado.setObjectName(_fromUtf8("ret_loss_s22_ch4_resultado"))
        self.label_110 = QtGui.QLabel(self.Tab_Return_Loss)
        self.label_110.setGeometry(QtCore.QRect(71, 371, 51, 21))
        self.label_110.setObjectName(_fromUtf8("label_110"))
        self.ret_loss_s11_ch1_resultado = QtGui.QLineEdit(self.Tab_Return_Loss)
        self.ret_loss_s11_ch1_resultado.setGeometry(QtCore.QRect(120, 371, 129, 23))
        self.ret_loss_s11_ch1_resultado.setObjectName(_fromUtf8("ret_loss_s11_ch1_resultado"))
        self.ret_loss_s22_ch3_resultado = QtGui.QLineEdit(self.Tab_Return_Loss)
        self.ret_loss_s22_ch3_resultado.setGeometry(QtCore.QRect(379, 400, 129, 23))
        self.ret_loss_s22_ch3_resultado.setObjectName(_fromUtf8("ret_loss_s22_ch3_resultado"))
        self.label_111 = QtGui.QLabel(self.Tab_Return_Loss)
        self.label_111.setGeometry(QtCore.QRect(380, 351, 121, 26))
        self.label_111.setObjectName(_fromUtf8("label_111"))
        self.ret_loss_s11_ch2_resultado = QtGui.QLineEdit(self.Tab_Return_Loss)
        self.ret_loss_s11_ch2_resultado.setGeometry(QtCore.QRect(251, 371, 129, 23))
        self.ret_loss_s11_ch2_resultado.setObjectName(_fromUtf8("ret_loss_s11_ch2_resultado"))
        self.ret_loss_s22_ch1_resultado = QtGui.QLineEdit(self.Tab_Return_Loss)
        self.ret_loss_s22_ch1_resultado.setGeometry(QtCore.QRect(120, 400, 129, 23))
        self.ret_loss_s22_ch1_resultado.setObjectName(_fromUtf8("ret_loss_s22_ch1_resultado"))
        self.tabWidget.addTab(self.Tab_Return_Loss, _fromUtf8(""))
        self.Tab_Temperatura = QtGui.QWidget()
        self.Tab_Temperatura.setObjectName(_fromUtf8("Tab_Temperatura"))
        self.label_76 = QtGui.QLabel(self.Tab_Temperatura)
        self.label_76.setGeometry(QtCore.QRect(0, 20, 741, 20))
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.temp_crit_max = QtGui.QLineEdit(self.Tab_Temperatura)
        self.temp_crit_max.setGeometry(QtCore.QRect(400, 50, 113, 26))
        self.temp_crit_max.setObjectName(_fromUtf8("temp_crit_max"))
        self.temp_crit_min = QtGui.QLineEdit(self.Tab_Temperatura)
        self.temp_crit_min.setGeometry(QtCore.QRect(400, 80, 113, 26))
        self.temp_crit_min.setObjectName(_fromUtf8("temp_crit_min"))
        self.line_11 = QtGui.QFrame(self.Tab_Temperatura)
        self.line_11.setGeometry(QtCore.QRect(0, 110, 741, 16))
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.label_77 = QtGui.QLabel(self.Tab_Temperatura)
        self.label_77.setGeometry(QtCore.QRect(260, 60, 141, 16))
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.label_78 = QtGui.QLabel(self.Tab_Temperatura)
        self.label_78.setGeometry(QtCore.QRect(260, 80, 141, 16))
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.label_79 = QtGui.QLabel(self.Tab_Temperatura)
        self.label_79.setGeometry(QtCore.QRect(0, 130, 741, 16))
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.label_80 = QtGui.QLabel(self.Tab_Temperatura)
        self.label_80.setGeometry(QtCore.QRect(0, 290, 741, 16))
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.temp_resultado = QtGui.QLineEdit(self.Tab_Temperatura)
        self.temp_resultado.setGeometry(QtCore.QRect(320, 330, 121, 26))
        self.temp_resultado.setObjectName(_fromUtf8("temp_resultado"))
        self.line_12 = QtGui.QFrame(self.Tab_Temperatura)
        self.line_12.setGeometry(QtCore.QRect(0, 250, 741, 16))
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.TEMP_VAL_1 = QtGui.QLineEdit(self.Tab_Temperatura)
        self.TEMP_VAL_1.setGeometry(QtCore.QRect(130, 190, 71, 26))
        self.TEMP_VAL_1.setObjectName(_fromUtf8("TEMP_VAL_1"))
        self.label_112 = QtGui.QLabel(self.Tab_Temperatura)
        self.label_112.setGeometry(QtCore.QRect(120, 170, 81, 16))
        self.label_112.setObjectName(_fromUtf8("label_112"))
        self.label_113 = QtGui.QLabel(self.Tab_Temperatura)
        self.label_113.setGeometry(QtCore.QRect(220, 170, 81, 16))
        self.label_113.setObjectName(_fromUtf8("label_113"))
        self.label_114 = QtGui.QLabel(self.Tab_Temperatura)
        self.label_114.setGeometry(QtCore.QRect(320, 170, 81, 16))
        self.label_114.setObjectName(_fromUtf8("label_114"))
        self.label_115 = QtGui.QLabel(self.Tab_Temperatura)
        self.label_115.setGeometry(QtCore.QRect(420, 170, 81, 16))
        self.label_115.setObjectName(_fromUtf8("label_115"))
        self.label_116 = QtGui.QLabel(self.Tab_Temperatura)
        self.label_116.setGeometry(QtCore.QRect(520, 170, 81, 16))
        self.label_116.setObjectName(_fromUtf8("label_116"))
        self.TEMP_VAL_2 = QtGui.QLineEdit(self.Tab_Temperatura)
        self.TEMP_VAL_2.setGeometry(QtCore.QRect(230, 190, 71, 26))
        self.TEMP_VAL_2.setObjectName(_fromUtf8("TEMP_VAL_2"))
        self.TEMP_VAL_3 = QtGui.QLineEdit(self.Tab_Temperatura)
        self.TEMP_VAL_3.setGeometry(QtCore.QRect(330, 190, 71, 26))
        self.TEMP_VAL_3.setObjectName(_fromUtf8("TEMP_VAL_3"))
        self.TEMP_VAL_4 = QtGui.QLineEdit(self.Tab_Temperatura)
        self.TEMP_VAL_4.setGeometry(QtCore.QRect(430, 190, 71, 26))
        self.TEMP_VAL_4.setObjectName(_fromUtf8("TEMP_VAL_4"))
        self.TEMP_VAL_5 = QtGui.QLineEdit(self.Tab_Temperatura)
        self.TEMP_VAL_5.setGeometry(QtCore.QRect(530, 190, 71, 26))
        self.TEMP_VAL_5.setObjectName(_fromUtf8("TEMP_VAL_5"))
        self.tabWidget.addTab(self.Tab_Temperatura, _fromUtf8(""))
        self.OK_BUTTON = QtGui.QPushButton(Dialog)
        self.OK_BUTTON.setGeometry(QtCore.QRect(670, 570, 87, 27))
        self.OK_BUTTON.setObjectName(_fromUtf8("OK_BUTTON"))
        self.dateTimeEdit_result = QtGui.QDateTimeEdit(Dialog)
        self.dateTimeEdit_result.setGeometry(QtCore.QRect(310, 15, 194, 26))
        self.dateTimeEdit_result.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit_result.setObjectName(_fromUtf8("dateTimeEdit_result"))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label_25.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Valor Máximo [dB]:</p></body></html>", None))
        self.label_26.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Critério de Avaliação</span></p></body></html>", None))
        self.atenuador_crit_max.setText(_translate("Dialog", "5,2", None))
        self.label_27.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Valor Mínimo [dB]:</p></body></html>", None))
        self.atenuador_crit_min.setText(_translate("Dialog", "4.8", None))
        self.label_28.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Valores Medidos [dB]</span></p></body></html>", None))
        self.label_29.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Resultado Final</span></p></body></html>", None))
        self.label_30.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 1</p></body></html>", None))
        self.label_31.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 2</p></body></html>", None))
        self.label_32.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 3</p></body></html>", None))
        self.label_33.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 4</p></body></html>", None))
        item = self.tableWidget_atenuadores.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "Medição", None))
        item = self.tableWidget_atenuadores.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "Canal 1", None))
        item = self.tableWidget_atenuadores.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "Canal 2", None))
        item = self.tableWidget_atenuadores.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "Canal 3", None))
        item = self.tableWidget_atenuadores.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "Canal 4", None))
        item = self.tableWidget_atenuadores.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "New Column", None))
        item = self.tableWidget_atenuadores.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "New Column", None))
        item = self.tableWidget_atenuadores.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "New Column", None))
        item = self.tableWidget_atenuadores.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "New Column", None))
        item = self.tableWidget_atenuadores.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "New Column", None))
        item = self.tableWidget_atenuadores.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "New Column", None))
        item = self.tableWidget_atenuadores.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "New Column", None))
        item = self.tableWidget_atenuadores.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "New Column", None))
        item = self.tableWidget_atenuadores.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "New Column", None))
        item = self.tableWidget_atenuadores.horizontalHeaderItem(9)
        item.setText(_translate("Dialog", "New Column", None))
        item = self.tableWidget_atenuadores.horizontalHeaderItem(10)
        item.setText(_translate("Dialog", "New Column", None))
        item = self.tableWidget_atenuadores.horizontalHeaderItem(11)
        item.setText(_translate("Dialog", "New Column", None))
        item = self.tableWidget_atenuadores.horizontalHeaderItem(12)
        item.setText(_translate("Dialog", "New Column", None))
        item = self.tableWidget_atenuadores.horizontalHeaderItem(13)
        item.setText(_translate("Dialog", "New Column", None))
        item = self.tableWidget_atenuadores.horizontalHeaderItem(14)
        item.setText(_translate("Dialog", "New Column", None))
        item = self.tableWidget_atenuadores.horizontalHeaderItem(15)
        item.setText(_translate("Dialog", "New Column", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_Atenuadores), _translate("Dialog", "Atenuadores", None))
        self.label_38.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Critério de Avaliação (Valor Absoluto)</span></p></body></html>", None))
        self.label_39.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Valor Mínimo [dB]:</p></body></html>", None))
        self.switch_dc_crit.setText(_translate("Dialog", "teste", None))
        self.label_40.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Valores Medidos (Valor Absoluto) [dB]</span></p></body></html>", None))
        self.label_41.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 1</p></body></html>", None))
        self.label_42.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 2</p></body></html>", None))
        self.label_43.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 3</p></body></html>", None))
        self.label_44.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 4</p></body></html>", None))
        self.label_45.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 4</p></body></html>", None))
        self.label_46.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Resultado Final</span></p></body></html>", None))
        self.label_47.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 1</p></body></html>", None))
        self.label_48.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 3</p></body></html>", None))
        self.label_49.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 2</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_RF_Switches), _translate("Dialog", "RF Switches", None))
        self.label_51.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Valor Máximo [dB]:</p></body></html>", None))
        self.label_52.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Critério de Avaliação</span></p></body></html>", None))
        self.linearidade_crit.setText(_translate("Dialog", "4.8", None))
        self.label_54.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Valores Medidos [dB]</span></p></body></html>", None))
        self.label_60.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Resultado Final</span></p></body></html>", None))
        self.label_61.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 2</p></body></html>", None))
        self.label_62.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 4</p></body></html>", None))
        self.label_63.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 1</p></body></html>", None))
        self.label_64.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 3</p></body></html>", None))
        item = self.tableWidget_linearidade.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "Medição", None))
        item = self.tableWidget_linearidade.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "Canal 1", None))
        item = self.tableWidget_linearidade.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "Canal 2", None))
        item = self.tableWidget_linearidade.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "Canal 3", None))
        item = self.tableWidget_linearidade.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "Canal 4", None))
        item = self.tableWidget_linearidade.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "New Column", None))
        item = self.tableWidget_linearidade.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "New Column", None))
        item = self.tableWidget_linearidade.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "New Column", None))
        item = self.tableWidget_linearidade.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "New Column", None))
        item = self.tableWidget_linearidade.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "New Column", None))
        item = self.tableWidget_linearidade.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "New Column", None))
        item = self.tableWidget_linearidade.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "New Column", None))
        item = self.tableWidget_linearidade.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "New Column", None))
        item = self.tableWidget_linearidade.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "New Column", None))
        item = self.tableWidget_linearidade.horizontalHeaderItem(9)
        item.setText(_translate("Dialog", "New Column", None))
        item = self.tableWidget_linearidade.horizontalHeaderItem(10)
        item.setText(_translate("Dialog", "New Column", None))
        item = self.tableWidget_linearidade.horizontalHeaderItem(11)
        item.setText(_translate("Dialog", "New Column", None))
        item = self.tableWidget_linearidade.horizontalHeaderItem(12)
        item.setText(_translate("Dialog", "New Column", None))
        item = self.tableWidget_linearidade.horizontalHeaderItem(13)
        item.setText(_translate("Dialog", "New Column", None))
        item = self.tableWidget_linearidade.horizontalHeaderItem(14)
        item.setText(_translate("Dialog", "New Column", None))
        item = self.tableWidget_linearidade.horizontalHeaderItem(15)
        item.setText(_translate("Dialog", "New Column", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_Linearidade), _translate("Dialog", "Linearidade", None))
        self.label_50.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Valor Mínimo [dB]:</p></body></html>", None))
        self.label_65.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 1</p></body></html>", None))
        self.label_66.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Critério de Avaliação (Valor Absoluto)</span></p></body></html>", None))
        self.label_67.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 2</p></body></html>", None))
        self.label_68.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Valores Medidos (Valor Absoluto) [dB]</span></p></body></html>", None))
        self.label_69.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 1</p></body></html>", None))
        self.label_70.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 2</p></body></html>", None))
        self.label_71.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 3</p></body></html>", None))
        self.label_72.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 3</p></body></html>", None))
        self.crosstalk_crit.setText(_translate("Dialog", "teste", None))
        self.label_73.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 4</p></body></html>", None))
        self.label_74.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 4</p></body></html>", None))
        self.label_75.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Resultado Final</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_Crosstalk), _translate("Dialog", "Crosstalk", None))
        self.freq_resp_crit_min.setText(_translate("Dialog", "teste", None))
        self.label_81.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Critério de Avaliação (Valor Absoluto)</span></p></body></html>", None))
        self.label_82.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Valor Mínimo (ao longo de toda a banda de passagem do filtro) [dB]:</p></body></html>", None))
        self.label_83.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Dif. Máxima entre Medida na Freq. Central e as demais na bandwith do filtro [dB]:</p></body></html>", None))
        self.freq_resp_crit_dif.setText(_translate("Dialog", "teste", None))
        self.label_84.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Amp. Máx</p></body></html>", None))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Dif. Máx</p></body></html>", None))
        self.label_14.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Freq. - Dif. Máx [Hz]</p></body></html>", None))
        self.label_89.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Valores Medidos (Valor Absoluto) [dB]</span></p></body></html>", None))
        self.label_85.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 3</p></body></html>", None))
        self.label_86.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 4</p></body></html>", None))
        self.label_87.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 2</p></body></html>", None))
        self.label_88.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 1</p></body></html>", None))
        self.label_90.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 4</p></body></html>", None))
        self.label_91.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 1</p></body></html>", None))
        self.label_92.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 3</p></body></html>", None))
        self.label_93.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Resultado Final</span></p></body></html>", None))
        self.label_94.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 2</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_Freq_Resp), _translate("Dialog", "Frequency Response", None))
        self.ret_loss_s22_crit.setText(_translate("Dialog", "4.8", None))
        self.label_95.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">S11 -&gt; Valor Mínimo [dB]:</p></body></html>", None))
        self.label_96.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">S22 -&gt; Valor Mínimo [dB]:</p></body></html>", None))
        self.label_97.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Critério de Avaliação (Valor Absoluto)</span></p></body></html>", None))
        self.ret_loss_s11_crit.setText(_translate("Dialog", "5,2", None))
        self.label_98.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 1</p></body></html>", None))
        self.label_99.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 3</p></body></html>", None))
        self.label_100.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Valores Medidos (Valor Absoluto) [dB]</span></p></body></html>", None))
        self.label_101.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 2</p></body></html>", None))
        self.label_102.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 4</p></body></html>", None))
        self.label_103.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">S11</p></body></html>", None))
        self.label_104.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">S22</p></body></html>", None))
        self.label_105.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Resultado Final</span></p></body></html>", None))
        self.label_106.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 4</p></body></html>", None))
        self.label_107.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 2</p></body></html>", None))
        self.label_108.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">S22</p></body></html>", None))
        self.label_109.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 1</p></body></html>", None))
        self.label_110.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">S11</p></body></html>", None))
        self.label_111.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 3</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_Return_Loss), _translate("Dialog", "Return Loss", None))
        self.label_76.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Critério de Avaliação</span></p></body></html>", None))
        self.temp_crit_max.setText(_translate("Dialog", "5,2", None))
        self.temp_crit_min.setText(_translate("Dialog", "4.8", None))
        self.label_77.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Valor Máximo [°C]:</p></body></html>", None))
        self.label_78.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Valor Mínimo [°C]:</p></body></html>", None))
        self.label_79.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Valores Medidos [°C]</span></p></body></html>", None))
        self.label_80.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Resultado Final</span></p></body></html>", None))
        self.label_112.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Medida 1</p></body></html>", None))
        self.label_113.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Medida 2</p></body></html>", None))
        self.label_114.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Medida 3</p></body></html>", None))
        self.label_115.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Medida 4</p></body></html>", None))
        self.label_116.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Medida 5</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_Temperatura), _translate("Dialog", "Temperatura", None))
        self.OK_BUTTON.setText(_translate("Dialog", "OK", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

