# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_principal_V3.ui'
#
# Created: Thu May 18 09:14:59 2017
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1135, 655)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        MainWindow.setPalette(palette)
        MainWindow.setDocumentMode(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 501, 61))
        self.label.setObjectName(_fromUtf8("label"))
        self.START_BUTTON = QtGui.QPushButton(self.centralwidget)
        self.START_BUTTON.setGeometry(QtCore.QRect(930, 600, 87, 27))
        self.START_BUTTON.setObjectName(_fromUtf8("START_BUTTON"))
        self.STOP_BUTTON = QtGui.QPushButton(self.centralwidget)
        self.STOP_BUTTON.setGeometry(QtCore.QRect(1020, 600, 87, 27))
        self.STOP_BUTTON.setObjectName(_fromUtf8("STOP_BUTTON"))
        self.checkGraficos = QtGui.QCheckBox(self.centralwidget)
        self.checkGraficos.setGeometry(QtCore.QRect(560, 60, 135, 20))
        self.checkGraficos.setObjectName(_fromUtf8("checkGraficos"))
        self.checkGravarFPGA = QtGui.QCheckBox(self.centralwidget)
        self.checkGravarFPGA.setGeometry(QtCore.QRect(450, 60, 101, 20))
        self.checkGravarFPGA.setObjectName(_fromUtf8("checkGravarFPGA"))
        self.checkUtilizarMATLAB = QtGui.QCheckBox(self.centralwidget)
        self.checkUtilizarMATLAB.setGeometry(QtCore.QRect(700, 60, 135, 20))
        self.checkUtilizarMATLAB.setObjectName(_fromUtf8("checkUtilizarMATLAB"))
        self.dateTimeEdit_MainScreen = QtGui.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit_MainScreen.setGeometry(QtCore.QRect(560, 20, 141, 26))
        self.dateTimeEdit_MainScreen.setWrapping(False)
        self.dateTimeEdit_MainScreen.setFrame(True)
        self.dateTimeEdit_MainScreen.setReadOnly(True)
        self.dateTimeEdit_MainScreen.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit_MainScreen.setObjectName(_fromUtf8("dateTimeEdit_MainScreen"))
        self.OPERADOR = QtGui.QLineEdit(self.centralwidget)
        self.OPERADOR.setGeometry(QtCore.QRect(1000, 17, 101, 26))
        self.OPERADOR.setObjectName(_fromUtf8("OPERADOR"))
        self.N_SERIE_ADC = QtGui.QLineEdit(self.centralwidget)
        self.N_SERIE_ADC.setGeometry(QtCore.QRect(1000, 50, 101, 26))
        self.N_SERIE_ADC.setObjectName(_fromUtf8("N_SERIE_ADC"))
        self.label_34 = QtGui.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(890, 20, 91, 21))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.label_35 = QtGui.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(890, 50, 91, 21))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 70, 1097, 521))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.tabWidget.setPalette(palette)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Test_Config = QtGui.QWidget()
        self.Test_Config.setObjectName(_fromUtf8("Test_Config"))
        self.frame_5 = QtGui.QFrame(self.Test_Config)
        self.frame_5.setGeometry(QtCore.QRect(770, 190, 311, 291))
        self.frame_5.setFrameShape(QtGui.QFrame.Box)
        self.frame_5.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.label_23 = QtGui.QLabel(self.frame_5)
        self.label_23.setGeometry(QtCore.QRect(10, 20, 301, 16))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.check_enob = QtGui.QRadioButton(self.frame_5)
        self.check_enob.setGeometry(QtCore.QRect(30, 80, 104, 31))
        self.check_enob.setAutoExclusive(False)
        self.check_enob.setObjectName(_fromUtf8("check_enob"))
        self.check_sfdr = QtGui.QRadioButton(self.frame_5)
        self.check_sfdr.setGeometry(QtCore.QRect(30, 110, 104, 31))
        self.check_sfdr.setAutoExclusive(False)
        self.check_sfdr.setObjectName(_fromUtf8("check_sfdr"))
        self.check_crosstalk = QtGui.QRadioButton(self.frame_5)
        self.check_crosstalk.setGeometry(QtCore.QRect(30, 140, 104, 31))
        self.check_crosstalk.setAutoExclusive(False)
        self.check_crosstalk.setObjectName(_fromUtf8("check_crosstalk"))
        self.check_missingcodes = QtGui.QRadioButton(self.frame_5)
        self.check_missingcodes.setGeometry(QtCore.QRect(30, 170, 131, 31))
        self.check_missingcodes.setAutoExclusive(False)
        self.check_missingcodes.setObjectName(_fromUtf8("check_missingcodes"))
        self.check_all = QtGui.QRadioButton(self.frame_5)
        self.check_all.setGeometry(QtCore.QRect(120, 240, 104, 31))
        self.check_all.setAutoExclusive(False)
        self.check_all.setObjectName(_fromUtf8("check_all"))
        self.check_dif_ampl = QtGui.QRadioButton(self.frame_5)
        self.check_dif_ampl.setGeometry(QtCore.QRect(30, 200, 141, 31))
        self.check_dif_ampl.setAutoExclusive(False)
        self.check_dif_ampl.setObjectName(_fromUtf8("check_dif_ampl"))
        self.check_snr = QtGui.QRadioButton(self.frame_5)
        self.check_snr.setGeometry(QtCore.QRect(30, 60, 55, 20))
        self.check_snr.setAutoExclusive(False)
        self.check_snr.setObjectName(_fromUtf8("check_snr"))
        self.check_eeprom = QtGui.QRadioButton(self.frame_5)
        self.check_eeprom.setGeometry(QtCore.QRect(180, 60, 91, 20))
        self.check_eeprom.setAutoExclusive(False)
        self.check_eeprom.setObjectName(_fromUtf8("check_eeprom"))
        self.check_ics854s01i = QtGui.QRadioButton(self.frame_5)
        self.check_ics854s01i.setGeometry(QtCore.QRect(180, 110, 121, 31))
        self.check_ics854s01i.setAutoExclusive(False)
        self.check_ics854s01i.setObjectName(_fromUtf8("check_ics854s01i"))
        self.check_sensor_temperatura = QtGui.QRadioButton(self.frame_5)
        self.check_sensor_temperatura.setGeometry(QtCore.QRect(180, 170, 131, 31))
        self.check_sensor_temperatura.setAutoExclusive(False)
        self.check_sensor_temperatura.setObjectName(_fromUtf8("check_sensor_temperatura"))
        self.check_ad9510 = QtGui.QRadioButton(self.frame_5)
        self.check_ad9510.setGeometry(QtCore.QRect(180, 140, 104, 31))
        self.check_ad9510.setAutoExclusive(False)
        self.check_ad9510.setObjectName(_fromUtf8("check_ad9510"))
        self.check_si571 = QtGui.QRadioButton(self.frame_5)
        self.check_si571.setGeometry(QtCore.QRect(180, 80, 104, 31))
        self.check_si571.setAutoExclusive(False)
        self.check_si571.setObjectName(_fromUtf8("check_si571"))
        self.label_17 = QtGui.QLabel(self.Test_Config)
        self.label_17.setGeometry(QtCore.QRect(470, 320, 111, 26))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.Test_Config)
        self.label_18.setGeometry(QtCore.QRect(470, 380, 121, 26))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_16 = QtGui.QLabel(self.Test_Config)
        self.label_16.setGeometry(QtCore.QRect(470, 350, 101, 26))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_15 = QtGui.QLabel(self.Test_Config)
        self.label_15.setGeometry(QtCore.QRect(470, 290, 81, 26))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.frame_4 = QtGui.QFrame(self.Test_Config)
        self.frame_4.setGeometry(QtCore.QRect(450, 240, 311, 241))
        self.frame_4.setFrameShape(QtGui.QFrame.Box)
        self.frame_4.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.label_21 = QtGui.QLabel(self.frame_4)
        self.label_21.setGeometry(QtCore.QRect(10, 20, 291, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.frame_4)
        self.label_22.setGeometry(QtCore.QRect(20, 170, 121, 26))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.MISSINGCODE_CRITERIO = QtGui.QLineEdit(self.frame_4)
        self.MISSINGCODE_CRITERIO.setGeometry(QtCore.QRect(180, 170, 123, 26))
        self.MISSINGCODE_CRITERIO.setObjectName(_fromUtf8("MISSINGCODE_CRITERIO"))
        self.ENOB_CRITERIO = QtGui.QLineEdit(self.frame_4)
        self.ENOB_CRITERIO.setGeometry(QtCore.QRect(180, 110, 123, 26))
        self.ENOB_CRITERIO.setObjectName(_fromUtf8("ENOB_CRITERIO"))
        self.SFDR_CRITERIO = QtGui.QLineEdit(self.frame_4)
        self.SFDR_CRITERIO.setGeometry(QtCore.QRect(180, 80, 123, 26))
        self.SFDR_CRITERIO.setObjectName(_fromUtf8("SFDR_CRITERIO"))
        self.SNR_CRITERIO = QtGui.QLineEdit(self.frame_4)
        self.SNR_CRITERIO.setGeometry(QtCore.QRect(180, 50, 123, 26))
        self.SNR_CRITERIO.setObjectName(_fromUtf8("SNR_CRITERIO"))
        self.CROSSTALK_CRITERIO = QtGui.QLineEdit(self.frame_4)
        self.CROSSTALK_CRITERIO.setGeometry(QtCore.QRect(180, 140, 123, 26))
        self.CROSSTALK_CRITERIO.setObjectName(_fromUtf8("CROSSTALK_CRITERIO"))
        self.label_25 = QtGui.QLabel(self.frame_4)
        self.label_25.setGeometry(QtCore.QRect(20, 200, 161, 26))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.DIF_AMPL_CRITERIO = QtGui.QLineEdit(self.frame_4)
        self.DIF_AMPL_CRITERIO.setGeometry(QtCore.QRect(180, 200, 123, 26))
        self.DIF_AMPL_CRITERIO.setObjectName(_fromUtf8("DIF_AMPL_CRITERIO"))
        self.frame_6 = QtGui.QFrame(self.Test_Config)
        self.frame_6.setGeometry(QtCore.QRect(450, 10, 311, 221))
        self.frame_6.setFrameShape(QtGui.QFrame.Box)
        self.frame_6.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.label_26 = QtGui.QLabel(self.frame_6)
        self.label_26.setGeometry(QtCore.QRect(10, 10, 291, 41))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.frame_6)
        self.label_27.setGeometry(QtCore.QRect(10, 90, 191, 26))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(self.frame_6)
        self.label_28.setGeometry(QtCore.QRect(10, 120, 191, 26))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.AMP_IN_MISSINGCODES = QtGui.QLineEdit(self.frame_6)
        self.AMP_IN_MISSINGCODES.setGeometry(QtCore.QRect(210, 150, 91, 26))
        self.AMP_IN_MISSINGCODES.setObjectName(_fromUtf8("AMP_IN_MISSINGCODES"))
        self.AMP_CLOCK_MISSINGCODES = QtGui.QLineEdit(self.frame_6)
        self.AMP_CLOCK_MISSINGCODES.setGeometry(QtCore.QRect(210, 120, 91, 26))
        self.AMP_CLOCK_MISSINGCODES.setObjectName(_fromUtf8("AMP_CLOCK_MISSINGCODES"))
        self.FREQ_CLOCK_MISSINGCODES = QtGui.QLineEdit(self.frame_6)
        self.FREQ_CLOCK_MISSINGCODES.setGeometry(QtCore.QRect(210, 60, 91, 26))
        self.FREQ_CLOCK_MISSINGCODES.setObjectName(_fromUtf8("FREQ_CLOCK_MISSINGCODES"))
        self.FREQ_IN_MISSINGCODES = QtGui.QLineEdit(self.frame_6)
        self.FREQ_IN_MISSINGCODES.setGeometry(QtCore.QRect(210, 90, 91, 26))
        self.FREQ_IN_MISSINGCODES.setObjectName(_fromUtf8("FREQ_IN_MISSINGCODES"))
        self.label_29 = QtGui.QLabel(self.frame_6)
        self.label_29.setGeometry(QtCore.QRect(10, 150, 191, 26))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(self.frame_6)
        self.label_30.setGeometry(QtCore.QRect(10, 60, 191, 26))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_31 = QtGui.QLabel(self.frame_6)
        self.label_31.setGeometry(QtCore.QRect(10, 180, 191, 26))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.PERDA_FILTRO_MISSINGCODES = QtGui.QLineEdit(self.frame_6)
        self.PERDA_FILTRO_MISSINGCODES.setGeometry(QtCore.QRect(210, 180, 91, 26))
        self.PERDA_FILTRO_MISSINGCODES.setObjectName(_fromUtf8("PERDA_FILTRO_MISSINGCODES"))
        self.label_14 = QtGui.QLabel(self.Test_Config)
        self.label_14.setGeometry(QtCore.QRect(20, 60, 91, 26))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.frame_3 = QtGui.QFrame(self.Test_Config)
        self.frame_3.setGeometry(QtCore.QRect(10, 260, 431, 181))
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.label_20 = QtGui.QLabel(self.frame_3)
        self.label_20.setGeometry(QtCore.QRect(10, 20, 311, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_8 = QtGui.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(10, 80, 261, 26))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_7 = QtGui.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(10, 110, 271, 26))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.AMP_IN = QtGui.QLineEdit(self.frame_3)
        self.AMP_IN.setGeometry(QtCore.QRect(300, 140, 123, 26))
        self.AMP_IN.setObjectName(_fromUtf8("AMP_IN"))
        self.AMP_CLOCK = QtGui.QLineEdit(self.frame_3)
        self.AMP_CLOCK.setGeometry(QtCore.QRect(300, 110, 123, 26))
        self.AMP_CLOCK.setObjectName(_fromUtf8("AMP_CLOCK"))
        self.FREQ_CLOCK = QtGui.QLineEdit(self.frame_3)
        self.FREQ_CLOCK.setGeometry(QtCore.QRect(300, 50, 123, 26))
        self.FREQ_CLOCK.setObjectName(_fromUtf8("FREQ_CLOCK"))
        self.FREQ_IN = QtGui.QLineEdit(self.frame_3)
        self.FREQ_IN.setGeometry(QtCore.QRect(300, 80, 123, 26))
        self.FREQ_IN.setObjectName(_fromUtf8("FREQ_IN"))
        self.label_9 = QtGui.QLabel(self.frame_3)
        self.label_9.setGeometry(QtCore.QRect(10, 140, 261, 26))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_3 = QtGui.QLabel(self.Test_Config)
        self.label_3.setGeometry(QtCore.QRect(18, 90, 221, 26))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_5 = QtGui.QLabel(self.Test_Config)
        self.label_5.setGeometry(QtCore.QRect(20, 310, 211, 26))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_4 = QtGui.QLabel(self.Test_Config)
        self.label_4.setGeometry(QtCore.QRect(20, 120, 231, 26))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_12 = QtGui.QLabel(self.Test_Config)
        self.label_12.setGeometry(QtCore.QRect(20, 180, 241, 26))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.Test_Config)
        self.label_13.setGeometry(QtCore.QRect(20, 210, 211, 26))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.frame = QtGui.QFrame(self.Test_Config)
        self.frame.setGeometry(QtCore.QRect(10, 10, 431, 241))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 231, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.POSICAO_AD = QtGui.QLineEdit(self.frame)
        self.POSICAO_AD.setGeometry(QtCore.QRect(300, 200, 123, 26))
        self.POSICAO_AD.setObjectName(_fromUtf8("POSICAO_AD"))
        self.POSICAO_AFC = QtGui.QLineEdit(self.frame)
        self.POSICAO_AFC.setGeometry(QtCore.QRect(300, 170, 123, 26))
        self.POSICAO_AFC.setObjectName(_fromUtf8("POSICAO_AFC"))
        self.IP_SWITCH = QtGui.QLineEdit(self.frame)
        self.IP_SWITCH.setGeometry(QtCore.QRect(300, 80, 123, 26))
        self.IP_SWITCH.setObjectName(_fromUtf8("IP_SWITCH"))
        self.IP_CRATE = QtGui.QLineEdit(self.frame)
        self.IP_CRATE.setGeometry(QtCore.QRect(300, 50, 123, 26))
        self.IP_CRATE.setObjectName(_fromUtf8("IP_CRATE"))
        self.IP_GERADOR_SINAIS_CLOCK = QtGui.QLineEdit(self.frame)
        self.IP_GERADOR_SINAIS_CLOCK.setGeometry(QtCore.QRect(300, 110, 123, 26))
        self.IP_GERADOR_SINAIS_CLOCK.setObjectName(_fromUtf8("IP_GERADOR_SINAIS_CLOCK"))
        self.IP_GERADOR_SINAIS_INPUT = QtGui.QLineEdit(self.frame)
        self.IP_GERADOR_SINAIS_INPUT.setGeometry(QtCore.QRect(300, 140, 123, 26))
        self.IP_GERADOR_SINAIS_INPUT.setObjectName(_fromUtf8("IP_GERADOR_SINAIS_INPUT"))
        self.label_24 = QtGui.QLabel(self.frame)
        self.label_24.setGeometry(QtCore.QRect(10, 140, 251, 26))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_33 = QtGui.QLabel(self.Test_Config)
        self.label_33.setGeometry(QtCore.QRect(10, 450, 301, 31))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.label_6 = QtGui.QLabel(self.Test_Config)
        self.label_6.setGeometry(QtCore.QRect(780, 60, 141, 26))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_11 = QtGui.QLabel(self.Test_Config)
        self.label_11.setGeometry(QtCore.QRect(780, 90, 161, 26))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_10 = QtGui.QLabel(self.Test_Config)
        self.label_10.setGeometry(QtCore.QRect(780, 150, 151, 26))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.frame_2 = QtGui.QFrame(self.Test_Config)
        self.frame_2.setGeometry(QtCore.QRect(770, 10, 311, 171))
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label_19 = QtGui.QLabel(self.frame_2)
        self.label_19.setGeometry(QtCore.QRect(10, 20, 301, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.N_FFT = QtGui.QLineEdit(self.frame_2)
        self.N_FFT.setGeometry(QtCore.QRect(232, 50, 71, 26))
        self.N_FFT.setObjectName(_fromUtf8("N_FFT"))
        self.N_CRATE = QtGui.QLineEdit(self.frame_2)
        self.N_CRATE.setGeometry(QtCore.QRect(232, 80, 71, 26))
        self.N_CRATE.setObjectName(_fromUtf8("N_CRATE"))
        self.N_REQUISICOES = QtGui.QLineEdit(self.frame_2)
        self.N_REQUISICOES.setGeometry(QtCore.QRect(232, 140, 71, 26))
        self.N_REQUISICOES.setObjectName(_fromUtf8("N_REQUISICOES"))
        self.label_32 = QtGui.QLabel(self.frame_2)
        self.label_32.setGeometry(QtCore.QRect(10, 110, 221, 26))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.N_CRATE_MISSINGCODES = QtGui.QLineEdit(self.frame_2)
        self.N_CRATE_MISSINGCODES.setGeometry(QtCore.QRect(232, 110, 71, 26))
        self.N_CRATE_MISSINGCODES.setObjectName(_fromUtf8("N_CRATE_MISSINGCODES"))
        self.tabWidget.addTab(self.Test_Config, _fromUtf8(""))
        self.ADC_Config = QtGui.QWidget()
        self.ADC_Config.setObjectName(_fromUtf8("ADC_Config"))
        self.frame_7 = QtGui.QFrame(self.ADC_Config)
        self.frame_7.setGeometry(QtCore.QRect(70, 80, 541, 361))
        self.frame_7.setFrameShape(QtGui.QFrame.Box)
        self.frame_7.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.ad9510_pll_function_config = QtGui.QLineEdit(self.frame_7)
        self.ad9510_pll_function_config.setGeometry(QtCore.QRect(440, 50, 71, 26))
        self.ad9510_pll_function_config.setObjectName(_fromUtf8("ad9510_pll_function_config"))
        self.label_36 = QtGui.QLabel(self.frame_7)
        self.label_36.setGeometry(QtCore.QRect(70, 50, 241, 21))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.label_37 = QtGui.QLabel(self.frame_7)
        self.label_37.setGeometry(QtCore.QRect(20, 20, 341, 16))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.label_39 = QtGui.QLabel(self.frame_7)
        self.label_39.setGeometry(QtCore.QRect(70, 80, 231, 21))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.ad9510_pll_clock_sel_config = QtGui.QLineEdit(self.frame_7)
        self.ad9510_pll_clock_sel_config.setGeometry(QtCore.QRect(440, 80, 71, 26))
        self.ad9510_pll_clock_sel_config.setObjectName(_fromUtf8("ad9510_pll_clock_sel_config"))
        self.label_40 = QtGui.QLabel(self.frame_7)
        self.label_40.setGeometry(QtCore.QRect(70, 140, 81, 21))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.ad9510_a_divider_config = QtGui.QLineEdit(self.frame_7)
        self.ad9510_a_divider_config.setGeometry(QtCore.QRect(440, 140, 71, 26))
        self.ad9510_a_divider_config.setObjectName(_fromUtf8("ad9510_a_divider_config"))
        self.label_41 = QtGui.QLabel(self.frame_7)
        self.label_41.setGeometry(QtCore.QRect(70, 170, 81, 21))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.ad9510_b_divider_config = QtGui.QLineEdit(self.frame_7)
        self.ad9510_b_divider_config.setGeometry(QtCore.QRect(440, 170, 71, 26))
        self.ad9510_b_divider_config.setObjectName(_fromUtf8("ad9510_b_divider_config"))
        self.label_42 = QtGui.QLabel(self.frame_7)
        self.label_42.setGeometry(QtCore.QRect(70, 200, 81, 21))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.ad9510_r_divider_config = QtGui.QLineEdit(self.frame_7)
        self.ad9510_r_divider_config.setGeometry(QtCore.QRect(440, 200, 71, 26))
        self.ad9510_r_divider_config.setObjectName(_fromUtf8("ad9510_r_divider_config"))
        self.label_43 = QtGui.QLabel(self.frame_7)
        self.label_43.setGeometry(QtCore.QRect(70, 230, 81, 21))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.ad9510_prescaler_config = QtGui.QLineEdit(self.frame_7)
        self.ad9510_prescaler_config.setGeometry(QtCore.QRect(440, 230, 71, 26))
        self.ad9510_prescaler_config.setObjectName(_fromUtf8("ad9510_prescaler_config"))
        self.label_44 = QtGui.QLabel(self.frame_7)
        self.label_44.setGeometry(QtCore.QRect(70, 260, 211, 21))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.ad9510_pll_powerdown_config = QtGui.QLineEdit(self.frame_7)
        self.ad9510_pll_powerdown_config.setGeometry(QtCore.QRect(440, 260, 71, 26))
        self.ad9510_pll_powerdown_config.setObjectName(_fromUtf8("ad9510_pll_powerdown_config"))
        self.label_45 = QtGui.QLabel(self.frame_7)
        self.label_45.setGeometry(QtCore.QRect(70, 290, 301, 21))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.ad9510_current_config = QtGui.QLineEdit(self.frame_7)
        self.ad9510_current_config.setGeometry(QtCore.QRect(440, 290, 71, 26))
        self.ad9510_current_config.setObjectName(_fromUtf8("ad9510_current_config"))
        self.label_46 = QtGui.QLabel(self.frame_7)
        self.label_46.setGeometry(QtCore.QRect(70, 110, 341, 21))
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.ad9510_pll_clock_sel_ref_config = QtGui.QLineEdit(self.frame_7)
        self.ad9510_pll_clock_sel_ref_config.setGeometry(QtCore.QRect(440, 110, 71, 26))
        self.ad9510_pll_clock_sel_ref_config.setObjectName(_fromUtf8("ad9510_pll_clock_sel_ref_config"))
        self.label_48 = QtGui.QLabel(self.frame_7)
        self.label_48.setGeometry(QtCore.QRect(70, 320, 231, 21))
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.ad9510_outputs_config = QtGui.QLineEdit(self.frame_7)
        self.ad9510_outputs_config.setGeometry(QtCore.QRect(440, 320, 71, 26))
        self.ad9510_outputs_config.setObjectName(_fromUtf8("ad9510_outputs_config"))
        self.ad9510_pll_function_config_check = QtGui.QRadioButton(self.frame_7)
        self.ad9510_pll_function_config_check.setGeometry(QtCore.QRect(30, 50, 21, 20))
        self.ad9510_pll_function_config_check.setText(_fromUtf8(""))
        self.ad9510_pll_function_config_check.setAutoExclusive(False)
        self.ad9510_pll_function_config_check.setObjectName(_fromUtf8("ad9510_pll_function_config_check"))
        self.ad9510_pll_clock_sel_config_check = QtGui.QRadioButton(self.frame_7)
        self.ad9510_pll_clock_sel_config_check.setGeometry(QtCore.QRect(30, 80, 21, 20))
        self.ad9510_pll_clock_sel_config_check.setText(_fromUtf8(""))
        self.ad9510_pll_clock_sel_config_check.setAutoExclusive(False)
        self.ad9510_pll_clock_sel_config_check.setObjectName(_fromUtf8("ad9510_pll_clock_sel_config_check"))
        self.ad9510_pll_clock_sel_ref_config_check = QtGui.QRadioButton(self.frame_7)
        self.ad9510_pll_clock_sel_ref_config_check.setGeometry(QtCore.QRect(30, 110, 21, 20))
        self.ad9510_pll_clock_sel_ref_config_check.setText(_fromUtf8(""))
        self.ad9510_pll_clock_sel_ref_config_check.setAutoExclusive(False)
        self.ad9510_pll_clock_sel_ref_config_check.setObjectName(_fromUtf8("ad9510_pll_clock_sel_ref_config_check"))
        self.ad9510_a_divider_config_check = QtGui.QRadioButton(self.frame_7)
        self.ad9510_a_divider_config_check.setGeometry(QtCore.QRect(30, 140, 21, 20))
        self.ad9510_a_divider_config_check.setText(_fromUtf8(""))
        self.ad9510_a_divider_config_check.setAutoExclusive(False)
        self.ad9510_a_divider_config_check.setObjectName(_fromUtf8("ad9510_a_divider_config_check"))
        self.ad9510_b_divider_config_check = QtGui.QRadioButton(self.frame_7)
        self.ad9510_b_divider_config_check.setGeometry(QtCore.QRect(30, 170, 21, 20))
        self.ad9510_b_divider_config_check.setText(_fromUtf8(""))
        self.ad9510_b_divider_config_check.setAutoExclusive(False)
        self.ad9510_b_divider_config_check.setObjectName(_fromUtf8("ad9510_b_divider_config_check"))
        self.ad9510_r_divider_config_check = QtGui.QRadioButton(self.frame_7)
        self.ad9510_r_divider_config_check.setGeometry(QtCore.QRect(30, 200, 21, 20))
        self.ad9510_r_divider_config_check.setText(_fromUtf8(""))
        self.ad9510_r_divider_config_check.setAutoExclusive(False)
        self.ad9510_r_divider_config_check.setObjectName(_fromUtf8("ad9510_r_divider_config_check"))
        self.ad9510_prescaler_config_check = QtGui.QRadioButton(self.frame_7)
        self.ad9510_prescaler_config_check.setGeometry(QtCore.QRect(30, 230, 21, 20))
        self.ad9510_prescaler_config_check.setText(_fromUtf8(""))
        self.ad9510_prescaler_config_check.setAutoExclusive(False)
        self.ad9510_prescaler_config_check.setObjectName(_fromUtf8("ad9510_prescaler_config_check"))
        self.ad9510_pll_powerdown_config_check = QtGui.QRadioButton(self.frame_7)
        self.ad9510_pll_powerdown_config_check.setGeometry(QtCore.QRect(30, 260, 21, 20))
        self.ad9510_pll_powerdown_config_check.setText(_fromUtf8(""))
        self.ad9510_pll_powerdown_config_check.setAutoExclusive(False)
        self.ad9510_pll_powerdown_config_check.setObjectName(_fromUtf8("ad9510_pll_powerdown_config_check"))
        self.ad9510_current_config_check = QtGui.QRadioButton(self.frame_7)
        self.ad9510_current_config_check.setGeometry(QtCore.QRect(30, 290, 21, 20))
        self.ad9510_current_config_check.setText(_fromUtf8(""))
        self.ad9510_current_config_check.setAutoExclusive(False)
        self.ad9510_current_config_check.setObjectName(_fromUtf8("ad9510_current_config_check"))
        self.ad9510_outputs_config_check = QtGui.QRadioButton(self.frame_7)
        self.ad9510_outputs_config_check.setGeometry(QtCore.QRect(30, 320, 21, 20))
        self.ad9510_outputs_config_check.setText(_fromUtf8(""))
        self.ad9510_outputs_config_check.setAutoExclusive(False)
        self.ad9510_outputs_config_check.setObjectName(_fromUtf8("ad9510_outputs_config_check"))
        self.frame_8 = QtGui.QFrame(self.ADC_Config)
        self.frame_8.setGeometry(QtCore.QRect(650, 80, 381, 121))
        self.frame_8.setFrameShape(QtGui.QFrame.Box)
        self.frame_8.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.label_58 = QtGui.QLabel(self.frame_8)
        self.label_58.setGeometry(QtCore.QRect(20, 20, 341, 16))
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.label_59 = QtGui.QLabel(self.frame_8)
        self.label_59.setGeometry(QtCore.QRect(58, 50, 101, 21))
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.label_60 = QtGui.QLabel(self.frame_8)
        self.label_60.setGeometry(QtCore.QRect(58, 80, 191, 21))
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.si571_freq_config = QtGui.QLineEdit(self.frame_8)
        self.si571_freq_config.setGeometry(QtCore.QRect(260, 50, 101, 26))
        self.si571_freq_config.setObjectName(_fromUtf8("si571_freq_config"))
        self.si571_output_config = QtGui.QLineEdit(self.frame_8)
        self.si571_output_config.setGeometry(QtCore.QRect(260, 80, 101, 26))
        self.si571_output_config.setObjectName(_fromUtf8("si571_output_config"))
        self.frame_9 = QtGui.QFrame(self.ADC_Config)
        self.frame_9.setGeometry(QtCore.QRect(650, 230, 381, 151))
        self.frame_9.setFrameShape(QtGui.QFrame.Box)
        self.frame_9.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.label_61 = QtGui.QLabel(self.frame_9)
        self.label_61.setGeometry(QtCore.QRect(20, 20, 131, 16))
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.result_config = QtGui.QLineEdit(self.frame_9)
        self.result_config.setGeometry(QtCore.QRect(230, 90, 101, 26))
        self.result_config.setObjectName(_fromUtf8("result_config"))
        self.label_47 = QtGui.QLabel(self.frame_9)
        self.label_47.setGeometry(QtCore.QRect(30, 90, 171, 21))
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.label_51 = QtGui.QLabel(self.frame_9)
        self.label_51.setGeometry(QtCore.QRect(30, 50, 191, 21))
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.communication_config = QtGui.QLineEdit(self.frame_9)
        self.communication_config.setGeometry(QtCore.QRect(230, 50, 101, 26))
        self.communication_config.setObjectName(_fromUtf8("communication_config"))
        self.label_62 = QtGui.QLabel(self.ADC_Config)
        self.label_62.setGeometry(QtCore.QRect(30, 20, 411, 41))
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.progressBar_config = QtGui.QProgressBar(self.ADC_Config)
        self.progressBar_config.setGeometry(QtCore.QRect(670, 410, 251, 23))
        self.progressBar_config.setProperty("value", 0)
        self.progressBar_config.setObjectName(_fromUtf8("progressBar_config"))
        self.CONFIG_BUTTON = QtGui.QPushButton(self.ADC_Config)
        self.CONFIG_BUTTON.setGeometry(QtCore.QRect(940, 410, 87, 27))
        self.CONFIG_BUTTON.setObjectName(_fromUtf8("CONFIG_BUTTON"))
        self.label_49 = QtGui.QLabel(self.ADC_Config)
        self.label_49.setGeometry(QtCore.QRect(70, 440, 471, 21))
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.label_50 = QtGui.QLabel(self.ADC_Config)
        self.label_50.setGeometry(QtCore.QRect(75, 456, 471, 21))
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.si571_freq_config_check = QtGui.QRadioButton(self.ADC_Config)
        self.si571_freq_config_check.setGeometry(QtCore.QRect(680, 130, 21, 20))
        self.si571_freq_config_check.setText(_fromUtf8(""))
        self.si571_freq_config_check.setAutoExclusive(False)
        self.si571_freq_config_check.setObjectName(_fromUtf8("si571_freq_config_check"))
        self.si571_output_config_check = QtGui.QRadioButton(self.ADC_Config)
        self.si571_output_config_check.setGeometry(QtCore.QRect(680, 160, 21, 20))
        self.si571_output_config_check.setText(_fromUtf8(""))
        self.si571_output_config_check.setAutoExclusive(False)
        self.si571_output_config_check.setObjectName(_fromUtf8("si571_output_config_check"))
        self.all_config_check = QtGui.QRadioButton(self.ADC_Config)
        self.all_config_check.setGeometry(QtCore.QRect(480, 40, 241, 20))
        self.all_config_check.setObjectName(_fromUtf8("all_config_check"))
        self.tabWidget.addTab(self.ADC_Config, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.IP_CRATE, self.IP_SWITCH)
        MainWindow.setTabOrder(self.IP_SWITCH, self.IP_GERADOR_SINAIS_CLOCK)
        MainWindow.setTabOrder(self.IP_GERADOR_SINAIS_CLOCK, self.IP_GERADOR_SINAIS_INPUT)
        MainWindow.setTabOrder(self.IP_GERADOR_SINAIS_INPUT, self.POSICAO_AFC)
        MainWindow.setTabOrder(self.POSICAO_AFC, self.POSICAO_AD)
        MainWindow.setTabOrder(self.POSICAO_AD, self.FREQ_CLOCK)
        MainWindow.setTabOrder(self.FREQ_CLOCK, self.FREQ_IN)
        MainWindow.setTabOrder(self.FREQ_IN, self.AMP_CLOCK)
        MainWindow.setTabOrder(self.AMP_CLOCK, self.AMP_IN)
        MainWindow.setTabOrder(self.AMP_IN, self.FREQ_CLOCK_MISSINGCODES)
        MainWindow.setTabOrder(self.FREQ_CLOCK_MISSINGCODES, self.FREQ_IN_MISSINGCODES)
        MainWindow.setTabOrder(self.FREQ_IN_MISSINGCODES, self.AMP_CLOCK_MISSINGCODES)
        MainWindow.setTabOrder(self.AMP_CLOCK_MISSINGCODES, self.AMP_IN_MISSINGCODES)
        MainWindow.setTabOrder(self.AMP_IN_MISSINGCODES, self.PERDA_FILTRO_MISSINGCODES)
        MainWindow.setTabOrder(self.PERDA_FILTRO_MISSINGCODES, self.SNR_CRITERIO)
        MainWindow.setTabOrder(self.SNR_CRITERIO, self.SFDR_CRITERIO)
        MainWindow.setTabOrder(self.SFDR_CRITERIO, self.ENOB_CRITERIO)
        MainWindow.setTabOrder(self.ENOB_CRITERIO, self.CROSSTALK_CRITERIO)
        MainWindow.setTabOrder(self.CROSSTALK_CRITERIO, self.MISSINGCODE_CRITERIO)
        MainWindow.setTabOrder(self.MISSINGCODE_CRITERIO, self.DIF_AMPL_CRITERIO)
        MainWindow.setTabOrder(self.DIF_AMPL_CRITERIO, self.N_FFT)
        MainWindow.setTabOrder(self.N_FFT, self.N_CRATE)
        MainWindow.setTabOrder(self.N_CRATE, self.N_CRATE_MISSINGCODES)
        MainWindow.setTabOrder(self.N_CRATE_MISSINGCODES, self.N_REQUISICOES)
        MainWindow.setTabOrder(self.N_REQUISICOES, self.check_snr)
        MainWindow.setTabOrder(self.check_snr, self.check_enob)
        MainWindow.setTabOrder(self.check_enob, self.check_sfdr)
        MainWindow.setTabOrder(self.check_sfdr, self.check_crosstalk)
        MainWindow.setTabOrder(self.check_crosstalk, self.check_missingcodes)
        MainWindow.setTabOrder(self.check_missingcodes, self.check_dif_ampl)
        MainWindow.setTabOrder(self.check_dif_ampl, self.check_eeprom)
        MainWindow.setTabOrder(self.check_eeprom, self.check_si571)
        MainWindow.setTabOrder(self.check_si571, self.check_ics854s01i)
        MainWindow.setTabOrder(self.check_ics854s01i, self.check_ad9510)
        MainWindow.setTabOrder(self.check_ad9510, self.check_sensor_temperatura)
        MainWindow.setTabOrder(self.check_sensor_temperatura, self.check_all)
        MainWindow.setTabOrder(self.check_all, self.checkGravarFPGA)
        MainWindow.setTabOrder(self.checkGravarFPGA, self.checkUtilizarMATLAB)
        MainWindow.setTabOrder(self.checkUtilizarMATLAB, self.checkGraficos)
        MainWindow.setTabOrder(self.checkGraficos, self.START_BUTTON)
        MainWindow.setTabOrder(self.START_BUTTON, self.STOP_BUTTON)
        MainWindow.setTabOrder(self.STOP_BUTTON, self.dateTimeEdit_MainScreen)
        MainWindow.setTabOrder(self.dateTimeEdit_MainScreen, self.OPERADOR)
        MainWindow.setTabOrder(self.OPERADOR, self.N_SERIE_ADC)
        MainWindow.setTabOrder(self.N_SERIE_ADC, self.ad9510_pll_function_config)
        MainWindow.setTabOrder(self.ad9510_pll_function_config, self.ad9510_pll_clock_sel_config)
        MainWindow.setTabOrder(self.ad9510_pll_clock_sel_config, self.ad9510_pll_clock_sel_ref_config)
        MainWindow.setTabOrder(self.ad9510_pll_clock_sel_ref_config, self.ad9510_a_divider_config)
        MainWindow.setTabOrder(self.ad9510_a_divider_config, self.ad9510_b_divider_config)
        MainWindow.setTabOrder(self.ad9510_b_divider_config, self.ad9510_r_divider_config)
        MainWindow.setTabOrder(self.ad9510_r_divider_config, self.ad9510_prescaler_config)
        MainWindow.setTabOrder(self.ad9510_prescaler_config, self.ad9510_pll_powerdown_config)
        MainWindow.setTabOrder(self.ad9510_pll_powerdown_config, self.ad9510_current_config)
        MainWindow.setTabOrder(self.ad9510_current_config, self.ad9510_outputs_config)
        MainWindow.setTabOrder(self.ad9510_outputs_config, self.si571_freq_config)
        MainWindow.setTabOrder(self.si571_freq_config, self.si571_output_config)
        MainWindow.setTabOrder(self.si571_output_config, self.communication_config)
        MainWindow.setTabOrder(self.communication_config, self.result_config)
        MainWindow.setTabOrder(self.result_config, self.CONFIG_BUTTON)
        MainWindow.setTabOrder(self.CONFIG_BUTTON, self.tabWidget)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Teste do Conversor AD", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>Antes de iniciar o teste, favor confirmar os parâmetros da simulação abaixo.</p><p>Após isso, clique em INICIAR TESTE</p></body></html>", None))
        self.START_BUTTON.setText(_translate("MainWindow", "Iniciar Teste", None))
        self.STOP_BUTTON.setText(_translate("MainWindow", "Sair", None))
        self.checkGraficos.setText(_translate("MainWindow", "Habilitar Gráficos", None))
        self.checkGravarFPGA.setText(_translate("MainWindow", "Gravar FPGA", None))
        self.checkUtilizarMATLAB.setText(_translate("MainWindow", "Utilizar MATLAB", None))
        self.OPERADOR.setText(_translate("MainWindow", "Fernando", None))
        self.N_SERIE_ADC.setText(_translate("MainWindow", "1111111", None))
        self.label_34.setText(_translate("MainWindow", "Operador", None))
        self.label_35.setText(_translate("MainWindow", "N. Série ADC", None))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">TESTES A SEREM REALIZADOS</span></p></body></html>", None))
        self.check_enob.setText(_translate("MainWindow", "ENOB", None))
        self.check_sfdr.setText(_translate("MainWindow", "SFDR", None))
        self.check_crosstalk.setText(_translate("MainWindow", "CROSSTALK", None))
        self.check_missingcodes.setText(_translate("MainWindow", "MISSING CODES", None))
        self.check_all.setText(_translate("MainWindow", "TODOS", None))
        self.check_dif_ampl.setText(_translate("MainWindow", "DIFERENÇA AMPL.", None))
        self.check_snr.setText(_translate("MainWindow", "SNR", None))
        self.check_eeprom.setText(_translate("MainWindow", "EEPROM", None))
        self.check_ics854s01i.setText(_translate("MainWindow", "ICS854S01I", None))
        self.check_sensor_temperatura.setText(_translate("MainWindow", "SENSOR TEMP.", None))
        self.check_ad9510.setText(_translate("MainWindow", "AD9510", None))
        self.check_si571.setText(_translate("MainWindow", "Si571", None))
        self.label_17.setText(_translate("MainWindow", "SFDR [ dBFS] >=", None))
        self.label_18.setText(_translate("MainWindow", "CROSSTALK [dBFS] >", None))
        self.label_16.setText(_translate("MainWindow", "ENOB [bits] >=", None))
        self.label_15.setText(_translate("MainWindow", "SNR [dBFS] >=", None))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">PARÂMETROS DE CRITÉRIO DE APROVAÇÃO</span></p></body></html>", None))
        self.label_22.setText(_translate("MainWindow", "MISSING CODE:", None))
        self.MISSINGCODE_CRITERIO.setText(_translate("MainWindow", "0", None))
        self.ENOB_CRITERIO.setText(_translate("MainWindow", "10", None))
        self.SFDR_CRITERIO.setText(_translate("MainWindow", "65", None))
        self.SNR_CRITERIO.setText(_translate("MainWindow", "50", None))
        self.CROSSTALK_CRITERIO.setText(_translate("MainWindow", "100", None))
        self.label_25.setText(_translate("MainWindow", "DIFERENÇA AMPL. [dB]:", None))
        self.DIF_AMPL_CRITERIO.setText(_translate("MainWindow", "0.001", None))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">PAR. DO SINAL DE CLOCK/ENTRADA</span></p><p align=\"center\"><span style=\" font-weight:600;\">(Missing Codes)</span></p></body></html>", None))
        self.label_27.setText(_translate("MainWindow", "FREQ. DO SINAL ENT. [MHz]", None))
        self.label_28.setText(_translate("MainWindow", "AMP. DO CLOCK [dBm]", None))
        self.AMP_IN_MISSINGCODES.setText(_translate("MainWindow", "9.5", None))
        self.AMP_CLOCK_MISSINGCODES.setText(_translate("MainWindow", "5", None))
        self.FREQ_CLOCK_MISSINGCODES.setText(_translate("MainWindow", "118.226944", None))
        self.FREQ_IN_MISSINGCODES.setText(_translate("MainWindow", "472.909580", None))
        self.label_29.setText(_translate("MainWindow", "AMP.  DO SINAL DE ENT. [dBm]", None))
        self.label_30.setText(_translate("MainWindow", "FREQ. DO SINAL CLOCK [MHz]", None))
        self.label_31.setText(_translate("MainWindow", "PERDA NO FILTRO [dBm]", None))
        self.PERDA_FILTRO_MISSINGCODES.setText(_translate("MainWindow", "2", None))
        self.label_14.setText(_translate("MainWindow", "IP DO CRATE", None))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">PARÂMETROS DO SINAL DE CLOCK/ENTRADA</span></p></body></html>", None))
        self.label_8.setText(_translate("MainWindow", "FREQUÊNCIA DO SINAL DE ENTRADA [MHz]", None))
        self.label_7.setText(_translate("MainWindow", "AMPLITUDE DO CLOCK [dBm]", None))
        self.AMP_IN.setText(_translate("MainWindow", "9.5", None))
        self.AMP_CLOCK.setText(_translate("MainWindow", "5", None))
        self.FREQ_CLOCK.setText(_translate("MainWindow", "118.23", None))
        self.FREQ_IN.setText(_translate("MainWindow", "499.944", None))
        self.label_9.setText(_translate("MainWindow", "AMPLITUDE DO SINAL DE ENTRADA [dBm]", None))
        self.label_3.setText(_translate("MainWindow", "IP DA CHAVE DE RF (SWITCH)", None))
        self.label_5.setText(_translate("MainWindow", "FREQUÊNCIA DO CLOCK [MHz]", None))
        self.label_4.setText(_translate("MainWindow", "IP DO GERADOR DE SINAIS (CLOCK)", None))
        self.label_12.setText(_translate("MainWindow", "POSIÇÃO DO AFC NO CRATE (de 1 a 7)", None))
        self.label_13.setText(_translate("MainWindow", "POSIÇÃO DO AD NO AFC (1 ou 0)", None))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">PARÂMETROS DE COMUNICAÇÃO</span></p></body></html>", None))
        self.POSICAO_AD.setText(_translate("MainWindow", "1", None))
        self.POSICAO_AFC.setText(_translate("MainWindow", "3", None))
        self.IP_SWITCH.setText(_translate("MainWindow", "10.0.18.15", None))
        self.IP_CRATE.setText(_translate("MainWindow", "10.0.18.18", None))
        self.IP_GERADOR_SINAIS_CLOCK.setText(_translate("MainWindow", "10.0.18.17", None))
        self.IP_GERADOR_SINAIS_INPUT.setText(_translate("MainWindow", "10.0.18.12", None))
        self.label_24.setText(_translate("MainWindow", "IP DO GERADOR DE SINAIS (SINAL ENT)", None))
        self.label_33.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt;\">* SNR, SFDR, ENOB, CROSSTALK, DIF. AMP.</span></p><p><span style=\" font-size:7pt;\">** SNR, SFDR, ENOB, CROSSTALK</span></p><p><span style=\" font-size:7pt;\"/></p></body></html>", None))
        self.label_6.setText(_translate("MainWindow", "Nº DE PTS DE FFT *", None))
        self.label_11.setText(_translate("MainWindow", "Nº DE PTS DO CRATE *", None))
        self.label_10.setText(_translate("MainWindow", "Nº DE REQUISIÇÕES ** ", None))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">PARÂMETROS DE PRECISÃO DA SIMULAÇÃO</span></p></body></html>", None))
        self.N_FFT.setText(_translate("MainWindow", "99995", None))
        self.N_CRATE.setText(_translate("MainWindow", "100000", None))
        self.N_REQUISICOES.setText(_translate("MainWindow", "1", None))
        self.label_32.setText(_translate("MainWindow", "Nº DE PTS DO CRATE (MIS. CODES)", None))
        self.N_CRATE_MISSINGCODES.setText(_translate("MainWindow", "1000000", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Test_Config), _translate("MainWindow", "Test Configuration", None))
        self.ad9510_pll_function_config.setText(_translate("MainWindow", "1", None))
        self.label_36.setText(_translate("MainWindow", "<html><head/><body><p>PLL Function [ Pin [0 | 1] ]</p></body></html>", None))
        self.label_37.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">PARÂMETROS DE CONFIGURAÇÃO DO AD9510</span></p></body></html>", None))
        self.label_39.setText(_translate("MainWindow", "<html><head/><body><p>PLL Clock Selection [ CLOCK [1 | 2] ]</p></body></html>", None))
        self.ad9510_pll_clock_sel_config.setText(_translate("MainWindow", "2", None))
        self.label_40.setText(_translate("MainWindow", "A Divider", None))
        self.ad9510_a_divider_config.setText(_translate("MainWindow", "0", None))
        self.label_41.setText(_translate("MainWindow", "B Divider", None))
        self.ad9510_b_divider_config.setText(_translate("MainWindow", "130", None))
        self.label_42.setText(_translate("MainWindow", "R Divider", None))
        self.ad9510_r_divider_config.setText(_translate("MainWindow", "37", None))
        self.label_43.setText(_translate("MainWindow", "Prescaler", None))
        self.ad9510_prescaler_config.setText(_translate("MainWindow", "0", None))
        self.label_44.setText(_translate("MainWindow", "<html><head/><body><p>PLL Power Down [ 0 | 1 | 2 | 3 ] *</p></body></html>", None))
        self.ad9510_pll_powerdown_config.setText(_translate("MainWindow", "0", None))
        self.label_45.setText(_translate("MainWindow", "Charge Pump  Current [600|1200|...|4800]  [uA]", None))
        self.ad9510_current_config.setText(_translate("MainWindow", "600", None))
        self.label_46.setText(_translate("MainWindow", "<html><head/><body><p>PLL Clock Sel. Ref. [ External Source [0] | FMC Pin [1] ]</p></body></html>", None))
        self.ad9510_pll_clock_sel_ref_config.setText(_translate("MainWindow", "1", None))
        self.label_48.setText(_translate("MainWindow", "<html><head/><body><p>Outputs [Disable [0] | Enable [1] ]</p></body></html>", None))
        self.ad9510_outputs_config.setText(_translate("MainWindow", "1", None))
        self.label_58.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">PARÂMETROS DE CONFIGURAÇÃO DO Si571</span></p></body></html>", None))
        self.label_59.setText(_translate("MainWindow", "Frequência [Hz]", None))
        self.label_60.setText(_translate("MainWindow", "Output [Disable[0] | Enable[1]]", None))
        self.si571_freq_config.setText(_translate("MainWindow", "113040445", None))
        self.si571_output_config.setText(_translate("MainWindow", "1", None))
        self.label_61.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">RESULTADO</span></p></body></html>", None))
        self.label_47.setText(_translate("MainWindow", "Resultado da Configuração", None))
        self.label_51.setText(_translate("MainWindow", "<html><head/><body><p>Status da Comunicação</p></body></html>", None))
        self.label_62.setText(_translate("MainWindow", "<html><head/><body><p>Informe os parâmetros para configuração dos CIs AD9510 e Si571.</p><p>Após informado, pressione o botão CONFIGURAR.</p></body></html>", None))
        self.CONFIG_BUTTON.setText(_translate("MainWindow", "Configurar", None))
        self.label_49.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt;\">*[0] Normal Operation 1; [1] Asynchronous power-down; </span></p></body></html>", None))
        self.label_50.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt;\">[2] Normal Operation 2; [3] Synchronous power-down.</span></p></body></html>", None))
        self.all_config_check.setText(_translate("MainWindow", "Realizar Todas as Configurações", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ADC_Config), _translate("MainWindow", "CIs Configuration", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

