# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_resultado_final.ui'
#
# Created: Tue Jan 31 10:36:17 2017
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(817, 628)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(50, 50, 741, 511))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Tab_SNR = QtGui.QWidget()
        self.Tab_SNR.setObjectName(_fromUtf8("Tab_SNR"))
        self.label_25 = QtGui.QLabel(self.Tab_SNR)
        self.label_25.setGeometry(QtCore.QRect(260, 70, 141, 21))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.Tab_SNR)
        self.label_26.setGeometry(QtCore.QRect(0, 20, 741, 20))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.line_3 = QtGui.QFrame(self.Tab_SNR)
        self.line_3.setGeometry(QtCore.QRect(0, 120, 741, 16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.label_28 = QtGui.QLabel(self.Tab_SNR)
        self.label_28.setGeometry(QtCore.QRect(0, 150, 741, 16))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.line_4 = QtGui.QFrame(self.Tab_SNR)
        self.line_4.setGeometry(QtCore.QRect(0, 300, 741, 16))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.label_29 = QtGui.QLabel(self.Tab_SNR)
        self.label_29.setGeometry(QtCore.QRect(0, 330, 741, 16))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.SNR_RESULT_CH1 = QtGui.QLineEdit(self.Tab_SNR)
        self.SNR_RESULT_CH1.setGeometry(QtCore.QRect(110, 400, 121, 26))
        self.SNR_RESULT_CH1.setObjectName(_fromUtf8("SNR_RESULT_CH1"))
        self.label_30 = QtGui.QLabel(self.Tab_SNR)
        self.label_30.setGeometry(QtCore.QRect(109, 370, 121, 26))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.SNR_RESULT_CH2 = QtGui.QLineEdit(self.Tab_SNR)
        self.SNR_RESULT_CH2.setGeometry(QtCore.QRect(260, 400, 121, 26))
        self.SNR_RESULT_CH2.setObjectName(_fromUtf8("SNR_RESULT_CH2"))
        self.label_31 = QtGui.QLabel(self.Tab_SNR)
        self.label_31.setGeometry(QtCore.QRect(259, 370, 121, 26))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.SNR_RESULT_CH3 = QtGui.QLineEdit(self.Tab_SNR)
        self.SNR_RESULT_CH3.setGeometry(QtCore.QRect(400, 400, 121, 26))
        self.SNR_RESULT_CH3.setObjectName(_fromUtf8("SNR_RESULT_CH3"))
        self.label_32 = QtGui.QLabel(self.Tab_SNR)
        self.label_32.setGeometry(QtCore.QRect(399, 370, 121, 26))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.SNR_RESULT_CH4 = QtGui.QLineEdit(self.Tab_SNR)
        self.SNR_RESULT_CH4.setGeometry(QtCore.QRect(540, 400, 121, 26))
        self.SNR_RESULT_CH4.setObjectName(_fromUtf8("SNR_RESULT_CH4"))
        self.label_33 = QtGui.QLabel(self.Tab_SNR)
        self.label_33.setGeometry(QtCore.QRect(539, 370, 121, 26))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.SNR_VALOR_MEDIDO_CH3 = QtGui.QLineEdit(self.Tab_SNR)
        self.SNR_VALOR_MEDIDO_CH3.setGeometry(QtCore.QRect(401, 230, 121, 26))
        self.SNR_VALOR_MEDIDO_CH3.setObjectName(_fromUtf8("SNR_VALOR_MEDIDO_CH3"))
        self.SNR_VALOR_MEDIDO_CH1 = QtGui.QLineEdit(self.Tab_SNR)
        self.SNR_VALOR_MEDIDO_CH1.setGeometry(QtCore.QRect(111, 230, 121, 26))
        self.SNR_VALOR_MEDIDO_CH1.setObjectName(_fromUtf8("SNR_VALOR_MEDIDO_CH1"))
        self.label_34 = QtGui.QLabel(self.Tab_SNR)
        self.label_34.setGeometry(QtCore.QRect(260, 200, 121, 26))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.SNR_VALOR_MEDIDO_CH2 = QtGui.QLineEdit(self.Tab_SNR)
        self.SNR_VALOR_MEDIDO_CH2.setGeometry(QtCore.QRect(261, 230, 121, 26))
        self.SNR_VALOR_MEDIDO_CH2.setObjectName(_fromUtf8("SNR_VALOR_MEDIDO_CH2"))
        self.label_35 = QtGui.QLabel(self.Tab_SNR)
        self.label_35.setGeometry(QtCore.QRect(540, 200, 121, 26))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.label_36 = QtGui.QLabel(self.Tab_SNR)
        self.label_36.setGeometry(QtCore.QRect(110, 200, 121, 26))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.SNR_VALOR_MEDIDO_CH4 = QtGui.QLineEdit(self.Tab_SNR)
        self.SNR_VALOR_MEDIDO_CH4.setGeometry(QtCore.QRect(541, 230, 121, 26))
        self.SNR_VALOR_MEDIDO_CH4.setObjectName(_fromUtf8("SNR_VALOR_MEDIDO_CH4"))
        self.label_37 = QtGui.QLabel(self.Tab_SNR)
        self.label_37.setGeometry(QtCore.QRect(400, 200, 121, 26))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.SNR_CRITERIO = QtGui.QLineEdit(self.Tab_SNR)
        self.SNR_CRITERIO.setGeometry(QtCore.QRect(400, 70, 121, 26))
        self.SNR_CRITERIO.setObjectName(_fromUtf8("SNR_CRITERIO"))
        self.tabWidget.addTab(self.Tab_SNR, _fromUtf8(""))
        self.Tab_ENOB = QtGui.QWidget()
        self.Tab_ENOB.setObjectName(_fromUtf8("Tab_ENOB"))
        self.label_38 = QtGui.QLabel(self.Tab_ENOB)
        self.label_38.setGeometry(QtCore.QRect(0, 20, 741, 20))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.label_39 = QtGui.QLabel(self.Tab_ENOB)
        self.label_39.setGeometry(QtCore.QRect(252, 60, 121, 21))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.ENOB_CRITERIO = QtGui.QLineEdit(self.Tab_ENOB)
        self.ENOB_CRITERIO.setGeometry(QtCore.QRect(390, 60, 112, 26))
        self.ENOB_CRITERIO.setObjectName(_fromUtf8("ENOB_CRITERIO"))
        self.line_5 = QtGui.QFrame(self.Tab_ENOB)
        self.line_5.setGeometry(QtCore.QRect(0, 100, 741, 16))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.label_40 = QtGui.QLabel(self.Tab_ENOB)
        self.label_40.setGeometry(QtCore.QRect(0, 130, 741, 16))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.label_41 = QtGui.QLabel(self.Tab_ENOB)
        self.label_41.setGeometry(QtCore.QRect(50, 170, 121, 26))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.ENOB_VALOR_MEDIDO_CH1 = QtGui.QLineEdit(self.Tab_ENOB)
        self.ENOB_VALOR_MEDIDO_CH1.setGeometry(QtCore.QRect(51, 200, 121, 26))
        self.ENOB_VALOR_MEDIDO_CH1.setObjectName(_fromUtf8("ENOB_VALOR_MEDIDO_CH1"))
        self.ENOB_VALOR_MEDIDO_CH2 = QtGui.QLineEdit(self.Tab_ENOB)
        self.ENOB_VALOR_MEDIDO_CH2.setGeometry(QtCore.QRect(222, 200, 121, 26))
        self.ENOB_VALOR_MEDIDO_CH2.setObjectName(_fromUtf8("ENOB_VALOR_MEDIDO_CH2"))
        self.label_42 = QtGui.QLabel(self.Tab_ENOB)
        self.label_42.setGeometry(QtCore.QRect(221, 170, 121, 26))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.ENOB_VALOR_MEDIDO_CH3 = QtGui.QLineEdit(self.Tab_ENOB)
        self.ENOB_VALOR_MEDIDO_CH3.setGeometry(QtCore.QRect(392, 200, 121, 26))
        self.ENOB_VALOR_MEDIDO_CH3.setObjectName(_fromUtf8("ENOB_VALOR_MEDIDO_CH3"))
        self.label_43 = QtGui.QLabel(self.Tab_ENOB)
        self.label_43.setGeometry(QtCore.QRect(391, 170, 121, 26))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.ENOB_VALOR_MEDIDO_CH4 = QtGui.QLineEdit(self.Tab_ENOB)
        self.ENOB_VALOR_MEDIDO_CH4.setGeometry(QtCore.QRect(561, 200, 121, 26))
        self.ENOB_VALOR_MEDIDO_CH4.setObjectName(_fromUtf8("ENOB_VALOR_MEDIDO_CH4"))
        self.label_44 = QtGui.QLabel(self.Tab_ENOB)
        self.label_44.setGeometry(QtCore.QRect(560, 170, 121, 26))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.ENOB_RESULT_CH3 = QtGui.QLineEdit(self.Tab_ENOB)
        self.ENOB_RESULT_CH3.setGeometry(QtCore.QRect(391, 360, 121, 26))
        self.ENOB_RESULT_CH3.setObjectName(_fromUtf8("ENOB_RESULT_CH3"))
        self.label_45 = QtGui.QLabel(self.Tab_ENOB)
        self.label_45.setGeometry(QtCore.QRect(559, 330, 121, 26))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.ENOB_RESULT_CH4 = QtGui.QLineEdit(self.Tab_ENOB)
        self.ENOB_RESULT_CH4.setGeometry(QtCore.QRect(560, 360, 121, 26))
        self.ENOB_RESULT_CH4.setObjectName(_fromUtf8("ENOB_RESULT_CH4"))
        self.label_46 = QtGui.QLabel(self.Tab_ENOB)
        self.label_46.setGeometry(QtCore.QRect(-1, 300, 741, 16))
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.ENOB_RESULT_CH1 = QtGui.QLineEdit(self.Tab_ENOB)
        self.ENOB_RESULT_CH1.setGeometry(QtCore.QRect(50, 360, 121, 26))
        self.ENOB_RESULT_CH1.setObjectName(_fromUtf8("ENOB_RESULT_CH1"))
        self.label_47 = QtGui.QLabel(self.Tab_ENOB)
        self.label_47.setGeometry(QtCore.QRect(49, 330, 121, 26))
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.line_6 = QtGui.QFrame(self.Tab_ENOB)
        self.line_6.setGeometry(QtCore.QRect(0, 270, 741, 16))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.label_48 = QtGui.QLabel(self.Tab_ENOB)
        self.label_48.setGeometry(QtCore.QRect(390, 330, 121, 26))
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.ENOB_RESULT_CH2 = QtGui.QLineEdit(self.Tab_ENOB)
        self.ENOB_RESULT_CH2.setGeometry(QtCore.QRect(221, 360, 121, 26))
        self.ENOB_RESULT_CH2.setObjectName(_fromUtf8("ENOB_RESULT_CH2"))
        self.label_49 = QtGui.QLabel(self.Tab_ENOB)
        self.label_49.setGeometry(QtCore.QRect(220, 330, 121, 26))
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.tabWidget.addTab(self.Tab_ENOB, _fromUtf8(""))
        self.Tab_SFDR = QtGui.QWidget()
        self.Tab_SFDR.setObjectName(_fromUtf8("Tab_SFDR"))
        self.line_7 = QtGui.QFrame(self.Tab_SFDR)
        self.line_7.setGeometry(QtCore.QRect(0, 130, 741, 16))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.label_51 = QtGui.QLabel(self.Tab_SFDR)
        self.label_51.setGeometry(QtCore.QRect(230, 60, 141, 31))
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.label_52 = QtGui.QLabel(self.Tab_SFDR)
        self.label_52.setGeometry(QtCore.QRect(0, 20, 741, 20))
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.SFDR_CRITERIO = QtGui.QLineEdit(self.Tab_SFDR)
        self.SFDR_CRITERIO.setGeometry(QtCore.QRect(388, 60, 112, 26))
        self.SFDR_CRITERIO.setObjectName(_fromUtf8("SFDR_CRITERIO"))
        self.label_54 = QtGui.QLabel(self.Tab_SFDR)
        self.label_54.setGeometry(QtCore.QRect(0, 150, 741, 16))
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.label_60 = QtGui.QLabel(self.Tab_SFDR)
        self.label_60.setGeometry(QtCore.QRect(0, 340, 741, 16))
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.SFDR_RESULT_CH2 = QtGui.QLineEdit(self.Tab_SFDR)
        self.SFDR_RESULT_CH2.setGeometry(QtCore.QRect(260, 400, 121, 26))
        self.SFDR_RESULT_CH2.setObjectName(_fromUtf8("SFDR_RESULT_CH2"))
        self.SFDR_RESULT_CH1 = QtGui.QLineEdit(self.Tab_SFDR)
        self.SFDR_RESULT_CH1.setGeometry(QtCore.QRect(110, 400, 121, 26))
        self.SFDR_RESULT_CH1.setObjectName(_fromUtf8("SFDR_RESULT_CH1"))
        self.SFDR_RESULT_CH4 = QtGui.QLineEdit(self.Tab_SFDR)
        self.SFDR_RESULT_CH4.setGeometry(QtCore.QRect(540, 400, 121, 26))
        self.SFDR_RESULT_CH4.setObjectName(_fromUtf8("SFDR_RESULT_CH4"))
        self.line_8 = QtGui.QFrame(self.Tab_SFDR)
        self.line_8.setGeometry(QtCore.QRect(0, 320, 741, 16))
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.SFDR_RESULT_CH3 = QtGui.QLineEdit(self.Tab_SFDR)
        self.SFDR_RESULT_CH3.setGeometry(QtCore.QRect(400, 400, 121, 26))
        self.SFDR_RESULT_CH3.setObjectName(_fromUtf8("SFDR_RESULT_CH3"))
        self.label_61 = QtGui.QLabel(self.Tab_SFDR)
        self.label_61.setGeometry(QtCore.QRect(260, 370, 121, 26))
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.label_62 = QtGui.QLabel(self.Tab_SFDR)
        self.label_62.setGeometry(QtCore.QRect(540, 370, 121, 26))
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.label_63 = QtGui.QLabel(self.Tab_SFDR)
        self.label_63.setGeometry(QtCore.QRect(110, 370, 121, 26))
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.label_64 = QtGui.QLabel(self.Tab_SFDR)
        self.label_64.setGeometry(QtCore.QRect(400, 370, 121, 26))
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.label_187 = QtGui.QLabel(self.Tab_SFDR)
        self.label_187.setGeometry(QtCore.QRect(110, 200, 121, 26))
        self.label_187.setObjectName(_fromUtf8("label_187"))
        self.label_188 = QtGui.QLabel(self.Tab_SFDR)
        self.label_188.setGeometry(QtCore.QRect(400, 200, 121, 26))
        self.label_188.setObjectName(_fromUtf8("label_188"))
        self.SFDR_VALOR_MEDIDO_CH4 = QtGui.QLineEdit(self.Tab_SFDR)
        self.SFDR_VALOR_MEDIDO_CH4.setGeometry(QtCore.QRect(540, 230, 121, 26))
        self.SFDR_VALOR_MEDIDO_CH4.setObjectName(_fromUtf8("SFDR_VALOR_MEDIDO_CH4"))
        self.SFDR_VALOR_MEDIDO_CH1 = QtGui.QLineEdit(self.Tab_SFDR)
        self.SFDR_VALOR_MEDIDO_CH1.setGeometry(QtCore.QRect(110, 230, 121, 26))
        self.SFDR_VALOR_MEDIDO_CH1.setObjectName(_fromUtf8("SFDR_VALOR_MEDIDO_CH1"))
        self.label_189 = QtGui.QLabel(self.Tab_SFDR)
        self.label_189.setGeometry(QtCore.QRect(260, 200, 121, 26))
        self.label_189.setObjectName(_fromUtf8("label_189"))
        self.SFDR_VALOR_MEDIDO_CH2 = QtGui.QLineEdit(self.Tab_SFDR)
        self.SFDR_VALOR_MEDIDO_CH2.setGeometry(QtCore.QRect(260, 230, 121, 26))
        self.SFDR_VALOR_MEDIDO_CH2.setObjectName(_fromUtf8("SFDR_VALOR_MEDIDO_CH2"))
        self.SFDR_VALOR_MEDIDO_CH3 = QtGui.QLineEdit(self.Tab_SFDR)
        self.SFDR_VALOR_MEDIDO_CH3.setGeometry(QtCore.QRect(400, 230, 121, 26))
        self.SFDR_VALOR_MEDIDO_CH3.setObjectName(_fromUtf8("SFDR_VALOR_MEDIDO_CH3"))
        self.label_190 = QtGui.QLabel(self.Tab_SFDR)
        self.label_190.setGeometry(QtCore.QRect(540, 200, 121, 26))
        self.label_190.setObjectName(_fromUtf8("label_190"))
        self.tabWidget.addTab(self.Tab_SFDR, _fromUtf8(""))
        self.Tab_Crosstalk = QtGui.QWidget()
        self.Tab_Crosstalk.setObjectName(_fromUtf8("Tab_Crosstalk"))
        self.label_50 = QtGui.QLabel(self.Tab_Crosstalk)
        self.label_50.setGeometry(QtCore.QRect(243, 60, 131, 21))
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.label_65 = QtGui.QLabel(self.Tab_Crosstalk)
        self.label_65.setGeometry(QtCore.QRect(140, 140, 121, 26))
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.label_66 = QtGui.QLabel(self.Tab_Crosstalk)
        self.label_66.setGeometry(QtCore.QRect(1, 20, 741, 20))
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.label_67 = QtGui.QLabel(self.Tab_Crosstalk)
        self.label_67.setGeometry(QtCore.QRect(221, 370, 121, 26))
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.label_68 = QtGui.QLabel(self.Tab_Crosstalk)
        self.label_68.setGeometry(QtCore.QRect(1, 120, 741, 16))
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.label_69 = QtGui.QLabel(self.Tab_Crosstalk)
        self.label_69.setGeometry(QtCore.QRect(50, 370, 121, 26))
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.CROSSTALK_RESULT_CH4 = QtGui.QLineEdit(self.Tab_Crosstalk)
        self.CROSSTALK_RESULT_CH4.setGeometry(QtCore.QRect(561, 400, 121, 26))
        self.CROSSTALK_RESULT_CH4.setObjectName(_fromUtf8("CROSSTALK_RESULT_CH4"))
        self.CROSSTALK_VALOR_MEDIDO_CH1_3 = QtGui.QLineEdit(self.Tab_Crosstalk)
        self.CROSSTALK_VALOR_MEDIDO_CH1_3.setGeometry(QtCore.QRect(401, 160, 121, 26))
        self.CROSSTALK_VALOR_MEDIDO_CH1_3.setObjectName(_fromUtf8("CROSSTALK_VALOR_MEDIDO_CH1_3"))
        self.label_70 = QtGui.QLabel(self.Tab_Crosstalk)
        self.label_70.setGeometry(QtCore.QRect(270, 140, 121, 26))
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.CROSSTALK_VALOR_MEDIDO_CH1_1 = QtGui.QLineEdit(self.Tab_Crosstalk)
        self.CROSSTALK_VALOR_MEDIDO_CH1_1.setGeometry(QtCore.QRect(141, 160, 121, 26))
        self.CROSSTALK_VALOR_MEDIDO_CH1_1.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.CROSSTALK_VALOR_MEDIDO_CH1_1.setObjectName(_fromUtf8("CROSSTALK_VALOR_MEDIDO_CH1_1"))
        self.label_71 = QtGui.QLabel(self.Tab_Crosstalk)
        self.label_71.setGeometry(QtCore.QRect(391, 370, 121, 26))
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.CROSSTALK_RESULT_CH2 = QtGui.QLineEdit(self.Tab_Crosstalk)
        self.CROSSTALK_RESULT_CH2.setGeometry(QtCore.QRect(222, 400, 121, 26))
        self.CROSSTALK_RESULT_CH2.setObjectName(_fromUtf8("CROSSTALK_RESULT_CH2"))
        self.label_72 = QtGui.QLabel(self.Tab_Crosstalk)
        self.label_72.setGeometry(QtCore.QRect(400, 140, 121, 26))
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.CROSSTALK_CRITERIO = QtGui.QLineEdit(self.Tab_Crosstalk)
        self.CROSSTALK_CRITERIO.setGeometry(QtCore.QRect(391, 60, 112, 26))
        self.CROSSTALK_CRITERIO.setObjectName(_fromUtf8("CROSSTALK_CRITERIO"))
        self.label_73 = QtGui.QLabel(self.Tab_Crosstalk)
        self.label_73.setGeometry(QtCore.QRect(560, 370, 121, 26))
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.CROSSTALK_RESULT_CH3 = QtGui.QLineEdit(self.Tab_Crosstalk)
        self.CROSSTALK_RESULT_CH3.setGeometry(QtCore.QRect(392, 400, 121, 26))
        self.CROSSTALK_RESULT_CH3.setObjectName(_fromUtf8("CROSSTALK_RESULT_CH3"))
        self.CROSSTALK_VALOR_MEDIDO_CH1_2 = QtGui.QLineEdit(self.Tab_Crosstalk)
        self.CROSSTALK_VALOR_MEDIDO_CH1_2.setGeometry(QtCore.QRect(271, 160, 121, 26))
        self.CROSSTALK_VALOR_MEDIDO_CH1_2.setObjectName(_fromUtf8("CROSSTALK_VALOR_MEDIDO_CH1_2"))
        self.CROSSTALK_RESULT_CH1 = QtGui.QLineEdit(self.Tab_Crosstalk)
        self.CROSSTALK_RESULT_CH1.setGeometry(QtCore.QRect(51, 400, 121, 26))
        self.CROSSTALK_RESULT_CH1.setObjectName(_fromUtf8("CROSSTALK_RESULT_CH1"))
        self.label_75 = QtGui.QLabel(self.Tab_Crosstalk)
        self.label_75.setGeometry(QtCore.QRect(0, 340, 731, 16))
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.line_9 = QtGui.QFrame(self.Tab_Crosstalk)
        self.line_9.setGeometry(QtCore.QRect(-1, 320, 741, 16))
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.line_10 = QtGui.QFrame(self.Tab_Crosstalk)
        self.line_10.setGeometry(QtCore.QRect(0, 100, 741, 16))
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.label_83 = QtGui.QLabel(self.Tab_Crosstalk)
        self.label_83.setGeometry(QtCore.QRect(70, 160, 61, 26))
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.CROSSTALK_VALOR_MEDIDO_CH2_3 = QtGui.QLineEdit(self.Tab_Crosstalk)
        self.CROSSTALK_VALOR_MEDIDO_CH2_3.setGeometry(QtCore.QRect(401, 200, 121, 26))
        self.CROSSTALK_VALOR_MEDIDO_CH2_3.setObjectName(_fromUtf8("CROSSTALK_VALOR_MEDIDO_CH2_3"))
        self.CROSSTALK_VALOR_MEDIDO_CH2_2 = QtGui.QLineEdit(self.Tab_Crosstalk)
        self.CROSSTALK_VALOR_MEDIDO_CH2_2.setGeometry(QtCore.QRect(271, 200, 121, 26))
        self.CROSSTALK_VALOR_MEDIDO_CH2_2.setObjectName(_fromUtf8("CROSSTALK_VALOR_MEDIDO_CH2_2"))
        self.CROSSTALK_VALOR_MEDIDO_CH2_1 = QtGui.QLineEdit(self.Tab_Crosstalk)
        self.CROSSTALK_VALOR_MEDIDO_CH2_1.setGeometry(QtCore.QRect(141, 200, 121, 26))
        self.CROSSTALK_VALOR_MEDIDO_CH2_1.setObjectName(_fromUtf8("CROSSTALK_VALOR_MEDIDO_CH2_1"))
        self.CROSSTALK_VALOR_MEDIDO_CH3_3 = QtGui.QLineEdit(self.Tab_Crosstalk)
        self.CROSSTALK_VALOR_MEDIDO_CH3_3.setGeometry(QtCore.QRect(401, 240, 121, 26))
        self.CROSSTALK_VALOR_MEDIDO_CH3_3.setObjectName(_fromUtf8("CROSSTALK_VALOR_MEDIDO_CH3_3"))
        self.CROSSTALK_VALOR_MEDIDO_CH3_2 = QtGui.QLineEdit(self.Tab_Crosstalk)
        self.CROSSTALK_VALOR_MEDIDO_CH3_2.setGeometry(QtCore.QRect(271, 240, 121, 26))
        self.CROSSTALK_VALOR_MEDIDO_CH3_2.setObjectName(_fromUtf8("CROSSTALK_VALOR_MEDIDO_CH3_2"))
        self.CROSSTALK_VALOR_MEDIDO_CH3_1 = QtGui.QLineEdit(self.Tab_Crosstalk)
        self.CROSSTALK_VALOR_MEDIDO_CH3_1.setGeometry(QtCore.QRect(141, 240, 121, 26))
        self.CROSSTALK_VALOR_MEDIDO_CH3_1.setObjectName(_fromUtf8("CROSSTALK_VALOR_MEDIDO_CH3_1"))
        self.CROSSTALK_VALOR_MEDIDO_CH4_3 = QtGui.QLineEdit(self.Tab_Crosstalk)
        self.CROSSTALK_VALOR_MEDIDO_CH4_3.setGeometry(QtCore.QRect(401, 280, 121, 26))
        self.CROSSTALK_VALOR_MEDIDO_CH4_3.setObjectName(_fromUtf8("CROSSTALK_VALOR_MEDIDO_CH4_3"))
        self.CROSSTALK_VALOR_MEDIDO_CH4_2 = QtGui.QLineEdit(self.Tab_Crosstalk)
        self.CROSSTALK_VALOR_MEDIDO_CH4_2.setGeometry(QtCore.QRect(271, 280, 121, 26))
        self.CROSSTALK_VALOR_MEDIDO_CH4_2.setObjectName(_fromUtf8("CROSSTALK_VALOR_MEDIDO_CH4_2"))
        self.CROSSTALK_VALOR_MEDIDO_CH4_1 = QtGui.QLineEdit(self.Tab_Crosstalk)
        self.CROSSTALK_VALOR_MEDIDO_CH4_1.setGeometry(QtCore.QRect(141, 280, 121, 26))
        self.CROSSTALK_VALOR_MEDIDO_CH4_1.setObjectName(_fromUtf8("CROSSTALK_VALOR_MEDIDO_CH4_1"))
        self.label_98 = QtGui.QLabel(self.Tab_Crosstalk)
        self.label_98.setGeometry(QtCore.QRect(70, 200, 61, 26))
        self.label_98.setObjectName(_fromUtf8("label_98"))
        self.label_102 = QtGui.QLabel(self.Tab_Crosstalk)
        self.label_102.setGeometry(QtCore.QRect(70, 240, 61, 26))
        self.label_102.setObjectName(_fromUtf8("label_102"))
        self.label_107 = QtGui.QLabel(self.Tab_Crosstalk)
        self.label_107.setGeometry(QtCore.QRect(70, 280, 61, 26))
        self.label_107.setObjectName(_fromUtf8("label_107"))
        self.CROSSTALK_VALOR_MEDIDO_CH1_4 = QtGui.QLineEdit(self.Tab_Crosstalk)
        self.CROSSTALK_VALOR_MEDIDO_CH1_4.setGeometry(QtCore.QRect(530, 160, 121, 26))
        self.CROSSTALK_VALOR_MEDIDO_CH1_4.setObjectName(_fromUtf8("CROSSTALK_VALOR_MEDIDO_CH1_4"))
        self.CROSSTALK_VALOR_MEDIDO_CH4_4 = QtGui.QLineEdit(self.Tab_Crosstalk)
        self.CROSSTALK_VALOR_MEDIDO_CH4_4.setGeometry(QtCore.QRect(530, 280, 121, 26))
        self.CROSSTALK_VALOR_MEDIDO_CH4_4.setObjectName(_fromUtf8("CROSSTALK_VALOR_MEDIDO_CH4_4"))
        self.CROSSTALK_VALOR_MEDIDO_CH3_4 = QtGui.QLineEdit(self.Tab_Crosstalk)
        self.CROSSTALK_VALOR_MEDIDO_CH3_4.setGeometry(QtCore.QRect(530, 240, 121, 26))
        self.CROSSTALK_VALOR_MEDIDO_CH3_4.setObjectName(_fromUtf8("CROSSTALK_VALOR_MEDIDO_CH3_4"))
        self.CROSSTALK_VALOR_MEDIDO_CH2_4 = QtGui.QLineEdit(self.Tab_Crosstalk)
        self.CROSSTALK_VALOR_MEDIDO_CH2_4.setGeometry(QtCore.QRect(530, 200, 121, 26))
        self.CROSSTALK_VALOR_MEDIDO_CH2_4.setObjectName(_fromUtf8("CROSSTALK_VALOR_MEDIDO_CH2_4"))
        self.label_74 = QtGui.QLabel(self.Tab_Crosstalk)
        self.label_74.setGeometry(QtCore.QRect(530, 140, 121, 26))
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.tabWidget.addTab(self.Tab_Crosstalk, _fromUtf8(""))
        self.Tab_Missingcodes = QtGui.QWidget()
        self.Tab_Missingcodes.setObjectName(_fromUtf8("Tab_Missingcodes"))
        self.line_13 = QtGui.QFrame(self.Tab_Missingcodes)
        self.line_13.setGeometry(QtCore.QRect(0, 130, 741, 16))
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.label_89 = QtGui.QLabel(self.Tab_Missingcodes)
        self.label_89.setGeometry(QtCore.QRect(0, 160, 741, 16))
        self.label_89.setObjectName(_fromUtf8("label_89"))
        self.line_14 = QtGui.QFrame(self.Tab_Missingcodes)
        self.line_14.setGeometry(QtCore.QRect(0, 320, 741, 16))
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.label_90 = QtGui.QLabel(self.Tab_Missingcodes)
        self.label_90.setGeometry(QtCore.QRect(540, 370, 121, 26))
        self.label_90.setObjectName(_fromUtf8("label_90"))
        self.label_91 = QtGui.QLabel(self.Tab_Missingcodes)
        self.label_91.setGeometry(QtCore.QRect(110, 370, 121, 26))
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.label_92 = QtGui.QLabel(self.Tab_Missingcodes)
        self.label_92.setGeometry(QtCore.QRect(400, 370, 121, 26))
        self.label_92.setObjectName(_fromUtf8("label_92"))
        self.MISSINGCODE_RESULT_CH4 = QtGui.QLineEdit(self.Tab_Missingcodes)
        self.MISSINGCODE_RESULT_CH4.setGeometry(QtCore.QRect(540, 400, 121, 26))
        self.MISSINGCODE_RESULT_CH4.setObjectName(_fromUtf8("MISSINGCODE_RESULT_CH4"))
        self.label_93 = QtGui.QLabel(self.Tab_Missingcodes)
        self.label_93.setGeometry(QtCore.QRect(0, 340, 741, 16))
        self.label_93.setObjectName(_fromUtf8("label_93"))
        self.MISSINGCODE_RESULT_CH1 = QtGui.QLineEdit(self.Tab_Missingcodes)
        self.MISSINGCODE_RESULT_CH1.setGeometry(QtCore.QRect(110, 400, 121, 26))
        self.MISSINGCODE_RESULT_CH1.setObjectName(_fromUtf8("MISSINGCODE_RESULT_CH1"))
        self.label_94 = QtGui.QLabel(self.Tab_Missingcodes)
        self.label_94.setGeometry(QtCore.QRect(260, 370, 121, 26))
        self.label_94.setObjectName(_fromUtf8("label_94"))
        self.MISSINGCODE_RESULT_CH2 = QtGui.QLineEdit(self.Tab_Missingcodes)
        self.MISSINGCODE_RESULT_CH2.setGeometry(QtCore.QRect(260, 400, 121, 26))
        self.MISSINGCODE_RESULT_CH2.setObjectName(_fromUtf8("MISSINGCODE_RESULT_CH2"))
        self.MISSINGCODE_RESULT_CH3 = QtGui.QLineEdit(self.Tab_Missingcodes)
        self.MISSINGCODE_RESULT_CH3.setGeometry(QtCore.QRect(400, 400, 121, 26))
        self.MISSINGCODE_RESULT_CH3.setObjectName(_fromUtf8("MISSINGCODE_RESULT_CH3"))
        self.MISSINGCODES_CRITERIO = QtGui.QLineEdit(self.Tab_Missingcodes)
        self.MISSINGCODES_CRITERIO.setGeometry(QtCore.QRect(370, 50, 112, 26))
        self.MISSINGCODES_CRITERIO.setObjectName(_fromUtf8("MISSINGCODES_CRITERIO"))
        self.label_53 = QtGui.QLabel(self.Tab_Missingcodes)
        self.label_53.setGeometry(QtCore.QRect(0, 20, 741, 20))
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.label_55 = QtGui.QLabel(self.Tab_Missingcodes)
        self.label_55.setGeometry(QtCore.QRect(260, 50, 101, 31))
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.label_191 = QtGui.QLabel(self.Tab_Missingcodes)
        self.label_191.setGeometry(QtCore.QRect(540, 210, 121, 26))
        self.label_191.setObjectName(_fromUtf8("label_191"))
        self.label_192 = QtGui.QLabel(self.Tab_Missingcodes)
        self.label_192.setGeometry(QtCore.QRect(400, 210, 121, 26))
        self.label_192.setObjectName(_fromUtf8("label_192"))
        self.MISSINGCODE_VALOR_MEDIDO_CH4 = QtGui.QLineEdit(self.Tab_Missingcodes)
        self.MISSINGCODE_VALOR_MEDIDO_CH4.setGeometry(QtCore.QRect(540, 240, 121, 26))
        self.MISSINGCODE_VALOR_MEDIDO_CH4.setObjectName(_fromUtf8("MISSINGCODE_VALOR_MEDIDO_CH4"))
        self.MISSINGCODE_VALOR_MEDIDO_CH3 = QtGui.QLineEdit(self.Tab_Missingcodes)
        self.MISSINGCODE_VALOR_MEDIDO_CH3.setGeometry(QtCore.QRect(400, 240, 121, 26))
        self.MISSINGCODE_VALOR_MEDIDO_CH3.setObjectName(_fromUtf8("MISSINGCODE_VALOR_MEDIDO_CH3"))
        self.MISSINGCODE_VALOR_MEDIDO_CH2 = QtGui.QLineEdit(self.Tab_Missingcodes)
        self.MISSINGCODE_VALOR_MEDIDO_CH2.setGeometry(QtCore.QRect(260, 240, 121, 26))
        self.MISSINGCODE_VALOR_MEDIDO_CH2.setObjectName(_fromUtf8("MISSINGCODE_VALOR_MEDIDO_CH2"))
        self.label_193 = QtGui.QLabel(self.Tab_Missingcodes)
        self.label_193.setGeometry(QtCore.QRect(260, 210, 121, 26))
        self.label_193.setObjectName(_fromUtf8("label_193"))
        self.label_194 = QtGui.QLabel(self.Tab_Missingcodes)
        self.label_194.setGeometry(QtCore.QRect(110, 210, 121, 26))
        self.label_194.setObjectName(_fromUtf8("label_194"))
        self.MISSINGCODE_VALOR_MEDIDO_CH1 = QtGui.QLineEdit(self.Tab_Missingcodes)
        self.MISSINGCODE_VALOR_MEDIDO_CH1.setGeometry(QtCore.QRect(110, 240, 121, 26))
        self.MISSINGCODE_VALOR_MEDIDO_CH1.setObjectName(_fromUtf8("MISSINGCODE_VALOR_MEDIDO_CH1"))
        self.MISSINGCODES_RANGE_MINIMO = QtGui.QLineEdit(self.Tab_Missingcodes)
        self.MISSINGCODES_RANGE_MINIMO.setGeometry(QtCore.QRect(350, 100, 112, 26))
        self.MISSINGCODES_RANGE_MINIMO.setObjectName(_fromUtf8("MISSINGCODES_RANGE_MINIMO"))
        self.label_96 = QtGui.QLabel(self.Tab_Missingcodes)
        self.label_96.setGeometry(QtCore.QRect(140, 100, 201, 31))
        self.label_96.setObjectName(_fromUtf8("label_96"))
        self.MISSINGCODES_RANGE_MAXIMO = QtGui.QLineEdit(self.Tab_Missingcodes)
        self.MISSINGCODES_RANGE_MAXIMO.setGeometry(QtCore.QRect(470, 100, 112, 26))
        self.MISSINGCODES_RANGE_MAXIMO.setObjectName(_fromUtf8("MISSINGCODES_RANGE_MAXIMO"))
        self.tabWidget.addTab(self.Tab_Missingcodes, _fromUtf8(""))
        self.Tab_Dif_Amp = QtGui.QWidget()
        self.Tab_Dif_Amp.setObjectName(_fromUtf8("Tab_Dif_Amp"))
        self.label_97 = QtGui.QLabel(self.Tab_Dif_Amp)
        self.label_97.setGeometry(QtCore.QRect(0, 20, 741, 20))
        self.label_97.setObjectName(_fromUtf8("label_97"))
        self.line_15 = QtGui.QFrame(self.Tab_Dif_Amp)
        self.line_15.setGeometry(QtCore.QRect(0, 130, 741, 16))
        self.line_15.setFrameShape(QtGui.QFrame.HLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName(_fromUtf8("line_15"))
        self.line_16 = QtGui.QFrame(self.Tab_Dif_Amp)
        self.line_16.setGeometry(QtCore.QRect(0, 300, 741, 16))
        self.line_16.setFrameShape(QtGui.QFrame.HLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName(_fromUtf8("line_16"))
        self.label_105 = QtGui.QLabel(self.Tab_Dif_Amp)
        self.label_105.setGeometry(QtCore.QRect(0, 330, 741, 16))
        self.label_105.setObjectName(_fromUtf8("label_105"))
        self.label_82 = QtGui.QLabel(self.Tab_Dif_Amp)
        self.label_82.setGeometry(QtCore.QRect(0, 160, 741, 16))
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.label_84 = QtGui.QLabel(self.Tab_Dif_Amp)
        self.label_84.setGeometry(QtCore.QRect(250, 360, 61, 26))
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.DIF_AMP_VALOR_MEDIDO_CH1CH3_1 = QtGui.QLineEdit(self.Tab_Dif_Amp)
        self.DIF_AMP_VALOR_MEDIDO_CH1CH3_1.setGeometry(QtCore.QRect(80, 240, 51, 26))
        self.DIF_AMP_VALOR_MEDIDO_CH1CH3_1.setObjectName(_fromUtf8("DIF_AMP_VALOR_MEDIDO_CH1CH3_1"))
        self.DIF_AMPL_CRITERIO = QtGui.QLineEdit(self.Tab_Dif_Amp)
        self.DIF_AMPL_CRITERIO.setGeometry(QtCore.QRect(380, 80, 112, 26))
        self.DIF_AMPL_CRITERIO.setObjectName(_fromUtf8("DIF_AMPL_CRITERIO"))
        self.label_88 = QtGui.QLabel(self.Tab_Dif_Amp)
        self.label_88.setGeometry(QtCore.QRect(250, 400, 61, 26))
        self.label_88.setObjectName(_fromUtf8("label_88"))
        self.label_56 = QtGui.QLabel(self.Tab_Dif_Amp)
        self.label_56.setGeometry(QtCore.QRect(232, 80, 131, 21))
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.label_99 = QtGui.QLabel(self.Tab_Dif_Amp)
        self.label_99.setGeometry(QtCore.QRect(80, 190, 51, 26))
        self.label_99.setObjectName(_fromUtf8("label_99"))
        self.DIF_AMP_RESULT_CH2CH4 = QtGui.QLineEdit(self.Tab_Dif_Amp)
        self.DIF_AMP_RESULT_CH2CH4.setGeometry(QtCore.QRect(320, 400, 121, 26))
        self.DIF_AMP_RESULT_CH2CH4.setObjectName(_fromUtf8("DIF_AMP_RESULT_CH2CH4"))
        self.DIF_AMP_RESULT_CH1CH3 = QtGui.QLineEdit(self.Tab_Dif_Amp)
        self.DIF_AMP_RESULT_CH1CH3.setGeometry(QtCore.QRect(320, 360, 121, 26))
        self.DIF_AMP_RESULT_CH1CH3.setObjectName(_fromUtf8("DIF_AMP_RESULT_CH1CH3"))
        self.label_85 = QtGui.QLabel(self.Tab_Dif_Amp)
        self.label_85.setGeometry(QtCore.QRect(10, 240, 51, 26))
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.label_100 = QtGui.QLabel(self.Tab_Dif_Amp)
        self.label_100.setGeometry(QtCore.QRect(140, 190, 51, 26))
        self.label_100.setObjectName(_fromUtf8("label_100"))
        self.DIF_AMP_VALOR_MEDIDO_CH1CH3_2 = QtGui.QLineEdit(self.Tab_Dif_Amp)
        self.DIF_AMP_VALOR_MEDIDO_CH1CH3_2.setGeometry(QtCore.QRect(140, 240, 51, 26))
        self.DIF_AMP_VALOR_MEDIDO_CH1CH3_2.setObjectName(_fromUtf8("DIF_AMP_VALOR_MEDIDO_CH1CH3_2"))
        self.label_101 = QtGui.QLabel(self.Tab_Dif_Amp)
        self.label_101.setGeometry(QtCore.QRect(200, 190, 51, 26))
        self.label_101.setObjectName(_fromUtf8("label_101"))
        self.DIF_AMP_VALOR_MEDIDO_CH1CH3_3 = QtGui.QLineEdit(self.Tab_Dif_Amp)
        self.DIF_AMP_VALOR_MEDIDO_CH1CH3_3.setGeometry(QtCore.QRect(200, 240, 51, 26))
        self.DIF_AMP_VALOR_MEDIDO_CH1CH3_3.setObjectName(_fromUtf8("DIF_AMP_VALOR_MEDIDO_CH1CH3_3"))
        self.label_103 = QtGui.QLabel(self.Tab_Dif_Amp)
        self.label_103.setGeometry(QtCore.QRect(260, 190, 51, 26))
        self.label_103.setObjectName(_fromUtf8("label_103"))
        self.DIF_AMP_VALOR_MEDIDO_CH1CH3_4 = QtGui.QLineEdit(self.Tab_Dif_Amp)
        self.DIF_AMP_VALOR_MEDIDO_CH1CH3_4.setGeometry(QtCore.QRect(260, 240, 51, 26))
        self.DIF_AMP_VALOR_MEDIDO_CH1CH3_4.setObjectName(_fromUtf8("DIF_AMP_VALOR_MEDIDO_CH1CH3_4"))
        self.label_104 = QtGui.QLabel(self.Tab_Dif_Amp)
        self.label_104.setGeometry(QtCore.QRect(320, 190, 51, 26))
        self.label_104.setObjectName(_fromUtf8("label_104"))
        self.DIF_AMP_VALOR_MEDIDO_CH1CH3_5 = QtGui.QLineEdit(self.Tab_Dif_Amp)
        self.DIF_AMP_VALOR_MEDIDO_CH1CH3_5.setGeometry(QtCore.QRect(320, 240, 51, 26))
        self.DIF_AMP_VALOR_MEDIDO_CH1CH3_5.setObjectName(_fromUtf8("DIF_AMP_VALOR_MEDIDO_CH1CH3_5"))
        self.label_106 = QtGui.QLabel(self.Tab_Dif_Amp)
        self.label_106.setGeometry(QtCore.QRect(380, 190, 51, 26))
        self.label_106.setObjectName(_fromUtf8("label_106"))
        self.DIF_AMP_VALOR_MEDIDO_CH1CH3_6 = QtGui.QLineEdit(self.Tab_Dif_Amp)
        self.DIF_AMP_VALOR_MEDIDO_CH1CH3_6.setGeometry(QtCore.QRect(380, 240, 51, 26))
        self.DIF_AMP_VALOR_MEDIDO_CH1CH3_6.setObjectName(_fromUtf8("DIF_AMP_VALOR_MEDIDO_CH1CH3_6"))
        self.label_108 = QtGui.QLabel(self.Tab_Dif_Amp)
        self.label_108.setGeometry(QtCore.QRect(440, 190, 51, 26))
        self.label_108.setObjectName(_fromUtf8("label_108"))
        self.DIF_AMP_VALOR_MEDIDO_CH1CH3_7 = QtGui.QLineEdit(self.Tab_Dif_Amp)
        self.DIF_AMP_VALOR_MEDIDO_CH1CH3_7.setGeometry(QtCore.QRect(440, 240, 51, 26))
        self.DIF_AMP_VALOR_MEDIDO_CH1CH3_7.setObjectName(_fromUtf8("DIF_AMP_VALOR_MEDIDO_CH1CH3_7"))
        self.label_109 = QtGui.QLabel(self.Tab_Dif_Amp)
        self.label_109.setGeometry(QtCore.QRect(500, 190, 51, 26))
        self.label_109.setObjectName(_fromUtf8("label_109"))
        self.DIF_AMP_VALOR_MEDIDO_CH1CH3_8 = QtGui.QLineEdit(self.Tab_Dif_Amp)
        self.DIF_AMP_VALOR_MEDIDO_CH1CH3_8.setGeometry(QtCore.QRect(500, 240, 51, 26))
        self.DIF_AMP_VALOR_MEDIDO_CH1CH3_8.setObjectName(_fromUtf8("DIF_AMP_VALOR_MEDIDO_CH1CH3_8"))
        self.label_110 = QtGui.QLabel(self.Tab_Dif_Amp)
        self.label_110.setGeometry(QtCore.QRect(560, 190, 51, 26))
        self.label_110.setObjectName(_fromUtf8("label_110"))
        self.DIF_AMP_VALOR_MEDIDO_CH1CH3_9 = QtGui.QLineEdit(self.Tab_Dif_Amp)
        self.DIF_AMP_VALOR_MEDIDO_CH1CH3_9.setGeometry(QtCore.QRect(560, 240, 51, 26))
        self.DIF_AMP_VALOR_MEDIDO_CH1CH3_9.setObjectName(_fromUtf8("DIF_AMP_VALOR_MEDIDO_CH1CH3_9"))
        self.label_111 = QtGui.QLabel(self.Tab_Dif_Amp)
        self.label_111.setGeometry(QtCore.QRect(620, 190, 51, 26))
        self.label_111.setObjectName(_fromUtf8("label_111"))
        self.DIF_AMP_VALOR_MEDIDO_CH1CH3_10 = QtGui.QLineEdit(self.Tab_Dif_Amp)
        self.DIF_AMP_VALOR_MEDIDO_CH1CH3_10.setGeometry(QtCore.QRect(620, 240, 51, 26))
        self.DIF_AMP_VALOR_MEDIDO_CH1CH3_10.setObjectName(_fromUtf8("DIF_AMP_VALOR_MEDIDO_CH1CH3_10"))
        self.DIF_AMP_VALOR_MEDIDO_CH1CH3_11 = QtGui.QLineEdit(self.Tab_Dif_Amp)
        self.DIF_AMP_VALOR_MEDIDO_CH1CH3_11.setGeometry(QtCore.QRect(680, 240, 51, 26))
        self.DIF_AMP_VALOR_MEDIDO_CH1CH3_11.setObjectName(_fromUtf8("DIF_AMP_VALOR_MEDIDO_CH1CH3_11"))
        self.label_112 = QtGui.QLabel(self.Tab_Dif_Amp)
        self.label_112.setGeometry(QtCore.QRect(680, 190, 51, 26))
        self.label_112.setObjectName(_fromUtf8("label_112"))
        self.label_86 = QtGui.QLabel(self.Tab_Dif_Amp)
        self.label_86.setGeometry(QtCore.QRect(10, 190, 61, 26))
        self.label_86.setObjectName(_fromUtf8("label_86"))
        self.label_87 = QtGui.QLabel(self.Tab_Dif_Amp)
        self.label_87.setGeometry(QtCore.QRect(10, 270, 51, 26))
        self.label_87.setObjectName(_fromUtf8("label_87"))
        self.DIF_AMP_VALOR_MEDIDO_CH2CH4_1 = QtGui.QLineEdit(self.Tab_Dif_Amp)
        self.DIF_AMP_VALOR_MEDIDO_CH2CH4_1.setGeometry(QtCore.QRect(80, 270, 51, 26))
        self.DIF_AMP_VALOR_MEDIDO_CH2CH4_1.setObjectName(_fromUtf8("DIF_AMP_VALOR_MEDIDO_CH2CH4_1"))
        self.label_113 = QtGui.QLabel(self.Tab_Dif_Amp)
        self.label_113.setGeometry(QtCore.QRect(260, 210, 51, 26))
        self.label_113.setObjectName(_fromUtf8("label_113"))
        self.label_114 = QtGui.QLabel(self.Tab_Dif_Amp)
        self.label_114.setGeometry(QtCore.QRect(80, 210, 51, 26))
        self.label_114.setObjectName(_fromUtf8("label_114"))
        self.label_115 = QtGui.QLabel(self.Tab_Dif_Amp)
        self.label_115.setGeometry(QtCore.QRect(500, 210, 51, 26))
        self.label_115.setObjectName(_fromUtf8("label_115"))
        self.label_116 = QtGui.QLabel(self.Tab_Dif_Amp)
        self.label_116.setGeometry(QtCore.QRect(140, 210, 51, 26))
        self.label_116.setObjectName(_fromUtf8("label_116"))
        self.label_117 = QtGui.QLabel(self.Tab_Dif_Amp)
        self.label_117.setGeometry(QtCore.QRect(620, 210, 51, 26))
        self.label_117.setObjectName(_fromUtf8("label_117"))
        self.label_118 = QtGui.QLabel(self.Tab_Dif_Amp)
        self.label_118.setGeometry(QtCore.QRect(200, 210, 51, 26))
        self.label_118.setObjectName(_fromUtf8("label_118"))
        self.label_119 = QtGui.QLabel(self.Tab_Dif_Amp)
        self.label_119.setGeometry(QtCore.QRect(380, 210, 51, 26))
        self.label_119.setObjectName(_fromUtf8("label_119"))
        self.label_120 = QtGui.QLabel(self.Tab_Dif_Amp)
        self.label_120.setGeometry(QtCore.QRect(440, 210, 51, 26))
        self.label_120.setObjectName(_fromUtf8("label_120"))
        self.label_121 = QtGui.QLabel(self.Tab_Dif_Amp)
        self.label_121.setGeometry(QtCore.QRect(320, 210, 51, 26))
        self.label_121.setObjectName(_fromUtf8("label_121"))
        self.label_122 = QtGui.QLabel(self.Tab_Dif_Amp)
        self.label_122.setGeometry(QtCore.QRect(560, 210, 51, 26))
        self.label_122.setObjectName(_fromUtf8("label_122"))
        self.label_95 = QtGui.QLabel(self.Tab_Dif_Amp)
        self.label_95.setGeometry(QtCore.QRect(10, 210, 61, 26))
        self.label_95.setObjectName(_fromUtf8("label_95"))
        self.label_123 = QtGui.QLabel(self.Tab_Dif_Amp)
        self.label_123.setGeometry(QtCore.QRect(680, 210, 51, 26))
        self.label_123.setObjectName(_fromUtf8("label_123"))
        self.DIF_AMP_VALOR_MEDIDO_CH2CH4_2 = QtGui.QLineEdit(self.Tab_Dif_Amp)
        self.DIF_AMP_VALOR_MEDIDO_CH2CH4_2.setGeometry(QtCore.QRect(140, 270, 51, 26))
        self.DIF_AMP_VALOR_MEDIDO_CH2CH4_2.setObjectName(_fromUtf8("DIF_AMP_VALOR_MEDIDO_CH2CH4_2"))
        self.DIF_AMP_VALOR_MEDIDO_CH2CH4_3 = QtGui.QLineEdit(self.Tab_Dif_Amp)
        self.DIF_AMP_VALOR_MEDIDO_CH2CH4_3.setGeometry(QtCore.QRect(200, 270, 51, 26))
        self.DIF_AMP_VALOR_MEDIDO_CH2CH4_3.setObjectName(_fromUtf8("DIF_AMP_VALOR_MEDIDO_CH2CH4_3"))
        self.DIF_AMP_VALOR_MEDIDO_CH2CH4_4 = QtGui.QLineEdit(self.Tab_Dif_Amp)
        self.DIF_AMP_VALOR_MEDIDO_CH2CH4_4.setGeometry(QtCore.QRect(260, 270, 51, 26))
        self.DIF_AMP_VALOR_MEDIDO_CH2CH4_4.setObjectName(_fromUtf8("DIF_AMP_VALOR_MEDIDO_CH2CH4_4"))
        self.DIF_AMP_VALOR_MEDIDO_CH2CH4_5 = QtGui.QLineEdit(self.Tab_Dif_Amp)
        self.DIF_AMP_VALOR_MEDIDO_CH2CH4_5.setGeometry(QtCore.QRect(320, 270, 51, 26))
        self.DIF_AMP_VALOR_MEDIDO_CH2CH4_5.setObjectName(_fromUtf8("DIF_AMP_VALOR_MEDIDO_CH2CH4_5"))
        self.DIF_AMP_VALOR_MEDIDO_CH2CH4_6 = QtGui.QLineEdit(self.Tab_Dif_Amp)
        self.DIF_AMP_VALOR_MEDIDO_CH2CH4_6.setGeometry(QtCore.QRect(380, 270, 51, 26))
        self.DIF_AMP_VALOR_MEDIDO_CH2CH4_6.setObjectName(_fromUtf8("DIF_AMP_VALOR_MEDIDO_CH2CH4_6"))
        self.DIF_AMP_VALOR_MEDIDO_CH2CH4_7 = QtGui.QLineEdit(self.Tab_Dif_Amp)
        self.DIF_AMP_VALOR_MEDIDO_CH2CH4_7.setGeometry(QtCore.QRect(440, 270, 51, 26))
        self.DIF_AMP_VALOR_MEDIDO_CH2CH4_7.setObjectName(_fromUtf8("DIF_AMP_VALOR_MEDIDO_CH2CH4_7"))
        self.DIF_AMP_VALOR_MEDIDO_CH2CH4_8 = QtGui.QLineEdit(self.Tab_Dif_Amp)
        self.DIF_AMP_VALOR_MEDIDO_CH2CH4_8.setGeometry(QtCore.QRect(500, 270, 51, 26))
        self.DIF_AMP_VALOR_MEDIDO_CH2CH4_8.setObjectName(_fromUtf8("DIF_AMP_VALOR_MEDIDO_CH2CH4_8"))
        self.DIF_AMP_VALOR_MEDIDO_CH2CH4_9 = QtGui.QLineEdit(self.Tab_Dif_Amp)
        self.DIF_AMP_VALOR_MEDIDO_CH2CH4_9.setGeometry(QtCore.QRect(560, 270, 51, 26))
        self.DIF_AMP_VALOR_MEDIDO_CH2CH4_9.setObjectName(_fromUtf8("DIF_AMP_VALOR_MEDIDO_CH2CH4_9"))
        self.DIF_AMP_VALOR_MEDIDO_CH2CH4_10 = QtGui.QLineEdit(self.Tab_Dif_Amp)
        self.DIF_AMP_VALOR_MEDIDO_CH2CH4_10.setGeometry(QtCore.QRect(620, 270, 51, 26))
        self.DIF_AMP_VALOR_MEDIDO_CH2CH4_10.setObjectName(_fromUtf8("DIF_AMP_VALOR_MEDIDO_CH2CH4_10"))
        self.DIF_AMP_VALOR_MEDIDO_CH2CH4_11 = QtGui.QLineEdit(self.Tab_Dif_Amp)
        self.DIF_AMP_VALOR_MEDIDO_CH2CH4_11.setGeometry(QtCore.QRect(680, 270, 51, 26))
        self.DIF_AMP_VALOR_MEDIDO_CH2CH4_11.setObjectName(_fromUtf8("DIF_AMP_VALOR_MEDIDO_CH2CH4_11"))
        self.tabWidget.addTab(self.Tab_Dif_Amp, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_124 = QtGui.QLabel(self.tab)
        self.label_124.setGeometry(QtCore.QRect(0, 40, 741, 20))
        self.label_124.setObjectName(_fromUtf8("label_124"))
        self.label_57 = QtGui.QLabel(self.tab)
        self.label_57.setGeometry(QtCore.QRect(72, 140, 131, 31))
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.EEPROM_WRITE_RESULT = QtGui.QLineEdit(self.tab)
        self.EEPROM_WRITE_RESULT.setGeometry(QtCore.QRect(220, 140, 112, 26))
        self.EEPROM_WRITE_RESULT.setObjectName(_fromUtf8("EEPROM_WRITE_RESULT"))
        self.SI571_WRITE_RESULT = QtGui.QLineEdit(self.tab)
        self.SI571_WRITE_RESULT.setGeometry(QtCore.QRect(218, 190, 112, 26))
        self.SI571_WRITE_RESULT.setObjectName(_fromUtf8("SI571_WRITE_RESULT"))
        self.label_58 = QtGui.QLabel(self.tab)
        self.label_58.setGeometry(QtCore.QRect(70, 190, 131, 31))
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.ICS854S01I_WRITE_RESULT = QtGui.QLineEdit(self.tab)
        self.ICS854S01I_WRITE_RESULT.setGeometry(QtCore.QRect(218, 240, 112, 26))
        self.ICS854S01I_WRITE_RESULT.setObjectName(_fromUtf8("ICS854S01I_WRITE_RESULT"))
        self.label_59 = QtGui.QLabel(self.tab)
        self.label_59.setGeometry(QtCore.QRect(70, 240, 131, 31))
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.AD9510_WRITE_RESULT = QtGui.QLineEdit(self.tab)
        self.AD9510_WRITE_RESULT.setGeometry(QtCore.QRect(218, 290, 112, 26))
        self.AD9510_WRITE_RESULT.setObjectName(_fromUtf8("AD9510_WRITE_RESULT"))
        self.label_76 = QtGui.QLabel(self.tab)
        self.label_76.setGeometry(QtCore.QRect(70, 290, 131, 31))
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.SENSOR_TEMP_WRITE_RESULT = QtGui.QLineEdit(self.tab)
        self.SENSOR_TEMP_WRITE_RESULT.setGeometry(QtCore.QRect(218, 340, 112, 26))
        self.SENSOR_TEMP_WRITE_RESULT.setObjectName(_fromUtf8("SENSOR_TEMP_WRITE_RESULT"))
        self.label_77 = QtGui.QLabel(self.tab)
        self.label_77.setGeometry(QtCore.QRect(70, 340, 131, 21))
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.label_78 = QtGui.QLabel(self.tab)
        self.label_78.setGeometry(QtCore.QRect(220, 100, 111, 31))
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.EEPROM_READ_RESULT = QtGui.QLineEdit(self.tab)
        self.EEPROM_READ_RESULT.setGeometry(QtCore.QRect(370, 140, 112, 26))
        self.EEPROM_READ_RESULT.setObjectName(_fromUtf8("EEPROM_READ_RESULT"))
        self.SI571_READ_RESULT = QtGui.QLineEdit(self.tab)
        self.SI571_READ_RESULT.setGeometry(QtCore.QRect(368, 190, 112, 26))
        self.SI571_READ_RESULT.setObjectName(_fromUtf8("SI571_READ_RESULT"))
        self.AD9510_READ_RESULT = QtGui.QLineEdit(self.tab)
        self.AD9510_READ_RESULT.setGeometry(QtCore.QRect(368, 290, 112, 26))
        self.AD9510_READ_RESULT.setObjectName(_fromUtf8("AD9510_READ_RESULT"))
        self.label_79 = QtGui.QLabel(self.tab)
        self.label_79.setGeometry(QtCore.QRect(370, 100, 111, 31))
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.SENSOR_TEMP_READ_RESULT = QtGui.QLineEdit(self.tab)
        self.SENSOR_TEMP_READ_RESULT.setGeometry(QtCore.QRect(368, 340, 112, 26))
        self.SENSOR_TEMP_READ_RESULT.setObjectName(_fromUtf8("SENSOR_TEMP_READ_RESULT"))
        self.ICS854S01I_READ_RESULT = QtGui.QLineEdit(self.tab)
        self.ICS854S01I_READ_RESULT.setGeometry(QtCore.QRect(368, 240, 112, 26))
        self.ICS854S01I_READ_RESULT.setObjectName(_fromUtf8("ICS854S01I_READ_RESULT"))
        self.ICS854S01I_RESULT_FINAL = QtGui.QLineEdit(self.tab)
        self.ICS854S01I_RESULT_FINAL.setGeometry(QtCore.QRect(520, 240, 112, 26))
        self.ICS854S01I_RESULT_FINAL.setObjectName(_fromUtf8("ICS854S01I_RESULT_FINAL"))
        self.SENSOR_TEMP_RESULT_FINAL = QtGui.QLineEdit(self.tab)
        self.SENSOR_TEMP_RESULT_FINAL.setGeometry(QtCore.QRect(520, 340, 112, 26))
        self.SENSOR_TEMP_RESULT_FINAL.setObjectName(_fromUtf8("SENSOR_TEMP_RESULT_FINAL"))
        self.SI571_RESULT_FINAL = QtGui.QLineEdit(self.tab)
        self.SI571_RESULT_FINAL.setGeometry(QtCore.QRect(520, 190, 112, 26))
        self.SI571_RESULT_FINAL.setObjectName(_fromUtf8("SI571_RESULT_FINAL"))
        self.EEPROM_RESULT_FINAL = QtGui.QLineEdit(self.tab)
        self.EEPROM_RESULT_FINAL.setGeometry(QtCore.QRect(522, 140, 112, 26))
        self.EEPROM_RESULT_FINAL.setObjectName(_fromUtf8("EEPROM_RESULT_FINAL"))
        self.label_80 = QtGui.QLabel(self.tab)
        self.label_80.setGeometry(QtCore.QRect(512, 100, 131, 31))
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.AD9510_RESULT_FINAL = QtGui.QLineEdit(self.tab)
        self.AD9510_RESULT_FINAL.setGeometry(QtCore.QRect(520, 290, 112, 26))
        self.AD9510_RESULT_FINAL.setObjectName(_fromUtf8("AD9510_RESULT_FINAL"))
        self.line = QtGui.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(70, 320, 591, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(70, 270, 591, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_11 = QtGui.QFrame(self.tab)
        self.line_11.setGeometry(QtCore.QRect(70, 220, 591, 20))
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.line_12 = QtGui.QFrame(self.tab)
        self.line_12.setGeometry(QtCore.QRect(70, 370, 590, 20))
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.line_17 = QtGui.QFrame(self.tab)
        self.line_17.setGeometry(QtCore.QRect(70, 170, 591, 20))
        self.line_17.setFrameShape(QtGui.QFrame.HLine)
        self.line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_17.setObjectName(_fromUtf8("line_17"))
        self.line_18 = QtGui.QFrame(self.tab)
        self.line_18.setGeometry(QtCore.QRect(70, 120, 591, 20))
        self.line_18.setFrameShape(QtGui.QFrame.HLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName(_fromUtf8("line_18"))
        self.line_19 = QtGui.QFrame(self.tab)
        self.line_19.setGeometry(QtCore.QRect(70, 90, 590, 20))
        self.line_19.setFrameShape(QtGui.QFrame.HLine)
        self.line_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_19.setObjectName(_fromUtf8("line_19"))
        self.line_20 = QtGui.QFrame(self.tab)
        self.line_20.setGeometry(QtCore.QRect(60, 100, 20, 280))
        self.line_20.setFrameShape(QtGui.QFrame.VLine)
        self.line_20.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_20.setObjectName(_fromUtf8("line_20"))
        self.line_21 = QtGui.QFrame(self.tab)
        self.line_21.setGeometry(QtCore.QRect(190, 100, 20, 280))
        self.line_21.setFrameShape(QtGui.QFrame.VLine)
        self.line_21.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_21.setObjectName(_fromUtf8("line_21"))
        self.line_22 = QtGui.QFrame(self.tab)
        self.line_22.setGeometry(QtCore.QRect(340, 100, 20, 280))
        self.line_22.setFrameShape(QtGui.QFrame.VLine)
        self.line_22.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_22.setObjectName(_fromUtf8("line_22"))
        self.line_23 = QtGui.QFrame(self.tab)
        self.line_23.setGeometry(QtCore.QRect(490, 100, 20, 280))
        self.line_23.setFrameShape(QtGui.QFrame.VLine)
        self.line_23.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_23.setObjectName(_fromUtf8("line_23"))
        self.line_24 = QtGui.QFrame(self.tab)
        self.line_24.setGeometry(QtCore.QRect(650, 100, 20, 280))
        self.line_24.setFrameShape(QtGui.QFrame.VLine)
        self.line_24.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_24.setObjectName(_fromUtf8("line_24"))
        self.label_81 = QtGui.QLabel(self.tab)
        self.label_81.setGeometry(QtCore.QRect(80, 100, 111, 31))
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.OK_BUTTON = QtGui.QPushButton(Dialog)
        self.OK_BUTTON.setGeometry(QtCore.QRect(680, 580, 87, 27))
        self.OK_BUTTON.setObjectName(_fromUtf8("OK_BUTTON"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 20, 94, 31))
        self.label.setObjectName(_fromUtf8("label"))
        self.dateTimeEdit_result = QtGui.QDateTimeEdit(Dialog)
        self.dateTimeEdit_result.setGeometry(QtCore.QRect(170, 20, 131, 26))
        self.dateTimeEdit_result.setWrapping(False)
        self.dateTimeEdit_result.setReadOnly(True)
        self.dateTimeEdit_result.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit_result.setObjectName(_fromUtf8("dateTimeEdit_result"))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Resultados - ADC", None))
        self.label_25.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Valor Mínimo [dBFS]:</p></body></html>", None))
        self.label_26.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Critério de Avaliação (Valor Absoluto)</span></p></body></html>", None))
        self.label_28.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Valores Medidos (Valor Absoluto) [dBFS]</span></p></body></html>", None))
        self.label_29.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Resultado Final</span></p></body></html>", None))
        self.label_30.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 1</p></body></html>", None))
        self.label_31.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 2</p></body></html>", None))
        self.label_32.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 3</p></body></html>", None))
        self.label_33.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 4</p></body></html>", None))
        self.label_34.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 2</p></body></html>", None))
        self.label_35.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 4</p></body></html>", None))
        self.label_36.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 1</p></body></html>", None))
        self.label_37.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 3</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_SNR), _translate("Dialog", "SNR", None))
        self.label_38.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Critério de Avaliação</span></p></body></html>", None))
        self.label_39.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Valor Mínimo [bits]:</p></body></html>", None))
        self.ENOB_CRITERIO.setText(_translate("Dialog", "teste", None))
        self.label_40.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Valores Medidos [bits]</span></p></body></html>", None))
        self.label_41.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 1</p></body></html>", None))
        self.label_42.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 2</p></body></html>", None))
        self.label_43.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 3</p></body></html>", None))
        self.label_44.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 4</p></body></html>", None))
        self.label_45.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 4</p></body></html>", None))
        self.label_46.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Resultado Final</span></p></body></html>", None))
        self.label_47.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 1</p></body></html>", None))
        self.label_48.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 3</p></body></html>", None))
        self.label_49.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 2</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_ENOB), _translate("Dialog", "ENOB", None))
        self.label_51.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Valor Mínimo [dBFS]:</p></body></html>", None))
        self.label_52.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Critério de Avaliação (Valor Absoluto)</span></p></body></html>", None))
        self.SFDR_CRITERIO.setText(_translate("Dialog", "4.8", None))
        self.label_54.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Valores Medidos (Valor Absoluto) [dBFS]</span></p></body></html>", None))
        self.label_60.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Resultado Final</span></p></body></html>", None))
        self.label_61.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 2</p></body></html>", None))
        self.label_62.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 4</p></body></html>", None))
        self.label_63.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 1</p></body></html>", None))
        self.label_64.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 3</p></body></html>", None))
        self.label_187.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 1</p></body></html>", None))
        self.label_188.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 3</p></body></html>", None))
        self.label_189.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 2</p></body></html>", None))
        self.label_190.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 4</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_SFDR), _translate("Dialog", "SFDR", None))
        self.label_50.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Valor Mínimo [dBFS]:</p></body></html>", None))
        self.label_65.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 1</p></body></html>", None))
        self.label_66.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Critério de Avaliação (Valor Absoluto)</span></p></body></html>", None))
        self.label_67.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 2</p></body></html>", None))
        self.label_68.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Valores Medidos (Valor Absoluto) [dBFS]</span></p></body></html>", None))
        self.label_69.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 1</p></body></html>", None))
        self.label_70.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 2</p></body></html>", None))
        self.CROSSTALK_VALOR_MEDIDO_CH1_1.setText(_translate("Dialog", "-", None))
        self.label_71.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 3</p></body></html>", None))
        self.label_72.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 3</p></body></html>", None))
        self.CROSSTALK_CRITERIO.setText(_translate("Dialog", "teste", None))
        self.label_73.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 4</p></body></html>", None))
        self.label_75.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Resultado Final</span></p></body></html>", None))
        self.label_83.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 1</p></body></html>", None))
        self.CROSSTALK_VALOR_MEDIDO_CH2_2.setText(_translate("Dialog", "-", None))
        self.CROSSTALK_VALOR_MEDIDO_CH3_3.setText(_translate("Dialog", "-", None))
        self.label_98.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 2</p></body></html>", None))
        self.label_102.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 3</p></body></html>", None))
        self.label_107.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 4</p></body></html>", None))
        self.CROSSTALK_VALOR_MEDIDO_CH4_4.setText(_translate("Dialog", "-", None))
        self.label_74.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 4</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_Crosstalk), _translate("Dialog", "CROSSTALK", None))
        self.label_89.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Valores Medidos (Número de Missing Codes)</span></p></body></html>", None))
        self.label_90.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 4</p></body></html>", None))
        self.label_91.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 1</p></body></html>", None))
        self.label_92.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 3</p></body></html>", None))
        self.label_93.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Resultado Final</span></p></body></html>", None))
        self.label_94.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 2</p></body></html>", None))
        self.MISSINGCODES_CRITERIO.setText(_translate("Dialog", "0", None))
        self.label_53.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Critério de Avaliação</span></p></body></html>", None))
        self.label_55.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Valor Máximo:</p></body></html>", None))
        self.label_191.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 4</p></body></html>", None))
        self.label_192.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 3</p></body></html>", None))
        self.label_193.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 2</p></body></html>", None))
        self.label_194.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Canal 1</p></body></html>", None))
        self.MISSINGCODES_RANGE_MINIMO.setText(_translate("Dialog", "0", None))
        self.label_96.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Range de Avaliação [Valores AD]:</p></body></html>", None))
        self.MISSINGCODES_RANGE_MAXIMO.setText(_translate("Dialog", "0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_Missingcodes), _translate("Dialog", "MISSING CODES", None))
        self.label_97.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Critério de Avaliação (Valor Absoluto)</span></p></body></html>", None))
        self.label_105.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Resultado Final</span></p></body></html>", None))
        self.label_82.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Valores Medidos (Valor Absoluto) [dB]</span></p></body></html>", None))
        self.label_84.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Ch 1-3</p></body></html>", None))
        self.DIF_AMPL_CRITERIO.setText(_translate("Dialog", "0.001", None))
        self.label_88.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Ch 2-4</p></body></html>", None))
        self.label_56.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Valor Máximo [dB]:</p></body></html>", None))
        self.label_99.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">-22.5</p></body></html>", None))
        self.label_85.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Ch 1-3</p></body></html>", None))
        self.label_100.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">-20.5</p></body></html>", None))
        self.label_101.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">-18.5</p></body></html>", None))
        self.label_103.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">-16.5</p></body></html>", None))
        self.label_104.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">-14.5</p></body></html>", None))
        self.label_106.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">-12.5</p></body></html>", None))
        self.label_108.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">-10.5</p></body></html>", None))
        self.label_109.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">-8.5</p></body></html>", None))
        self.label_110.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">-6.5</p></body></html>", None))
        self.label_111.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">-4.5</p></body></html>", None))
        self.label_112.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">-2.5</p></body></html>", None))
        self.label_86.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">In. [dBm]</p></body></html>", None))
        self.label_87.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Ch 2-4</p></body></html>", None))
        self.label_113.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">-24</p></body></html>", None))
        self.label_114.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">-30</p></body></html>", None))
        self.label_115.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">-16</p></body></html>", None))
        self.label_116.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">-28</p></body></html>", None))
        self.label_117.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">-12</p></body></html>", None))
        self.label_118.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">-26</p></body></html>", None))
        self.label_119.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">-20</p></body></html>", None))
        self.label_120.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">-18</p></body></html>", None))
        self.label_121.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">-22</p></body></html>", None))
        self.label_122.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">-14</p></body></html>", None))
        self.label_95.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">In. [dBFS]</p></body></html>", None))
        self.label_123.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">-10</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_Dif_Amp), _translate("Dialog", "DIF. AMP.", None))
        self.label_124.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Resultado Final</span></p></body></html>", None))
        self.label_57.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">EEPROM</p></body></html>", None))
        self.EEPROM_WRITE_RESULT.setText(_translate("Dialog", "-", None))
        self.SI571_WRITE_RESULT.setText(_translate("Dialog", "-", None))
        self.label_58.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Si571</p></body></html>", None))
        self.ICS854S01I_WRITE_RESULT.setText(_translate("Dialog", "-", None))
        self.label_59.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">ICS854S01I</p></body></html>", None))
        self.AD9510_WRITE_RESULT.setText(_translate("Dialog", "-", None))
        self.label_76.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">AD9510</p></body></html>", None))
        self.SENSOR_TEMP_WRITE_RESULT.setText(_translate("Dialog", "-", None))
        self.label_77.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">SENSOR DE TEMP.</p></body></html>", None))
        self.label_78.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">ESCRITA</span></p></body></html>", None))
        self.EEPROM_READ_RESULT.setText(_translate("Dialog", "-", None))
        self.SI571_READ_RESULT.setText(_translate("Dialog", "-", None))
        self.AD9510_READ_RESULT.setText(_translate("Dialog", "-", None))
        self.label_79.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">LEITURA</span></p></body></html>", None))
        self.SENSOR_TEMP_READ_RESULT.setText(_translate("Dialog", "-", None))
        self.ICS854S01I_READ_RESULT.setText(_translate("Dialog", "-", None))
        self.ICS854S01I_RESULT_FINAL.setText(_translate("Dialog", "-", None))
        self.SENSOR_TEMP_RESULT_FINAL.setText(_translate("Dialog", "-", None))
        self.SI571_RESULT_FINAL.setText(_translate("Dialog", "-", None))
        self.EEPROM_RESULT_FINAL.setText(_translate("Dialog", "-", None))
        self.label_80.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">RESULTADO FINAL</span></p></body></html>", None))
        self.AD9510_RESULT_FINAL.setText(_translate("Dialog", "-", None))
        self.label_81.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">COMPONENTE</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "COMPONENTES", None))
        self.OK_BUTTON.setText(_translate("Dialog", "OK", None))
        self.label.setText(_translate("Dialog", "Data Realizada:", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

