# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_principal_rffe.ui'
#
# Created: Fri Feb 24 11:23:47 2017
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1330, 683)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 501, 61))
        self.label.setObjectName(_fromUtf8("label"))
        self.START_BUTTON = QtGui.QPushButton(self.centralwidget)
        self.START_BUTTON.setGeometry(QtCore.QRect(1080, 630, 87, 27))
        self.START_BUTTON.setObjectName(_fromUtf8("START_BUTTON"))
        self.EXIT_BUTTON = QtGui.QPushButton(self.centralwidget)
        self.EXIT_BUTTON.setGeometry(QtCore.QRect(1170, 630, 87, 27))
        self.EXIT_BUTTON.setObjectName(_fromUtf8("EXIT_BUTTON"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 210, 191, 26))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(50, 240, 191, 26))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(50, 270, 191, 26))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(50, 150, 191, 26))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 90, 371, 221))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(0, 20, 371, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.IP_SWITCH_2 = QtGui.QLineEdit(self.frame)
        self.IP_SWITCH_2.setGeometry(QtCore.QRect(230, 90, 123, 26))
        self.IP_SWITCH_2.setObjectName(_fromUtf8("IP_SWITCH_2"))
        self.IP_GERADOR_SINAIS_DC = QtGui.QLineEdit(self.frame)
        self.IP_GERADOR_SINAIS_DC.setGeometry(QtCore.QRect(230, 150, 123, 26))
        self.IP_GERADOR_SINAIS_DC.setObjectName(_fromUtf8("IP_GERADOR_SINAIS_DC"))
        self.IP_RFFE = QtGui.QLineEdit(self.frame)
        self.IP_RFFE.setGeometry(QtCore.QRect(230, 120, 123, 26))
        self.IP_RFFE.setObjectName(_fromUtf8("IP_RFFE"))
        self.IP_NETWORK_ANALYZER = QtGui.QLineEdit(self.frame)
        self.IP_NETWORK_ANALYZER.setGeometry(QtCore.QRect(230, 180, 123, 26))
        self.IP_NETWORK_ANALYZER.setObjectName(_fromUtf8("IP_NETWORK_ANALYZER"))
        self.IP_SWITCH_1 = QtGui.QLineEdit(self.frame)
        self.IP_SWITCH_1.setGeometry(QtCore.QRect(230, 60, 123, 26))
        self.IP_SWITCH_1.setObjectName(_fromUtf8("IP_SWITCH_1"))
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(30, 320, 371, 191))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.label_20 = QtGui.QLabel(self.frame_3)
        self.label_20.setGeometry(QtCore.QRect(0, 20, 371, 20))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.PARAMETRO_S = QtGui.QRadioButton(self.frame_3)
        self.PARAMETRO_S.setGeometry(QtCore.QRect(30, 50, 131, 20))
        self.PARAMETRO_S.setAutoExclusive(False)
        self.PARAMETRO_S.setObjectName(_fromUtf8("PARAMETRO_S"))
        self.ATENUADORES = QtGui.QRadioButton(self.frame_3)
        self.ATENUADORES.setGeometry(QtCore.QRect(30, 80, 131, 20))
        self.ATENUADORES.setAutoExclusive(False)
        self.ATENUADORES.setObjectName(_fromUtf8("ATENUADORES"))
        self.SWITCH_DC = QtGui.QRadioButton(self.frame_3)
        self.SWITCH_DC.setGeometry(QtCore.QRect(30, 110, 131, 20))
        self.SWITCH_DC.setAutoExclusive(False)
        self.SWITCH_DC.setObjectName(_fromUtf8("SWITCH_DC"))
        self.FREQ_RESP = QtGui.QRadioButton(self.frame_3)
        self.FREQ_RESP.setGeometry(QtCore.QRect(30, 140, 131, 20))
        self.FREQ_RESP.setAutoExclusive(False)
        self.FREQ_RESP.setObjectName(_fromUtf8("FREQ_RESP"))
        self.TEMPERATURA = QtGui.QRadioButton(self.frame_3)
        self.TEMPERATURA.setGeometry(QtCore.QRect(220, 140, 131, 20))
        self.TEMPERATURA.setAutoExclusive(False)
        self.TEMPERATURA.setObjectName(_fromUtf8("TEMPERATURA"))
        self.LINEARIDADE = QtGui.QRadioButton(self.frame_3)
        self.LINEARIDADE.setGeometry(QtCore.QRect(220, 80, 131, 20))
        self.LINEARIDADE.setAutoExclusive(False)
        self.LINEARIDADE.setObjectName(_fromUtf8("LINEARIDADE"))
        self.CROSSTALK = QtGui.QRadioButton(self.frame_3)
        self.CROSSTALK.setGeometry(QtCore.QRect(220, 110, 131, 20))
        self.CROSSTALK.setAutoExclusive(False)
        self.CROSSTALK.setObjectName(_fromUtf8("CROSSTALK"))
        self.RETURN_LOSS = QtGui.QRadioButton(self.frame_3)
        self.RETURN_LOSS.setGeometry(QtCore.QRect(220, 50, 131, 20))
        self.RETURN_LOSS.setAutoExclusive(False)
        self.RETURN_LOSS.setObjectName(_fromUtf8("RETURN_LOSS"))
        self.ALL_TESTS = QtGui.QRadioButton(self.frame_3)
        self.ALL_TESTS.setGeometry(QtCore.QRect(150, 160, 81, 20))
        self.ALL_TESTS.setChecked(False)
        self.ALL_TESTS.setAutoRepeat(False)
        self.ALL_TESTS.setObjectName(_fromUtf8("ALL_TESTS"))
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(800, 90, 501, 361))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.label_21 = QtGui.QLabel(self.frame_4)
        self.label_21.setGeometry(QtCore.QRect(0, 10, 451, 20))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.TEMP_MIN = QtGui.QLineEdit(self.frame_4)
        self.TEMP_MIN.setGeometry(QtCore.QRect(193, 320, 41, 26))
        self.TEMP_MIN.setObjectName(_fromUtf8("TEMP_MIN"))
        self.XTALK_REF = QtGui.QLineEdit(self.frame_4)
        self.XTALK_REF.setGeometry(QtCore.QRect(230, 290, 41, 26))
        self.XTALK_REF.setObjectName(_fromUtf8("XTALK_REF"))
        self.LINEARITY_REF = QtGui.QLineEdit(self.frame_4)
        self.LINEARITY_REF.setGeometry(QtCore.QRect(230, 260, 41, 26))
        self.LINEARITY_REF.setObjectName(_fromUtf8("LINEARITY_REF"))
        self.label_22 = QtGui.QLabel(self.frame_4)
        self.label_22.setGeometry(QtCore.QRect(-2, 320, 161, 26))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.frame_4)
        self.label_23.setGeometry(QtCore.QRect(0, 290, 161, 26))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.frame_4)
        self.label_24.setGeometry(QtCore.QRect(0, 260, 161, 26))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(self.frame_4)
        self.label_25.setGeometry(QtCore.QRect(160, 40, 181, 61))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.frame_4)
        self.label_26.setGeometry(QtCore.QRect(340, 40, 171, 26))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.ATT_TOL = QtGui.QLineEdit(self.frame_4)
        self.ATT_TOL.setGeometry(QtCore.QRect(370, 110, 41, 26))
        self.ATT_TOL.setObjectName(_fromUtf8("ATT_TOL"))
        self.ATT_REF = QtGui.QLineEdit(self.frame_4)
        self.ATT_REF.setGeometry(QtCore.QRect(230, 110, 41, 26))
        self.ATT_REF.setObjectName(_fromUtf8("ATT_REF"))
        self.SWITCH_TOL = QtGui.QLineEdit(self.frame_4)
        self.SWITCH_TOL.setGeometry(QtCore.QRect(370, 140, 41, 26))
        self.SWITCH_TOL.setObjectName(_fromUtf8("SWITCH_TOL"))
        self.FREQ_RES_TOL_REF = QtGui.QLineEdit(self.frame_4)
        self.FREQ_RES_TOL_REF.setGeometry(QtCore.QRect(370, 170, 41, 26))
        self.FREQ_RES_TOL_REF.setObjectName(_fromUtf8("FREQ_RES_TOL_REF"))
        self.RET_LOSS_S11_TOL_REF = QtGui.QLineEdit(self.frame_4)
        self.RET_LOSS_S11_TOL_REF.setGeometry(QtCore.QRect(370, 200, 41, 26))
        self.RET_LOSS_S11_TOL_REF.setObjectName(_fromUtf8("RET_LOSS_S11_TOL_REF"))
        self.LINEARITY_TOL = QtGui.QLineEdit(self.frame_4)
        self.LINEARITY_TOL.setGeometry(QtCore.QRect(370, 260, 41, 26))
        self.LINEARITY_TOL.setObjectName(_fromUtf8("LINEARITY_TOL"))
        self.XTALK_TOL_REF = QtGui.QLineEdit(self.frame_4)
        self.XTALK_TOL_REF.setGeometry(QtCore.QRect(370, 290, 41, 26))
        self.XTALK_TOL_REF.setObjectName(_fromUtf8("XTALK_TOL_REF"))
        self.TEMP_MAX = QtGui.QLineEdit(self.frame_4)
        self.TEMP_MAX.setGeometry(QtCore.QRect(280, 320, 41, 26))
        self.TEMP_MAX.setObjectName(_fromUtf8("TEMP_MAX"))
        self.label_27 = QtGui.QLabel(self.frame_4)
        self.label_27.setGeometry(QtCore.QRect(0, 230, 161, 26))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.RET_LOSS_S22_REF = QtGui.QLineEdit(self.frame_4)
        self.RET_LOSS_S22_REF.setGeometry(QtCore.QRect(230, 230, 41, 26))
        self.RET_LOSS_S22_REF.setObjectName(_fromUtf8("RET_LOSS_S22_REF"))
        self.RET_LOSS_S22_TOL_REF = QtGui.QLineEdit(self.frame_4)
        self.RET_LOSS_S22_TOL_REF.setGeometry(QtCore.QRect(370, 230, 41, 26))
        self.RET_LOSS_S22_TOL_REF.setObjectName(_fromUtf8("RET_LOSS_S22_TOL_REF"))
        self.line_2 = QtGui.QFrame(self.frame_4)
        self.line_2.setGeometry(QtCore.QRect(340, 58, 171, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.frame_4)
        self.line_3.setGeometry(QtCore.QRect(0, 30, 511, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_4 = QtGui.QFrame(self.frame_4)
        self.line_4.setGeometry(QtCore.QRect(150, 39, 20, 321))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.SWITCH_REF = QtGui.QLineEdit(self.frame_4)
        self.SWITCH_REF.setGeometry(QtCore.QRect(230, 140, 41, 26))
        self.SWITCH_REF.setObjectName(_fromUtf8("SWITCH_REF"))
        self.FREQ_RES_REF = QtGui.QLineEdit(self.frame_4)
        self.FREQ_RES_REF.setGeometry(QtCore.QRect(230, 170, 41, 26))
        self.FREQ_RES_REF.setObjectName(_fromUtf8("FREQ_RES_REF"))
        self.RET_LOSS_S11_REF = QtGui.QLineEdit(self.frame_4)
        self.RET_LOSS_S11_REF.setGeometry(QtCore.QRect(230, 200, 41, 26))
        self.RET_LOSS_S11_REF.setObjectName(_fromUtf8("RET_LOSS_S11_REF"))
        self.label_17 = QtGui.QLabel(self.frame_4)
        self.label_17.setGeometry(QtCore.QRect(0, 140, 161, 26))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_15 = QtGui.QLabel(self.frame_4)
        self.label_15.setGeometry(QtCore.QRect(0, 110, 161, 26))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.frame_4)
        self.label_16.setGeometry(QtCore.QRect(0, 170, 161, 26))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_18 = QtGui.QLabel(self.frame_4)
        self.label_18.setGeometry(QtCore.QRect(0, 200, 161, 26))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.line_5 = QtGui.QFrame(self.frame_4)
        self.line_5.setGeometry(QtCore.QRect(330, 39, 20, 321))
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.label_30 = QtGui.QLabel(self.frame_4)
        self.label_30.setGeometry(QtCore.QRect(190, 170, 41, 26))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_31 = QtGui.QLabel(self.frame_4)
        self.label_31.setGeometry(QtCore.QRect(190, 140, 41, 26))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_29 = QtGui.QLabel(self.frame_4)
        self.label_29.setGeometry(QtCore.QRect(340, 140, 31, 26))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_32 = QtGui.QLabel(self.frame_4)
        self.label_32.setGeometry(QtCore.QRect(340, 110, 31, 26))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.label_34 = QtGui.QLabel(self.frame_4)
        self.label_34.setGeometry(QtCore.QRect(340, 200, 31, 26))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.label_35 = QtGui.QLabel(self.frame_4)
        self.label_35.setGeometry(QtCore.QRect(340, 230, 31, 26))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.label_36 = QtGui.QLabel(self.frame_4)
        self.label_36.setGeometry(QtCore.QRect(340, 260, 31, 26))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.label_37 = QtGui.QLabel(self.frame_4)
        self.label_37.setGeometry(QtCore.QRect(340, 290, 31, 26))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.label_19 = QtGui.QLabel(self.frame_4)
        self.label_19.setGeometry(QtCore.QRect(0, 40, 161, 61))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_38 = QtGui.QLabel(self.frame_4)
        self.label_38.setGeometry(QtCore.QRect(190, 200, 41, 26))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.label_39 = QtGui.QLabel(self.frame_4)
        self.label_39.setGeometry(QtCore.QRect(190, 230, 41, 26))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.label_40 = QtGui.QLabel(self.frame_4)
        self.label_40.setGeometry(QtCore.QRect(190, 290, 41, 26))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.label_41 = QtGui.QLabel(self.frame_4)
        self.label_41.setGeometry(QtCore.QRect(158, 320, 41, 26))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.label_42 = QtGui.QLabel(self.frame_4)
        self.label_42.setGeometry(QtCore.QRect(248, 320, 31, 26))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.label_10 = QtGui.QLabel(self.frame_4)
        self.label_10.setGeometry(QtCore.QRect(340, 72, 91, 21))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.line_7 = QtGui.QFrame(self.frame_4)
        self.line_7.setGeometry(QtCore.QRect(0, 88, 511, 20))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.line_9 = QtGui.QFrame(self.frame_4)
        self.line_9.setGeometry(QtCore.QRect(415, 67, 20, 293))
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.label_65 = QtGui.QLabel(self.frame_4)
        self.label_65.setGeometry(QtCore.QRect(420, 170, 31, 26))
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.FREQ_RES_TOL_VAR = QtGui.QLineEdit(self.frame_4)
        self.FREQ_RES_TOL_VAR.setGeometry(QtCore.QRect(450, 170, 41, 26))
        self.FREQ_RES_TOL_VAR.setObjectName(_fromUtf8("FREQ_RES_TOL_VAR"))
        self.dateTimeEdit_tela_inicial = QtGui.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit_tela_inicial.setGeometry(QtCore.QRect(550, 40, 194, 26))
        self.dateTimeEdit_tela_inicial.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit_tela_inicial.setObjectName(_fromUtf8("dateTimeEdit_tela_inicial"))
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(430, 90, 341, 521))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.NETWORK_FREQ_SPAN = QtGui.QLineEdit(self.frame_2)
        self.NETWORK_FREQ_SPAN.setGeometry(QtCore.QRect(220, 110, 101, 26))
        self.NETWORK_FREQ_SPAN.setObjectName(_fromUtf8("NETWORK_FREQ_SPAN"))
        self.NETWORK_FREQ_CENTRAL = QtGui.QLineEdit(self.frame_2)
        self.NETWORK_FREQ_CENTRAL.setGeometry(QtCore.QRect(220, 80, 101, 26))
        self.NETWORK_FREQ_CENTRAL.setObjectName(_fromUtf8("NETWORK_FREQ_CENTRAL"))
        self.label_43 = QtGui.QLabel(self.frame_2)
        self.label_43.setGeometry(QtCore.QRect(30, 110, 141, 26))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.label_44 = QtGui.QLabel(self.frame_2)
        self.label_44.setGeometry(QtCore.QRect(30, 420, 171, 26))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.label_28 = QtGui.QLabel(self.frame_2)
        self.label_28.setGeometry(QtCore.QRect(30, 80, 141, 26))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.NETWORK_POT_IN_STANDARD = QtGui.QLineEdit(self.frame_2)
        self.NETWORK_POT_IN_STANDARD.setGeometry(QtCore.QRect(220, 140, 101, 26))
        self.NETWORK_POT_IN_STANDARD.setObjectName(_fromUtf8("NETWORK_POT_IN_STANDARD"))
        self.label_47 = QtGui.QLabel(self.frame_2)
        self.label_47.setGeometry(QtCore.QRect(30, 140, 161, 26))
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.label_48 = QtGui.QLabel(self.frame_2)
        self.label_48.setGeometry(QtCore.QRect(30, 350, 171, 26))
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.label_49 = QtGui.QLabel(self.frame_2)
        self.label_49.setGeometry(QtCore.QRect(0, 40, 341, 26))
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.line = QtGui.QFrame(self.frame_2)
        self.line.setGeometry(QtCore.QRect(0, 30, 341, 16))
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_5 = QtGui.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(0, 10, 341, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.line_6 = QtGui.QFrame(self.frame_2)
        self.line_6.setGeometry(QtCore.QRect(0, 300, 341, 20))
        self.line_6.setLineWidth(2)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.label_50 = QtGui.QLabel(self.frame_2)
        self.label_50.setGeometry(QtCore.QRect(0, 310, 341, 26))
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.RFFE_ATTENUATION_STANDARD = QtGui.QLineEdit(self.frame_2)
        self.RFFE_ATTENUATION_STANDARD.setGeometry(QtCore.QRect(220, 350, 101, 26))
        self.RFFE_ATTENUATION_STANDARD.setObjectName(_fromUtf8("RFFE_ATTENUATION_STANDARD"))
        self.RFFE_ATTENUATION_INITIAL = QtGui.QLineEdit(self.frame_2)
        self.RFFE_ATTENUATION_INITIAL.setGeometry(QtCore.QRect(220, 420, 101, 26))
        self.RFFE_ATTENUATION_INITIAL.setObjectName(_fromUtf8("RFFE_ATTENUATION_INITIAL"))
        self.label_51 = QtGui.QLabel(self.frame_2)
        self.label_51.setGeometry(QtCore.QRect(30, 450, 161, 26))
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.RFFE_ATTENUATION_FINAL = QtGui.QLineEdit(self.frame_2)
        self.RFFE_ATTENUATION_FINAL.setGeometry(QtCore.QRect(220, 450, 101, 26))
        self.RFFE_ATTENUATION_FINAL.setObjectName(_fromUtf8("RFFE_ATTENUATION_FINAL"))
        self.label_52 = QtGui.QLabel(self.frame_2)
        self.label_52.setGeometry(QtCore.QRect(30, 480, 171, 26))
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.RFFE_ATTENUATION_STEP = QtGui.QLineEdit(self.frame_2)
        self.RFFE_ATTENUATION_STEP.setGeometry(QtCore.QRect(220, 480, 101, 26))
        self.RFFE_ATTENUATION_STEP.setObjectName(_fromUtf8("RFFE_ATTENUATION_STEP"))
        self.line_8 = QtGui.QFrame(self.frame_2)
        self.line_8.setGeometry(QtCore.QRect(0, 400, 341, 20))
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.NETWORK_POT_IN_FINAL = QtGui.QLineEdit(self.frame_2)
        self.NETWORK_POT_IN_FINAL.setGeometry(QtCore.QRect(220, 240, 101, 26))
        self.NETWORK_POT_IN_FINAL.setObjectName(_fromUtf8("NETWORK_POT_IN_FINAL"))
        self.label_55 = QtGui.QLabel(self.frame_2)
        self.label_55.setGeometry(QtCore.QRect(30, 210, 171, 26))
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.NETWORK_POT_IN_STEP = QtGui.QLineEdit(self.frame_2)
        self.NETWORK_POT_IN_STEP.setGeometry(QtCore.QRect(220, 270, 101, 26))
        self.NETWORK_POT_IN_STEP.setObjectName(_fromUtf8("NETWORK_POT_IN_STEP"))
        self.label_56 = QtGui.QLabel(self.frame_2)
        self.label_56.setGeometry(QtCore.QRect(30, 270, 171, 26))
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.label_57 = QtGui.QLabel(self.frame_2)
        self.label_57.setGeometry(QtCore.QRect(30, 240, 161, 26))
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.NETWORK_POT_IN_INITIAL = QtGui.QLineEdit(self.frame_2)
        self.NETWORK_POT_IN_INITIAL.setGeometry(QtCore.QRect(220, 210, 101, 26))
        self.NETWORK_POT_IN_INITIAL.setObjectName(_fromUtf8("NETWORK_POT_IN_INITIAL"))
        self.label_58 = QtGui.QLabel(self.frame_2)
        self.label_58.setGeometry(QtCore.QRect(0, 390, 341, 20))
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.label_59 = QtGui.QLabel(self.frame_2)
        self.label_59.setGeometry(QtCore.QRect(0, 170, 341, 20))
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.label_45 = QtGui.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(30, 610, 601, 26))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.label_46 = QtGui.QLabel(self.centralwidget)
        self.label_46.setGeometry(QtCore.QRect(50, 180, 191, 26))
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.line_10 = QtGui.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(430, 270, 341, 20))
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.line_11 = QtGui.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(430, 470, 341, 20))
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.line_12 = QtGui.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(430, 250, 341, 20))
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.CURVA_S_PARAMETER = QtGui.QCheckBox(self.centralwidget)
        self.CURVA_S_PARAMETER.setGeometry(QtCore.QRect(1050, 40, 201, 20))
        self.CURVA_S_PARAMETER.setObjectName(_fromUtf8("CURVA_S_PARAMETER"))
        self.label_53 = QtGui.QLabel(self.centralwidget)
        self.label_53.setGeometry(QtCore.QRect(30, 624, 601, 26))
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.frame_5 = QtGui.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(800, 470, 501, 141))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.label_54 = QtGui.QLabel(self.frame_5)
        self.label_54.setGeometry(QtCore.QRect(0, 10, 451, 20))
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.NETWORK_MODEL = QtGui.QLineEdit(self.frame_5)
        self.NETWORK_MODEL.setGeometry(QtCore.QRect(140, 40, 113, 26))
        self.NETWORK_MODEL.setObjectName(_fromUtf8("NETWORK_MODEL"))
        self.WAVEFORM_MODEL = QtGui.QLineEdit(self.frame_5)
        self.WAVEFORM_MODEL.setGeometry(QtCore.QRect(140, 70, 113, 26))
        self.WAVEFORM_MODEL.setObjectName(_fromUtf8("WAVEFORM_MODEL"))
        self.label_3 = QtGui.QLabel(self.frame_5)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 111, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_6 = QtGui.QLabel(self.frame_5)
        self.label_6.setGeometry(QtCore.QRect(10, 70, 131, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.DC_POWER_MODEL = QtGui.QLineEdit(self.frame_5)
        self.DC_POWER_MODEL.setGeometry(QtCore.QRect(140, 100, 113, 26))
        self.DC_POWER_MODEL.setObjectName(_fromUtf8("DC_POWER_MODEL"))
        self.label_7 = QtGui.QLabel(self.frame_5)
        self.label_7.setGeometry(QtCore.QRect(10, 100, 131, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.frame_5)
        self.label_8.setGeometry(QtCore.QRect(270, 40, 111, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.RF_SWITCH_MODEL = QtGui.QLineEdit(self.frame_5)
        self.RF_SWITCH_MODEL.setGeometry(QtCore.QRect(380, 40, 113, 26))
        self.RF_SWITCH_MODEL.setObjectName(_fromUtf8("RF_SWITCH_MODEL"))
        self.RFFE_SERIE = QtGui.QLineEdit(self.frame_5)
        self.RFFE_SERIE.setGeometry(QtCore.QRect(380, 70, 113, 26))
        self.RFFE_SERIE.setObjectName(_fromUtf8("RFFE_SERIE"))
        self.label_9 = QtGui.QLabel(self.frame_5)
        self.label_9.setGeometry(QtCore.QRect(270, 70, 111, 21))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.RFFE_OPERADOR = QtGui.QLineEdit(self.frame_5)
        self.RFFE_OPERADOR.setGeometry(QtCore.QRect(380, 100, 113, 26))
        self.RFFE_OPERADOR.setObjectName(_fromUtf8("RFFE_OPERADOR"))
        self.label_64 = QtGui.QLabel(self.frame_5)
        self.label_64.setGeometry(QtCore.QRect(270, 100, 111, 21))
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(1225, 162, 71, 21))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_62 = QtGui.QLabel(self.centralwidget)
        self.label_62.setGeometry(QtCore.QRect(1140, 260, 31, 26))
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.frame_6 = QtGui.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(30, 520, 371, 91))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.label_33 = QtGui.QLabel(self.frame_6)
        self.label_33.setGeometry(QtCore.QRect(0, 10, 371, 20))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.label_60 = QtGui.QLabel(self.frame_6)
        self.label_60.setGeometry(QtCore.QRect(30, 50, 81, 26))
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.NETWORK_START_BANDWIDTH = QtGui.QLineEdit(self.frame_6)
        self.NETWORK_START_BANDWIDTH.setGeometry(QtCore.QRect(110, 50, 51, 26))
        self.NETWORK_START_BANDWIDTH.setObjectName(_fromUtf8("NETWORK_START_BANDWIDTH"))
        self.label_61 = QtGui.QLabel(self.frame_6)
        self.label_61.setGeometry(QtCore.QRect(210, 50, 81, 26))
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.NETWORK_STOP_BANDWIDTH = QtGui.QLineEdit(self.frame_6)
        self.NETWORK_STOP_BANDWIDTH.setGeometry(QtCore.QRect(290, 50, 51, 26))
        self.NETWORK_STOP_BANDWIDTH.setObjectName(_fromUtf8("NETWORK_STOP_BANDWIDTH"))
        self.label_63 = QtGui.QLabel(self.centralwidget)
        self.label_63.setGeometry(QtCore.QRect(30, 638, 601, 26))
        self.label_63.setObjectName(_fromUtf8("label_63"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.IP_SWITCH_1, self.IP_SWITCH_2)
        MainWindow.setTabOrder(self.IP_SWITCH_2, self.IP_RFFE)
        MainWindow.setTabOrder(self.IP_RFFE, self.IP_GERADOR_SINAIS_DC)
        MainWindow.setTabOrder(self.IP_GERADOR_SINAIS_DC, self.IP_NETWORK_ANALYZER)
        MainWindow.setTabOrder(self.IP_NETWORK_ANALYZER, self.NETWORK_FREQ_CENTRAL)
        MainWindow.setTabOrder(self.NETWORK_FREQ_CENTRAL, self.NETWORK_FREQ_SPAN)
        MainWindow.setTabOrder(self.NETWORK_FREQ_SPAN, self.NETWORK_POT_IN_STANDARD)
        MainWindow.setTabOrder(self.NETWORK_POT_IN_STANDARD, self.NETWORK_POT_IN_INITIAL)
        MainWindow.setTabOrder(self.NETWORK_POT_IN_INITIAL, self.NETWORK_POT_IN_FINAL)
        MainWindow.setTabOrder(self.NETWORK_POT_IN_FINAL, self.NETWORK_POT_IN_STEP)
        MainWindow.setTabOrder(self.NETWORK_POT_IN_STEP, self.RFFE_ATTENUATION_STANDARD)
        MainWindow.setTabOrder(self.RFFE_ATTENUATION_STANDARD, self.RFFE_ATTENUATION_INITIAL)
        MainWindow.setTabOrder(self.RFFE_ATTENUATION_INITIAL, self.RFFE_ATTENUATION_FINAL)
        MainWindow.setTabOrder(self.RFFE_ATTENUATION_FINAL, self.RFFE_ATTENUATION_STEP)
        MainWindow.setTabOrder(self.RFFE_ATTENUATION_STEP, self.ATT_REF)
        MainWindow.setTabOrder(self.ATT_REF, self.SWITCH_REF)
        MainWindow.setTabOrder(self.SWITCH_REF, self.FREQ_RES_REF)
        MainWindow.setTabOrder(self.FREQ_RES_REF, self.RET_LOSS_S11_REF)
        MainWindow.setTabOrder(self.RET_LOSS_S11_REF, self.RET_LOSS_S22_REF)
        MainWindow.setTabOrder(self.RET_LOSS_S22_REF, self.LINEARITY_REF)
        MainWindow.setTabOrder(self.LINEARITY_REF, self.XTALK_REF)
        MainWindow.setTabOrder(self.XTALK_REF, self.TEMP_MIN)
        MainWindow.setTabOrder(self.TEMP_MIN, self.TEMP_MAX)
        MainWindow.setTabOrder(self.TEMP_MAX, self.ATT_TOL)
        MainWindow.setTabOrder(self.ATT_TOL, self.SWITCH_TOL)
        MainWindow.setTabOrder(self.SWITCH_TOL, self.FREQ_RES_TOL_REF)
        MainWindow.setTabOrder(self.FREQ_RES_TOL_REF, self.RET_LOSS_S11_TOL_REF)
        MainWindow.setTabOrder(self.RET_LOSS_S11_TOL_REF, self.RET_LOSS_S22_TOL_REF)
        MainWindow.setTabOrder(self.RET_LOSS_S22_TOL_REF, self.LINEARITY_TOL)
        MainWindow.setTabOrder(self.LINEARITY_TOL, self.XTALK_TOL_REF)
        MainWindow.setTabOrder(self.XTALK_TOL_REF, self.NETWORK_MODEL)
        MainWindow.setTabOrder(self.NETWORK_MODEL, self.WAVEFORM_MODEL)
        MainWindow.setTabOrder(self.WAVEFORM_MODEL, self.DC_POWER_MODEL)
        MainWindow.setTabOrder(self.DC_POWER_MODEL, self.RF_SWITCH_MODEL)
        MainWindow.setTabOrder(self.RF_SWITCH_MODEL, self.RFFE_SERIE)
        MainWindow.setTabOrder(self.RFFE_SERIE, self.PARAMETRO_S)
        MainWindow.setTabOrder(self.PARAMETRO_S, self.ATENUADORES)
        MainWindow.setTabOrder(self.ATENUADORES, self.SWITCH_DC)
        MainWindow.setTabOrder(self.SWITCH_DC, self.FREQ_RESP)
        MainWindow.setTabOrder(self.FREQ_RESP, self.RETURN_LOSS)
        MainWindow.setTabOrder(self.RETURN_LOSS, self.LINEARIDADE)
        MainWindow.setTabOrder(self.LINEARIDADE, self.CROSSTALK)
        MainWindow.setTabOrder(self.CROSSTALK, self.TEMPERATURA)
        MainWindow.setTabOrder(self.TEMPERATURA, self.ALL_TESTS)
        MainWindow.setTabOrder(self.ALL_TESTS, self.CURVA_S_PARAMETER)
        MainWindow.setTabOrder(self.CURVA_S_PARAMETER, self.START_BUTTON)
        MainWindow.setTabOrder(self.START_BUTTON, self.EXIT_BUTTON)
        MainWindow.setTabOrder(self.EXIT_BUTTON, self.dateTimeEdit_tela_inicial)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Teste do RFFE", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>Antes de iniciar o teste, favor confirmar os parâmetros do teste abaixo.</p><p>Após isso, clique em INICIAR TESTE</p></body></html>", None))
        self.START_BUTTON.setText(_translate("MainWindow", "Iniciar Teste", None))
        self.EXIT_BUTTON.setText(_translate("MainWindow", "Sair", None))
        self.label_4.setText(_translate("MainWindow", "IP DO RFFE", None))
        self.label_12.setText(_translate("MainWindow", "IP DO GERADOR DE SINAIS DC", None))
        self.label_13.setText(_translate("MainWindow", "IP DO NETWORK ANALYZER", None))
        self.label_14.setText(_translate("MainWindow", "IP DO SWITCH 1", None))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">PARÂMETROS DE COMUNICAÇÃO</span></p></body></html>", None))
        self.IP_SWITCH_2.setText(_translate("MainWindow", "10.0.18.50", None))
        self.IP_GERADOR_SINAIS_DC.setText(_translate("MainWindow", "10.0.18.69", None))
        self.IP_RFFE.setText(_translate("MainWindow", "10.0.18.9", None))
        self.IP_NETWORK_ANALYZER.setText(_translate("MainWindow", "10.0.18.66", None))
        self.IP_SWITCH_1.setText(_translate("MainWindow", "10.0.18.68", None))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">TESTES A SEREM REALIZADOS</span></p></body></html>", None))
        self.PARAMETRO_S.setText(_translate("MainWindow", "PARÂMETRO S", None))
        self.ATENUADORES.setText(_translate("MainWindow", "ATENUADORES", None))
        self.SWITCH_DC.setText(_translate("MainWindow", "SWITCH DC", None))
        self.FREQ_RESP.setText(_translate("MainWindow", "RESP. FREQ.", None))
        self.TEMPERATURA.setText(_translate("MainWindow", "TEMPERATURA", None))
        self.LINEARIDADE.setText(_translate("MainWindow", "LINEARIDADE", None))
        self.CROSSTALK.setText(_translate("MainWindow", "CROSSTALK", None))
        self.RETURN_LOSS.setText(_translate("MainWindow", "RETURN LOSS", None))
        self.ALL_TESTS.setText(_translate("MainWindow", "TODOS", None))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">CRITÉRIO DE APROVAÇÃO DO TESTE</span></p></body></html>", None))
        self.TEMP_MIN.setText(_translate("MainWindow", "20", None))
        self.XTALK_REF.setText(_translate("MainWindow", "-36", None))
        self.LINEARITY_REF.setText(_translate("MainWindow", "0", None))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">TEMPERATURA [°C]</p></body></html>", None))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">CROSSTALK [dB]</p></body></html>", None))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">LINEARIDADE [dB]</p></body></html>", None))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Valor de Referência</span></p></body></html>", None))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Tolerância</span></p></body></html>", None))
        self.ATT_TOL.setText(_translate("MainWindow", "0.2", None))
        self.ATT_REF.setText(_translate("MainWindow", "5", None))
        self.SWITCH_TOL.setText(_translate("MainWindow", "0", None))
        self.FREQ_RES_TOL_REF.setText(_translate("MainWindow", "-1", None))
        self.RET_LOSS_S11_TOL_REF.setText(_translate("MainWindow", "1", None))
        self.LINEARITY_TOL.setText(_translate("MainWindow", "0.2", None))
        self.XTALK_TOL_REF.setText(_translate("MainWindow", "2", None))
        self.TEMP_MAX.setText(_translate("MainWindow", "40", None))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">RET. LOSS (S22) [dB]</p></body></html>", None))
        self.RET_LOSS_S22_REF.setText(_translate("MainWindow", "-17", None))
        self.RET_LOSS_S22_TOL_REF.setText(_translate("MainWindow", "1", None))
        self.SWITCH_REF.setText(_translate("MainWindow", "-36", None))
        self.FREQ_RES_REF.setText(_translate("MainWindow", "4.5", None))
        self.RET_LOSS_S11_REF.setText(_translate("MainWindow", "-13", None))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">SWITCH DC [dB]</p></body></html>", None))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">ATENADORES [dB]</p></body></html>", None))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">RESP. FREQ. [dB]</p></body></html>", None))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">RET. LOSS (S11) [dB]</p></body></html>", None))
        self.label_30.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">&gt;</p></body></html>", None))
        self.label_31.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">&gt;</p></body></html>", None))
        self.label_29.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">+</p></body></html>", None))
        self.label_32.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">±</p></body></html>", None))
        self.label_34.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">+</p></body></html>", None))
        self.label_35.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">+</p></body></html>", None))
        self.label_36.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">±</p></body></html>", None))
        self.label_37.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">+</p></body></html>", None))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Tipo de Teste</span></p></body></html>", None))
        self.label_38.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">&gt;</p></body></html>", None))
        self.label_39.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">&gt;</p></body></html>", None))
        self.label_40.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">&gt;</p></body></html>", None))
        self.label_41.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Min</p></body></html>", None))
        self.label_42.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Máx</p></body></html>", None))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-style:italic;\">Ref.</span></p></body></html>", None))
        self.label_65.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">±</p></body></html>", None))
        self.FREQ_RES_TOL_VAR.setText(_translate("MainWindow", "1", None))
        self.NETWORK_FREQ_SPAN.setText(_translate("MainWindow", "90", None))
        self.NETWORK_FREQ_CENTRAL.setText(_translate("MainWindow", "475", None))
        self.label_43.setText(_translate("MainWindow", "Freq. Span [MHz]", None))
        self.label_44.setText(_translate("MainWindow", "Atenuação Inicial [dB]", None))
        self.label_28.setText(_translate("MainWindow", "Freq. Central [MHz]", None))
        self.NETWORK_POT_IN_STANDARD.setText(_translate("MainWindow", "-25", None))
        self.label_47.setText(_translate("MainWindow", "Nível de Entrada* [dB]", None))
        self.label_48.setText(_translate("MainWindow", "Nível de Atenuação** [dB]", None))
        self.label_49.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Network Analyzer</span></p></body></html>", None))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">PARÂMETROS DE ENTRADA</span></p></body></html>", None))
        self.label_50.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">RFFE</span></p></body></html>", None))
        self.RFFE_ATTENUATION_STANDARD.setText(_translate("MainWindow", "30", None))
        self.RFFE_ATTENUATION_INITIAL.setText(_translate("MainWindow", "2.5", None))
        self.label_51.setText(_translate("MainWindow", "Atenuação Final [dB]", None))
        self.RFFE_ATTENUATION_FINAL.setText(_translate("MainWindow", "27.5", None))
        self.label_52.setText(_translate("MainWindow", "Step [dB]", None))
        self.RFFE_ATTENUATION_STEP.setText(_translate("MainWindow", "5", None))
        self.NETWORK_POT_IN_FINAL.setText(_translate("MainWindow", "-20", None))
        self.label_55.setText(_translate("MainWindow", "Nível Inicial [dB]", None))
        self.NETWORK_POT_IN_STEP.setText(_translate("MainWindow", "5", None))
        self.label_56.setText(_translate("MainWindow", "Step [dB]", None))
        self.label_57.setText(_translate("MainWindow", "Nível Final [dB]", None))
        self.NETWORK_POT_IN_INITIAL.setText(_translate("MainWindow", "-45", None))
        self.label_58.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-style:italic;\">Teste de Atenuadores</span></p></body></html>", None))
        self.label_59.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-style:italic;\">Teste de Linearidade</span></p></body></html>", None))
        self.label_45.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt;\">* Aplicável para os testes:  Parâmetro-S, Atenuadores, RF Switch, Resp. Freq., Return Loss e Crosstalk</span></p></body></html>", None))
        self.label_46.setText(_translate("MainWindow", "IP DO SWITCH 2", None))
        self.CURVA_S_PARAMETER.setText(_translate("MainWindow", "Gerar Curvas - Parâmetro-S", None))
        self.label_53.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt;\">** Aplicável para os testes: Parâmetro-S, Linearidade, RF Switch, Resp. Freq., Return Loss e Crosstalk</span></p></body></html>", None))
        self.label_54.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">DESCRIÇÃO DO SET-UP DE TESTE</span></p></body></html>", None))
        self.NETWORK_MODEL.setText(_translate("MainWindow", "E5062A", None))
        self.WAVEFORM_MODEL.setText(_translate("MainWindow", "33500B", None))
        self.label_3.setText(_translate("MainWindow", "Network Analyzer", None))
        self.label_6.setText(_translate("MainWindow", "Waveform Generator", None))
        self.DC_POWER_MODEL.setText(_translate("MainWindow", "6626A", None))
        self.label_7.setText(_translate("MainWindow", "DC Power Supply", None))
        self.label_8.setText(_translate("MainWindow", "Chave RF", None))
        self.RF_SWITCH_MODEL.setText(_translate("MainWindow", "RC-2SP4T-A18", None))
        self.RFFE_SERIE.setText(_translate("MainWindow", "11111111", None))
        self.label_9.setText(_translate("MainWindow", "N de Série - RFFE", None))
        self.RFFE_OPERADOR.setText(_translate("MainWindow", "Fernando", None))
        self.label_64.setText(_translate("MainWindow", "Operador", None))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-style:italic;\">Varredura</span></p></body></html>", None))
        self.label_62.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">+</p></body></html>", None))
        self.label_33.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">BANDWIDTH [VARREDURA]***</span></p></body></html>", None))
        self.label_60.setText(_translate("MainWindow", "Start [MHz]", None))
        self.NETWORK_START_BANDWIDTH.setText(_translate("MainWindow", "465", None))
        self.label_61.setText(_translate("MainWindow", "Stop [MHz]", None))
        self.NETWORK_STOP_BANDWIDTH.setText(_translate("MainWindow", "483", None))
        self.label_63.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt;\">*** Aplicável para Resp. Freq, Ret. Loss e Crosstalk [Varredura]</span></p></body></html>", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

