# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_status_leds_rffe.ui'
#
# Created: Mon Feb 20 15:21:47 2017
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(753, 682)
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(20, 20, 341, 281))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(60, 185, 161, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(60, 65, 51, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.kled_NETWORK = KLed(self.frame)
        self.kled_NETWORK.setGeometry(QtCore.QRect(20, 100, 28, 28))
        self.kled_NETWORK.setState(KLed.Off)
        self.kled_NETWORK.setObjectName(_fromUtf8("kled_NETWORK"))
        self.kled_SWITCH2 = KLed(self.frame)
        self.kled_SWITCH2.setGeometry(QtCore.QRect(20, 180, 28, 28))
        self.kled_SWITCH2.setState(KLed.Off)
        self.kled_SWITCH2.setObjectName(_fromUtf8("kled_SWITCH2"))
        self.kled_RFFE = KLed(self.frame)
        self.kled_RFFE.setGeometry(QtCore.QRect(20, 60, 28, 28))
        self.kled_RFFE.setState(KLed.Off)
        self.kled_RFFE.setObjectName(_fromUtf8("kled_RFFE"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(60, 145, 251, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.kled_SWITCH1 = KLed(self.frame)
        self.kled_SWITCH1.setGeometry(QtCore.QRect(20, 140, 28, 28))
        self.kled_SWITCH1.setState(KLed.Off)
        self.kled_SWITCH1.setObjectName(_fromUtf8("kled_SWITCH1"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(60, 105, 201, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(0, 20, 341, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_14 = QtGui.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(60, 225, 171, 21))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.kled_WAVEFORM = KLed(self.frame)
        self.kled_WAVEFORM.setGeometry(QtCore.QRect(20, 220, 28, 28))
        self.kled_WAVEFORM.setState(KLed.Off)
        self.kled_WAVEFORM.setObjectName(_fromUtf8("kled_WAVEFORM"))
        self.frame_2 = QtGui.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(380, 20, 341, 351))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label_6 = QtGui.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(60, 155, 181, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(60, 51, 121, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.kled_ATENUADORES_TEST = KLed(self.frame_2)
        self.kled_ATENUADORES_TEST.setGeometry(QtCore.QRect(20, 80, 31, 31))
        self.kled_ATENUADORES_TEST.setState(KLed.Off)
        self.kled_ATENUADORES_TEST.setObjectName(_fromUtf8("kled_ATENUADORES_TEST"))
        self.kled_RESP_FREQ_TEST = KLed(self.frame_2)
        self.kled_RESP_FREQ_TEST.setGeometry(QtCore.QRect(20, 150, 31, 31))
        self.kled_RESP_FREQ_TEST.setState(KLed.Off)
        self.kled_RESP_FREQ_TEST.setObjectName(_fromUtf8("kled_RESP_FREQ_TEST"))
        self.kled_PARAMETRO_S_TEST = KLed(self.frame_2)
        self.kled_PARAMETRO_S_TEST.setGeometry(QtCore.QRect(20, 45, 31, 31))
        self.kled_PARAMETRO_S_TEST.setState(KLed.Off)
        self.kled_PARAMETRO_S_TEST.setObjectName(_fromUtf8("kled_PARAMETRO_S_TEST"))
        self.label_8 = QtGui.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(60, 125, 81, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.kled_RF_SWITCH_TEST = KLed(self.frame_2)
        self.kled_RF_SWITCH_TEST.setGeometry(QtCore.QRect(20, 115, 31, 31))
        self.kled_RF_SWITCH_TEST.setState(KLed.Off)
        self.kled_RF_SWITCH_TEST.setObjectName(_fromUtf8("kled_RF_SWITCH_TEST"))
        self.label_9 = QtGui.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(60, 85, 201, 21))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(0, 20, 341, 20))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.kled_RETURN_LOSS_TEST = KLed(self.frame_2)
        self.kled_RETURN_LOSS_TEST.setGeometry(QtCore.QRect(20, 185, 31, 31))
        self.kled_RETURN_LOSS_TEST.setState(KLed.Off)
        self.kled_RETURN_LOSS_TEST.setObjectName(_fromUtf8("kled_RETURN_LOSS_TEST"))
        self.label_12 = QtGui.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(60, 190, 141, 21))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.kled_LINEARIDADE_TEST = KLed(self.frame_2)
        self.kled_LINEARIDADE_TEST.setGeometry(QtCore.QRect(20, 220, 31, 31))
        self.kled_LINEARIDADE_TEST.setState(KLed.Off)
        self.kled_LINEARIDADE_TEST.setObjectName(_fromUtf8("kled_LINEARIDADE_TEST"))
        self.label_13 = QtGui.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(60, 230, 141, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.kled_CROSSTALK_TEST = KLed(self.frame_2)
        self.kled_CROSSTALK_TEST.setGeometry(QtCore.QRect(20, 255, 31, 31))
        self.kled_CROSSTALK_TEST.setState(KLed.Off)
        self.kled_CROSSTALK_TEST.setObjectName(_fromUtf8("kled_CROSSTALK_TEST"))
        self.label_15 = QtGui.QLabel(self.frame_2)
        self.label_15.setGeometry(QtCore.QRect(60, 265, 141, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.kled_TEMPERATURE_TEST = KLed(self.frame_2)
        self.kled_TEMPERATURE_TEST.setGeometry(QtCore.QRect(20, 290, 31, 31))
        self.kled_TEMPERATURE_TEST.setState(KLed.Off)
        self.kled_TEMPERATURE_TEST.setObjectName(_fromUtf8("kled_TEMPERATURE_TEST"))
        self.label_16 = QtGui.QLabel(self.frame_2)
        self.label_16.setGeometry(QtCore.QRect(60, 300, 101, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.frame_4 = QtGui.QFrame(Dialog)
        self.frame_4.setGeometry(QtCore.QRect(380, 380, 341, 241))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.label_27 = QtGui.QLabel(self.frame_4)
        self.label_27.setGeometry(QtCore.QRect(60, 45, 51, 21))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.kled_statusFAIL = KLed(self.frame_4)
        self.kled_statusFAIL.setGeometry(QtCore.QRect(20, 80, 28, 28))
        self.kled_statusFAIL.setColor(QtGui.QColor(255, 0, 0))
        self.kled_statusFAIL.setObjectName(_fromUtf8("kled_statusFAIL"))
        self.kled_statusOK = KLed(self.frame_4)
        self.kled_statusOK.setGeometry(QtCore.QRect(20, 40, 28, 28))
        self.kled_statusOK.setObjectName(_fromUtf8("kled_statusOK"))
        self.label_28 = QtGui.QLabel(self.frame_4)
        self.label_28.setGeometry(QtCore.QRect(60, 165, 251, 21))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.kled_statusNotUsed = KLed(self.frame_4)
        self.kled_statusNotUsed.setGeometry(QtCore.QRect(20, 160, 28, 28))
        self.kled_statusNotUsed.setColor(QtGui.QColor(0, 0, 255))
        self.kled_statusNotUsed.setObjectName(_fromUtf8("kled_statusNotUsed"))
        self.label_29 = QtGui.QLabel(self.frame_4)
        self.label_29.setGeometry(QtCore.QRect(60, 85, 201, 21))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(self.frame_4)
        self.label_30.setGeometry(QtCore.QRect(0, 20, 341, 20))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.kled_statusNaoAvaliado = KLed(self.frame_4)
        self.kled_statusNaoAvaliado.setGeometry(QtCore.QRect(20, 200, 28, 28))
        self.kled_statusNaoAvaliado.setState(KLed.Off)
        self.kled_statusNaoAvaliado.setObjectName(_fromUtf8("kled_statusNaoAvaliado"))
        self.label_31 = QtGui.QLabel(self.frame_4)
        self.label_31.setGeometry(QtCore.QRect(60, 205, 251, 21))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.kled_statusExecutando = KLed(self.frame_4)
        self.kled_statusExecutando.setGeometry(QtCore.QRect(20, 120, 28, 28))
        self.kled_statusExecutando.setColor(QtGui.QColor(255, 255, 0))
        self.kled_statusExecutando.setObjectName(_fromUtf8("kled_statusExecutando"))
        self.label_32 = QtGui.QLabel(self.frame_4)
        self.label_32.setGeometry(QtCore.QRect(60, 126, 201, 20))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.OK_Button = QtGui.QPushButton(Dialog)
        self.OK_Button.setGeometry(QtCore.QRect(620, 640, 87, 27))
        self.OK_Button.setObjectName(_fromUtf8("OK_Button"))
        self.progressBar = QtGui.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(220, 640, 311, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.frame_3 = QtGui.QFrame(Dialog)
        self.frame_3.setGeometry(QtCore.QRect(20, 320, 341, 291))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.label_33 = QtGui.QLabel(self.frame_3)
        self.label_33.setGeometry(QtCore.QRect(0, 10, 341, 20))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.kled_CH1_B_SWITCH2 = KLed(self.frame_3)
        self.kled_CH1_B_SWITCH2.setGeometry(QtCore.QRect(190, 195, 28, 28))
        self.kled_CH1_B_SWITCH2.setState(KLed.Off)
        self.kled_CH1_B_SWITCH2.setObjectName(_fromUtf8("kled_CH1_B_SWITCH2"))
        self.label_36 = QtGui.QLabel(self.frame_3)
        self.label_36.setGeometry(QtCore.QRect(280, 200, 31, 21))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.kled_CH4_B_SWITCH2 = KLed(self.frame_3)
        self.kled_CH4_B_SWITCH2.setGeometry(QtCore.QRect(190, 235, 28, 28))
        self.kled_CH4_B_SWITCH2.setState(KLed.Off)
        self.kled_CH4_B_SWITCH2.setObjectName(_fromUtf8("kled_CH4_B_SWITCH2"))
        self.label_37 = QtGui.QLabel(self.frame_3)
        self.label_37.setGeometry(QtCore.QRect(220, 240, 31, 21))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.kled_CH2_B_SWITCH2 = KLed(self.frame_3)
        self.kled_CH2_B_SWITCH2.setGeometry(QtCore.QRect(250, 195, 28, 28))
        self.kled_CH2_B_SWITCH2.setState(KLed.Off)
        self.kled_CH2_B_SWITCH2.setObjectName(_fromUtf8("kled_CH2_B_SWITCH2"))
        self.kled_CH3_B_SWITCH2 = KLed(self.frame_3)
        self.kled_CH3_B_SWITCH2.setGeometry(QtCore.QRect(250, 235, 28, 28))
        self.kled_CH3_B_SWITCH2.setState(KLed.Off)
        self.kled_CH3_B_SWITCH2.setObjectName(_fromUtf8("kled_CH3_B_SWITCH2"))
        self.label_38 = QtGui.QLabel(self.frame_3)
        self.label_38.setGeometry(QtCore.QRect(220, 200, 31, 21))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.label_39 = QtGui.QLabel(self.frame_3)
        self.label_39.setGeometry(QtCore.QRect(280, 240, 31, 21))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.kled_CH3_A_SWITCH2 = KLed(self.frame_3)
        self.kled_CH3_A_SWITCH2.setGeometry(QtCore.QRect(100, 235, 28, 28))
        self.kled_CH3_A_SWITCH2.setState(KLed.Off)
        self.kled_CH3_A_SWITCH2.setObjectName(_fromUtf8("kled_CH3_A_SWITCH2"))
        self.label_40 = QtGui.QLabel(self.frame_3)
        self.label_40.setGeometry(QtCore.QRect(130, 200, 31, 21))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.label_41 = QtGui.QLabel(self.frame_3)
        self.label_41.setGeometry(QtCore.QRect(130, 240, 31, 21))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.label_42 = QtGui.QLabel(self.frame_3)
        self.label_42.setGeometry(QtCore.QRect(70, 240, 31, 21))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.kled_CH4_A_SWITCH2 = KLed(self.frame_3)
        self.kled_CH4_A_SWITCH2.setGeometry(QtCore.QRect(40, 235, 28, 28))
        self.kled_CH4_A_SWITCH2.setState(KLed.Off)
        self.kled_CH4_A_SWITCH2.setObjectName(_fromUtf8("kled_CH4_A_SWITCH2"))
        self.kled_CH1_A_SWITCH2 = KLed(self.frame_3)
        self.kled_CH1_A_SWITCH2.setGeometry(QtCore.QRect(40, 195, 28, 28))
        self.kled_CH1_A_SWITCH2.setState(KLed.Off)
        self.kled_CH1_A_SWITCH2.setObjectName(_fromUtf8("kled_CH1_A_SWITCH2"))
        self.label_43 = QtGui.QLabel(self.frame_3)
        self.label_43.setGeometry(QtCore.QRect(70, 200, 31, 21))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.kled_CH2_A_SWITCH2 = KLed(self.frame_3)
        self.kled_CH2_A_SWITCH2.setGeometry(QtCore.QRect(100, 195, 28, 28))
        self.kled_CH2_A_SWITCH2.setState(KLed.Off)
        self.kled_CH2_A_SWITCH2.setObjectName(_fromUtf8("kled_CH2_A_SWITCH2"))
        self.frame_5 = QtGui.QFrame(self.frame_3)
        self.frame_5.setGeometry(QtCore.QRect(20, 165, 301, 111))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.label_44 = QtGui.QLabel(self.frame_3)
        self.label_44.setGeometry(QtCore.QRect(20, 165, 301, 21))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.label_45 = QtGui.QLabel(self.frame_3)
        self.label_45.setGeometry(QtCore.QRect(40, 175, 121, 21))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.label_46 = QtGui.QLabel(self.frame_3)
        self.label_46.setGeometry(QtCore.QRect(190, 175, 121, 21))
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.label_47 = QtGui.QLabel(self.frame_3)
        self.label_47.setGeometry(QtCore.QRect(280, 115, 31, 21))
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.kled_CH2_A_SWITCH1 = KLed(self.frame_3)
        self.kled_CH2_A_SWITCH1.setGeometry(QtCore.QRect(100, 70, 28, 28))
        self.kled_CH2_A_SWITCH1.setState(KLed.Off)
        self.kled_CH2_A_SWITCH1.setObjectName(_fromUtf8("kled_CH2_A_SWITCH1"))
        self.kled_CH4_B_SWITCH1 = KLed(self.frame_3)
        self.kled_CH4_B_SWITCH1.setGeometry(QtCore.QRect(190, 110, 28, 28))
        self.kled_CH4_B_SWITCH1.setState(KLed.Off)
        self.kled_CH4_B_SWITCH1.setObjectName(_fromUtf8("kled_CH4_B_SWITCH1"))
        self.label_48 = QtGui.QLabel(self.frame_3)
        self.label_48.setGeometry(QtCore.QRect(220, 115, 31, 21))
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.kled_CH1_B_SWITCH1 = KLed(self.frame_3)
        self.kled_CH1_B_SWITCH1.setGeometry(QtCore.QRect(190, 70, 28, 28))
        self.kled_CH1_B_SWITCH1.setState(KLed.Off)
        self.kled_CH1_B_SWITCH1.setObjectName(_fromUtf8("kled_CH1_B_SWITCH1"))
        self.kled_CH1_A_SWITCH1 = KLed(self.frame_3)
        self.kled_CH1_A_SWITCH1.setGeometry(QtCore.QRect(40, 70, 28, 28))
        self.kled_CH1_A_SWITCH1.setState(KLed.Off)
        self.kled_CH1_A_SWITCH1.setObjectName(_fromUtf8("kled_CH1_A_SWITCH1"))
        self.kled_CH4_A_SWITCH1 = KLed(self.frame_3)
        self.kled_CH4_A_SWITCH1.setGeometry(QtCore.QRect(40, 110, 28, 28))
        self.kled_CH4_A_SWITCH1.setState(KLed.Off)
        self.kled_CH4_A_SWITCH1.setObjectName(_fromUtf8("kled_CH4_A_SWITCH1"))
        self.label_49 = QtGui.QLabel(self.frame_3)
        self.label_49.setGeometry(QtCore.QRect(130, 115, 31, 21))
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.label_50 = QtGui.QLabel(self.frame_3)
        self.label_50.setGeometry(QtCore.QRect(20, 40, 301, 21))
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.kled_CH2_B_SWITCH1 = KLed(self.frame_3)
        self.kled_CH2_B_SWITCH1.setGeometry(QtCore.QRect(250, 70, 28, 28))
        self.kled_CH2_B_SWITCH1.setState(KLed.Off)
        self.kled_CH2_B_SWITCH1.setObjectName(_fromUtf8("kled_CH2_B_SWITCH1"))
        self.label_51 = QtGui.QLabel(self.frame_3)
        self.label_51.setGeometry(QtCore.QRect(280, 75, 31, 21))
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.label_52 = QtGui.QLabel(self.frame_3)
        self.label_52.setGeometry(QtCore.QRect(70, 75, 31, 21))
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.label_53 = QtGui.QLabel(self.frame_3)
        self.label_53.setGeometry(QtCore.QRect(40, 50, 121, 21))
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.kled_CH3_A_SWITCH1 = KLed(self.frame_3)
        self.kled_CH3_A_SWITCH1.setGeometry(QtCore.QRect(100, 110, 28, 28))
        self.kled_CH3_A_SWITCH1.setState(KLed.Off)
        self.kled_CH3_A_SWITCH1.setObjectName(_fromUtf8("kled_CH3_A_SWITCH1"))
        self.label_54 = QtGui.QLabel(self.frame_3)
        self.label_54.setGeometry(QtCore.QRect(190, 50, 121, 21))
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.label_55 = QtGui.QLabel(self.frame_3)
        self.label_55.setGeometry(QtCore.QRect(130, 75, 31, 21))
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.label_56 = QtGui.QLabel(self.frame_3)
        self.label_56.setGeometry(QtCore.QRect(220, 75, 31, 21))
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.kled_CH3_B_SWITCH1 = KLed(self.frame_3)
        self.kled_CH3_B_SWITCH1.setGeometry(QtCore.QRect(250, 110, 28, 28))
        self.kled_CH3_B_SWITCH1.setState(KLed.Off)
        self.kled_CH3_B_SWITCH1.setObjectName(_fromUtf8("kled_CH3_B_SWITCH1"))
        self.label_57 = QtGui.QLabel(self.frame_3)
        self.label_57.setGeometry(QtCore.QRect(70, 115, 31, 21))
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.frame_6 = QtGui.QFrame(self.frame_3)
        self.frame_6.setGeometry(QtCore.QRect(20, 40, 301, 111))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Status", None))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p>CHAVE DE RF - SWITCH 2</p></body></html>", None))
        self.label.setText(_translate("Dialog", "<html><head/><body><p>RFFE</p></body></html>", None))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p>CHAVE DE RF - SWITCH 1</p></body></html>", None))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p>NETWORK ANALYZER</p></body></html>", None))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">COMUNICAÇÃO/AQUISIÇÃO DE DADOS</span></p></body></html>", None))
        self.label_14.setText(_translate("Dialog", "<html><head/><body><p>WAVEFORM GENERATOR</p></body></html>", None))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p>RESPOSTA EM FREQUÊNCIA</p></body></html>", None))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p>PARÂMETRO-S</p></body></html>", None))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p>RF SWITCH</p></body></html>", None))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p>ATENUADORES</p></body></html>", None))
        self.label_10.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">TESTES</span></p></body></html>", None))
        self.label_12.setText(_translate("Dialog", "<html><head/><body><p>RETURN LOSS</p></body></html>", None))
        self.label_13.setText(_translate("Dialog", "<html><head/><body><p>LINEARIDADE</p></body></html>", None))
        self.label_15.setText(_translate("Dialog", "<html><head/><body><p>CROSSTALK</p></body></html>", None))
        self.label_16.setText(_translate("Dialog", "<html><head/><body><p>TEMPERATURA</p></body></html>", None))
        self.label_27.setText(_translate("Dialog", "<html><head/><body><p>OK</p></body></html>", None))
        self.label_28.setText(_translate("Dialog", "<html><head/><body><p>Não será executado</p></body></html>", None))
        self.label_29.setText(_translate("Dialog", "<html><head/><body><p>Falhou</p></body></html>", None))
        self.label_30.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">LEGENDA</span></p></body></html>", None))
        self.label_31.setText(_translate("Dialog", "<html><head/><body><p>Status ainda não avaliado</p></body></html>", None))
        self.label_32.setText(_translate("Dialog", "<html><head/><body><p>Em execução</p></body></html>", None))
        self.OK_Button.setText(_translate("Dialog", "OK", None))
        self.label_33.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">CANAL ATIVO - CHAVE RF</span></p></body></html>", None))
        self.label_36.setText(_translate("Dialog", "<html><head/><body><p>CH2</p></body></html>", None))
        self.label_37.setText(_translate("Dialog", "<html><head/><body><p>CH4</p></body></html>", None))
        self.label_38.setText(_translate("Dialog", "<html><head/><body><p>CH1</p></body></html>", None))
        self.label_39.setText(_translate("Dialog", "<html><head/><body><p>CH3</p></body></html>", None))
        self.label_40.setText(_translate("Dialog", "<html><head/><body><p>CH2</p></body></html>", None))
        self.label_41.setText(_translate("Dialog", "<html><head/><body><p>CH3</p></body></html>", None))
        self.label_42.setText(_translate("Dialog", "<html><head/><body><p>CH4</p></body></html>", None))
        self.label_43.setText(_translate("Dialog", "<html><head/><body><p>CH1</p></body></html>", None))
        self.label_44.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">SWITCH 2</span></p></body></html>", None))
        self.label_45.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">A</span></p></body></html>", None))
        self.label_46.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">B</span></p></body></html>", None))
        self.label_47.setText(_translate("Dialog", "<html><head/><body><p>CH3</p></body></html>", None))
        self.label_48.setText(_translate("Dialog", "<html><head/><body><p>CH4</p></body></html>", None))
        self.label_49.setText(_translate("Dialog", "<html><head/><body><p>CH3</p></body></html>", None))
        self.label_50.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">SWITCH 1</span></p></body></html>", None))
        self.label_51.setText(_translate("Dialog", "<html><head/><body><p>CH2</p></body></html>", None))
        self.label_52.setText(_translate("Dialog", "<html><head/><body><p>CH1</p></body></html>", None))
        self.label_53.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">A</span></p></body></html>", None))
        self.label_54.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">B</span></p></body></html>", None))
        self.label_55.setText(_translate("Dialog", "<html><head/><body><p>CH2</p></body></html>", None))
        self.label_56.setText(_translate("Dialog", "<html><head/><body><p>CH1</p></body></html>", None))
        self.label_57.setText(_translate("Dialog", "<html><head/><body><p>CH4</p></body></html>", None))

from PyKDE4.kdeui import KLed

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

